### ISSUE TITLE
 Client cli(server, port);  delay with hostname instead of ip

### ISSUE THREAD

**Issue by toutant** [yhirose/cpp-httplib#1006]
Client cli("Temp-PC",8100); takes over 5 seconds to post
 Client cli("192.168.1.14",8100); takes 10th of a second to post

 this function seems to be where the time delay is 
return detail::create_client_socket(
			host_.c_str(), port_, address_family_, tcp_nodelay_, socket_options_,
			connection_timeout_sec_, connection_timeout_usec_, read_timeout_sec_,
			read_timeout_usec_, write_timeout_sec_, write_timeout_usec_, interface_,
			error);

**Comment by yhirose** [comment]
@toutant, thanks for the feedback. I think this isn't an issue of cpp-httplib, but  a general TCP/IP socket issue, since `detail::create_client_socke` doesn't do any special treatment rather than calling raw socket system calls.
Please provide more information if you still think it's a really cpp-httplib issue. Thanks!

**Comment by toutant** [comment]
your server code is fantastic by the way - flexible and fast - perfect.
client code is also so easy and flexible - very nice ...

It is somewhere in your code - this is a highly repeatable issue - 

simple try your client code  connecting to your server software using url such as http://temp-pc:8100/test
and then try with ip http://192.168.1.14:8100/test

in my tests server and client are on same computer....there should not be 4-5 second delay - after days of trying to find the issue - i changed name to the IP and everything worked perfectly

**Comment by yhirose** [comment]
@toutant, could you trace down the code and identify which line in httplib.h is really slow? Otherwise, I can't give you any meaningful information...

Also if the code which causes the delay in httplib.h is the following line, there is not way to fix the problem and it's simply a problem in your network environment.

https://github.com/yhirose/cpp-httplib/blob/ccbddd88423d9ce364bfbaada130c36fa2fc1bd6/httplib.h#L2120

Hope you will find the network issue and get your project going soothly!

**Comment by toutant** [comment]
I do not know where the exact slowness is in your library - i will once my current commitment is done 
- you can do your own test as mentioned above if you want to track down the error. 
- I have tested on several different networks - issue is big delay unless IP is used ( using latest code )

I added my own simple hostname lookup before using your client and it solved the issue

const char c = server.at(0);
	bool isDigit = (c >= '0' && c <= '9');
	if (!isDigit) {
		printf("looking up hostname %s\n", server.c_str());
		hostent * record = gethostbyname(server.c_str());
		if (record == NULL)
		{
			 
			printf("lookup failed\n");
		}
		else {
			in_addr * address = (in_addr *)record->h_addr;
			char *s = inet_ntoa(*address);
			std::string n(s);
			server = n;

			printf("success hostname to ip %s\n", server.c_str());
		}
	}

//then call server 

 Client cli(server, port);
	 
	 cli.Post(url.c_str(), data.c_str(), datatype.c_str());

**Comment by PixlRainbow** [comment]
Hi, this delay occurs due to system-level name resolution. Sometimes the system attempts to search on the wrong networks to resolve a domain. By performing a hostname lookup first, the system will cache the IP address so the subsequent connection by httplib is faster.  
However, I note that you appear to be using NetBIOS ("Windows-style workgroup computer name") name resolution. Note that this is distinct from DNS resolution and may be slower. NetBIOS name resolution works by broadcasting a packet to all computers on the network and waiting for the respective computer to respond. DNS works by sending a request to a specific name server, which will perform a lookup from its internal database and return the result.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the clear explanation!

**Comment by toutant** [comment]
Like I said... My host name lookup is fast yours takes 4 to 5 seconds... So
something is up with your code

**Comment by PixlRainbow** [comment]
you are using the older `gethostbyname` (deprecated) which only supports IPv4. httplib is using the newer `getaddrinfo` which supports both IPv6 and IPv4. httplib configures `getaddrinfo` to "use whichever is available". However, some systems may have a bug where IPv6 resolving does not work correctly and will stall until it times out, whereupon it then falls back to IPv4, which resolves immediately.

The online community is aware of this issue, but there does not seem to be agreement on how this can be fixed other than to turn off IPv4 at the system level, which may not always be desirable for some.
