### ISSUE TITLE
redeclaring URLs 

### ISSUE THREAD

**Issue by LittleSOiLent999** [yhirose/cpp-httplib#1007]
they say I want to do a git requests to 
httplib::Client cli("https://lumtest.com");
you did what you want there 
lets say you 
auto res = cli.Get("/");
/* did what you needed with the response */
and now I want to scrap google.com
how do I not called httplib::Client cli 
this way ? couldnt find and API DOC 
do I just do ? httplib::Client cli("https://google.com");
its not clear :) anyways have a great day 

btw I am a GCC user if it matters

**Comment by yhirose** [comment]
@LittleSOiLent999, sorry that I don't fully understand what you are asking though, I try to answer according to your title. :)

```cpp
#include <httplib.h>
#include <iostream>

using namespace std;

int main(void) {
  httplib::Client cli("http://google.com");
  cli.set_follow_location(true);

  if (auto res = cli.Get("/")) {
    cout << res->body << endl;
  } else {
    cout << res.error() << endl;
  }

  return 0;
}
```

**Comment by PixlRainbow** [comment]
If you want to change to a different domain, then yes, you will have to destroy and reconstruct the client object. This is because you have to establish a new connection instance to a different server.
If you want to just browse different URLs on the same domain, you can call `Get` with the new path on the old client object.
