### ISSUE TITLE
unexpected ssl error with https:// urls

### ISSUE THREAD

**Issue by kritzikratzi** [yhirose/cpp-httplib#1018]
i'm using v0.9.2 with openssl on osx. 

for me this works: 

    httplib::SSLClient cli("my-host", 443); 

while this fails to verify the certificate: 

    httplib::SSLClient cli("https://my-host", 443); 

you can set a debug point at the top of this loop, nothing will match: 

https://github.com/yhirose/cpp-httplib/blob/469c6bc2b611ec5d212275e559e58e4da256019d/httplib.h#L7330-L7347

for me it's no problem at all, i was just really thrown off by the behavior.

**Comment by yhirose** [comment]
@kritzikratzi thanks for the feedback. This is an expected behavior. Here is the constructor code in httplib.h. The first parameter takes only 'host', not 'scheme_host'.

https://github.com/yhirose/cpp-httplib/blob/469c6bc2b611ec5d212275e559e58e4da256019d/httplib.h#L1418

If you want to include 'scheme', `http::Client` can allow you to do it:

https://github.com/yhirose/cpp-httplib/blob/469c6bc2b611ec5d212275e559e58e4da256019d/httplib.h#L1189

So, you can do this: `httplib::Client cli("https://my-host:443");` or `httplib::Client cli("https://my-host");`

You can see the same information [here](https://github.com/yhirose/cpp-httplib#ssl-support) in README.

Hope it helps!
