### ISSUE TITLE
DNS resolve

### ISSUE THREAD

**Issue by zhenyolka** [yhirose/cpp-httplib#1066]
This library relies on getaddrinfo to get server IP address, while using SSLClient for example.
But what if DNS requests spoofed by ISP to block access to server or any other problem with system nameservers, or I just want to use DoH protocol.
Maybe it will be better to allow to pass server IP address in Client constructors as optional argument to bypass these problems and don't resolve address in library code in this case?

**Comment by yhirose** [comment]
@zhenyolka, thank you for the feedback. I honestly know little about DoH. Could you send a pull request to show what changes are necessary to support it? Thanks!

**Comment by zhenyolka** [comment]
@yhirose ok. I will try to add it manually. You don't need to implement DoH, just need to allow to specify IP address manually in SSLClient constructor instead of resolve IP address

**Comment by PixlRainbow** [comment]
SSLClient can be used with a direct IP address if you specify it in place of the hostname. However, note that doing this may compromise the security of your application as we will not be able to verify the server certificate, since the certificates are usually signed against the domain name, not the IP address

**Comment by yhirose** [comment]
@zhenyolka, could you give us your response to the above comment from @PixlRainbow regarding the compromise of security?

**Comment by yhirose** [comment]
Implemented in #1067.
