### ISSUE TITLE
connection support login

### ISSUE THREAD

**Issue by nblog** [yhirose/cpp-httplib#107]
Is it possible to increase the login account at the time of connection?

such as:
curl_easy_setopt(curl, CURLOPT_USERPWD, userpwd);

**Comment by yhirose** [comment]
@nblog, It would be nice to implement the feature. But as see the actual code in curl, it involves lots of things to consider.
https://github.com/curl/curl/search?l=C&q=user_passwd

So I am not planning to implement the similar feature in cpp-httplib, since I don't need it yet and have time to work on it. Of course a pull request from you is always welcome!

Thank you for your feedback.
