### ISSUE TITLE
What's the behavior regarding client read timeout

### ISSUE THREAD

**Issue by liuzqt** [yhirose/cpp-httplib#1074]
As the title said.

I was using the client sent some Post requests to my server and the request might cause some long-running IO operation on server side(~15s), I think the default read timeout is 10s or something, because I noticed that after 10s, the httplib client report a read error and exit, but the connection seems still alive because my server is still running some worker thread to handle that request.

**Comment by yhirose** [comment]
@liuzqt, thanks for the feedback, The default read timeout is 5s. Also `Error::Read` represents an error of failure of reading with various reasons. So the problem happens after 10s, this is not caused by the reading timeout. Hope it helps.

https://github.com/yhirose/cpp-httplib/blob/b80aa7fee31a8712b1d3cae05c1d9e7f5c436e3d/httplib.h#L32
