### ISSUE TITLE
`ParseAcceptEncoding` tests failing when compiling the library

### ISSUE THREAD

**Issue by Tachi107** [yhirose/cpp-httplib#1087]
Hi, I'm consistently getting test failures when building the library with Meson and `cpp-httplib_compile=true`.

`ParseAcceptEncoding1`, `2` and `3` are all failing.

When setting `cpp-httplib_compile=false`, no failures occur.

I've setup a CI job that tests the compiled library in a different branch to show the failures, you can find it here: #1088

**Comment by yhirose** [comment]
@Tachi107, thanks for the report. Since I don't use the compiled version at all on my any project, could you look into it deeper to see why it happens only on the compiled version? If it's hard to track down the reason, I am thinking to get rid of the feature, because it's requested by users for their benefit. Thanks!

**Comment by Tachi107** [comment]
Ok, I'll try to figure out why it happens :)

**Comment by Tachi107** [comment]
Turns out the issue wasn't really related to the split script, but a small issue with the Meson build file. Basically, flags like `-DCPPHTTPLIB_ZLIB_SUPPORT` were only used for the compilation of the library, and not when actually using it in external code. This meant that users would use the library as if all the various extra feature weren't available, while they actually were. Simple fix, I'm preparing a PR now
