### ISSUE TITLE
Boost regex replacement

### ISSUE THREAD

**Issue by ratman** [yhirose/cpp-httplib#1105]
Hi Together! My issue is rather a question. The library is supposed to be unusable with GCC 4.8 and above for well-known issues. As I see, std::regex is not that central in the library and it looks not impossible to me to replace it with boost regexes for the first sight. Of course, it would lose the nice singleheaderonlyness, but it would work on my cursed legacy embedded devices. I would do it by myself, but is there any hindrance doing that or just simply no one tried yet? Thanks in advance!

**Comment by yhirose** [comment]
@ratman, thank you for the feedback. I don't have any plan to try to use the boost regex instead of std::regex, because I don't need it and I would not like to add any other dependency to this library. I guess it's not too hard for you to try it with your fork of cpp-httplib, since the interface of boost::regex maybe similar to std::regex. Hope your project will go well!

**Comment by ratman** [comment]
@yhirose I thank you, the library is a great work and I have big respect for your long term enthusiasm for it. That's why I did not want to replace it for my legacy project. The good news is that the interface seems to be the same in fact, so I only needed a namespace alias for switching boost/std and a compile definition for defining the alias. I do not know if it makes sense to push it here on a branch, is not a big deal. I leave this comment here in case someone is interested ;)

**Comment by yhirose** [comment]
@ratman, glad to heat the news! You could put the link to your branch here, so that others could benefit from it. Thanks!
