### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by marcovc** [yhirose/cpp-httplib#1138]
Hi,

I'm trying to debug a deadlock, where once in a while a request seems to be running forever. I'm wondering if this has anything to do with exceptions, since apparently this happens whenever there is an exception. 

I've installed an exception handler with

```c++
server.set_exception_handler([&](const auto& req, auto& res, std::exception &e)
```

Say that an uncaught exception is thrown inside

```c++
  server.Post("/solve", [&](const httplib::Request& req, httplib::Response &res)
```

The library correctly calls my exception handler. I am assuming that the thread handling the request where the uncaught exception was thrown will join the worker pool ready to process another request. Is this not the case?

**Comment by yhirose** [comment]
@marcovc, thanks for the feedback. I have never experience the situation like 'once in a while a request seems to be running forever'. Could you make the smallest possible sample code to reproduce the problem, so that I can take a look at the problem.

> I am assuming that the thread handling the request where the uncaught exception was thrown will join the worker pool ready to process another request.

I don't fully understand what you mean with the sentence. Could you explain more clearly?

Thanks!

**Comment by marcovc** [comment]
Thanks for the quick reply! 

It is unfortunately very hard to replicate, but I will try to come up with a small example.

Maybe my assumptions are wrong, but this is my model: I assume there is a thread pool (or worker pool) with N threads waiting. Also I assume when a new request is made to the server, a worker/thread is assigned to run the function attached to the request handler. My question is: in the case the function attached to the request handler throws an exception and does not handle it, will that worker thread rejoin the thread pool and become ready to serve the next request, or will it somehow become stale?

**Comment by yhirose** [comment]
@marcovc, I still cannot tell what really causes the issue unless it can be reproducible, because a premature guess most likely turns out incorrect. :)

What I can tell at this point is where the exception handing is cared. Here is the code:

https://github.com/yhirose/cpp-httplib/blob/20056f6cdaed7c8006d58fc2498c2861efdf375d/httplib.h#L5563-L5576

As you can see the above code, exceptions inherited from `std::exception` will be caught at line 5565, and any other exceptions will be caught at 5573. Any 'exception leak' cannot occur according to this implementation.

The following is my unit test for `set_exception_handler`. You might get some information from it.

https://github.com/yhirose/cpp-httplib/blob/20056f6cdaed7c8006d58fc2498c2861efdf375d/test/test.cc#L1195-L1243

Hope it helps.

**Comment by marcovc** [comment]
Thanks for the help. It turned out this was unrelated to exceptions (and to this library). Closing!
