### ISSUE TITLE
Multi host with multiple SSL certificates server

### ISSUE THREAD

**Issue by alphamarket** [yhirose/cpp-httplib#1155]
Hey, We want to create something like `nginx` which we are going to host multiple domains and each of them will have its own certificate files, when a request comes in, we will check what is the domain name and load its certificate files, and establish the connection, how we can do that with this library?

**Comment by yhirose** [comment]
@alphamarket, thank you for the question. Unfortunately, the simple HTTP library doesn't support such multiple virtual hosts, and I am not planing to support it because it requires lots of code changes and even interface changes. Sorry about that. Hope you will find other HTTP libraries which give you such capability!
