### ISSUE TITLE
Simple example doesnt work + no info what happened

### ISSUE THREAD

**Issue by M0n7y5** [yhirose/cpp-httplib#1185]
Hi i have this code:
![image](https://user-images.githubusercontent.com/17201053/152622259-17a068e4-3037-4711-9f56-85cb7a2b38c2.png)

For some reason i am getting this error 
![image](https://user-images.githubusercontent.com/17201053/152622546-7d1c420a-1f44-42c4-859d-13d619cdc71f.png)
![image](https://user-images.githubusercontent.com/17201053/152622568-24a35877-78ee-4019-a778-4503a21b9f64.png)

What this error means? Server refused connection? Client is blocked by firewall?

**Comment by yhirose** [comment]
`httplib::Client cli("https://google.com")` should work. Please see the following information in README.
https://github.com/yhirose/cpp-httplib#client

**Comment by PixlRainbow** [comment]
you need to check if response is null. Response will be null if httplib could not get a response from the server, either because a connection could not be made, or because of failed security check, or server connected but did not send anything before timeout.

In the case of Connection, it is just a general error meaning connection cannot be created. Because of limitation of Operating System (Windows/Mac/Linux) network API, we cannot identify _why_ a connection cannot be made, just that it happened.
