### ISSUE TITLE
How to send data to server through other thread?

### ISSUE THREAD

**Issue by xjsxujingsong** [yhirose/cpp-httplib#1186]
Hi, this question may be a little beyond this repo. 
I am would like to use this repo to host as a server. The data hosted in the server may come from the other thread. Not sure how to transfer data here. Any thoughts?
Thank you.

**Comment by yhirose** [comment]
@xjsxujingsong, I probably don't fully understand what you are asking for. But at least the following code shows a simple example of using a thread to supply data to a HTTP handler. Hope it helps.

```
#include <httplib.h>
using namespace httplib;

int main(void) {
  Server svr;

  svr.Get("/hi", [](const Request & /*req*/, Response &res) {
    std::string data;
    auto t = std::thread([&]() {
      data = "hello world!";
    });
    t.join();
    res.set_content(data, "text/plain");
  });

  svr.listen("0.0.0.0", 8080);
}
```

**Comment by PixlRainbow** [comment]
you can simply store the data in a global variable (simple to implement, but not recommended for large projects due to potential naming conflicts) and then just access the global variable from the request handler. Or you can pass a specific object by reference using the scope operator and then call a function on that object to retrieve the needed data. e.g. 
```cpp
// your request handler
// instead of [](const Request &, Response &res) 
[&myObject](const Request &, Response &res) {
  res.set_content(myObject.getData(), "application/octet-stream");
}
```
Of course, take care to handle race conditions (data access from multiple threads).

**Comment by xjsxujingsong** [comment]
Thank you very much for both of you. I may define a global atomic variable to avoid potential multi.thread problem.
