### ISSUE TITLE
SSE crashes under heavy load

### ISSUE THREAD

**Issue by kokseen1** [yhirose/cpp-httplib#1192]
When using the ssesvr.cc and ssecli.cc examples, removing the line `this_thread::sleep_for(chrono::seconds(1));` from the server code will cause the client to crash after running for a period of time. The crashes occur especially when multiple programs are running at once (e.g. many Chrome tabs, Wireshark, etc.). 
Is there any fix for this issue? My project requires sending SSE with high frequency. Thanks!

**Comment by yhirose** [comment]
@kokseen1, honestly, that is just a simple **example** of SSE support, not production level code. So please don't use it production... I think you could improve `EventDispatcher` in order to handle socket connection management more properly. But I don't have time to work on it now. Sorry about that...

Supporting SSE or WebSocket is out of scope of cpp-httplib at this point. But pull requests for such higher level protocols/applications are always welcome. :)
