### ISSUE TITLE
Avoid having request headers in a separate package

### ISSUE THREAD

**Issue by au-ee** [yhirose/cpp-httplib#1203]
Hi @yhirose ,

thanks for this awesome package and thanks for the quick merge, yesterday!

While evaluating cpp-httplib for use in our application, we did a bit of network tracing and discovered that the header of the http request is always sent as a separate package due to the `write_data` in line 6227. This causes a small tcp frame to be sent immediately with the PSH flag set.

The result is that each http request gets split up into two tcp frames at minimum. Which causes a bit of overhead which is usually not critical, but again, can sum up to gigabytes of cellular data volume per month in an iot application.

You know the library and its surroundings better: Do you see any chance to combine sending the header together with the body without having to copy too much data around or do you see a chance to make the stream/socket wait for more data before it is flushed to the network?

Thanks,

Markus

**Comment by PixlRainbow** [comment]
It's been a while since I dug in depth into the implementation of httplib, but as far as I can remember, httplib depends on the system's socket library implementation to handle buffering, and does not by default flush the buffer until the content body is reached.
If the headers are being sent as a separate frame, it suggests that your system's network buffer is disabled, either due to nodelay option or other reasons.
It may still be possible to rewrite httplib to use the existing `BufferStream` instead of depending on the system network buffer, but I am not sure.

**Comment by yhirose** [comment]
@au-ee, as @PixlRainbow mentioned, cpp-httplib relies on the system's socket library implementation. If you would like to control data buffering, you can make your own stream calls by inheriting from `Stream` interface and replace `SocketStream` with yours. Hope it helps!

https://github.com/yhirose/cpp-httplib/blob/d73395e1dc652465fa9524266cd26ad57365491f/httplib.h#L4651-L4660

**Comment by au-ee** [comment]
@PixlRainbow @yhirose - Thanks for your thoughts!
