### ISSUE TITLE
Request: Add support for sending files as multipart form data

### ISSUE THREAD

**Issue by slowriot** [yhirose/cpp-httplib#121]
The server can receive multipart form data, but I don't see a straightforward way to send multipart form data using the client.  If this is possible already, apologies for the noise - please let me know how I should go about it.  Otherwise, please add functionality to send multipart files with the client.

**Comment by yhirose** [comment]
@slowriot, thanks for the feedback. The client currently doesn't support a 'straightforward way' to send multipart form data. 

Of course, you can construct HTTP header and body for mutipart form data by hand with consulting [RFC 7578](https://tools.ietf.org/html/rfc7578), since it's just a post message.
https://stackoverflow.com/questions/4238809/example-of-multipart-form-data

When I have time, I'll try to implement this. Thanks!
