### ISSUE TITLE
Propgram has exited with code 0 (0x0)

### ISSUE THREAD

**Issue by kras95** [yhirose/cpp-httplib#1224]
Hello,

I'm having trouble running the server with SSL.

I created my certificate and key with the following command:
`openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem`

I'm compiling with Visual Studio 2017 Community Edition (15.9.43)

The HTTP server runs fine, but the HTTPS example just closes with code 0.
I think that this might be the SIGPIPE issue, but SIGPIPE is not defined for me.
The program doesn't even go into the signalHandler to prevent the program from closing.

```
#define CPPHTTPLIB_OPENSSL_SUPPORT

#include <iostream>
#include <csignal>
#include "httplib.h"

using namespace std;

void signalHandler(int signum) {
	std::cout << "Signal: " << signum << std::endl;
}

int main() {
	signal(SIGINT, signalHandler);

	httplib::SSLServer svr("./cert.pem", "./key.pem");

	svr.Get("/", [](const httplib::Request& req, httplib::Response& res) {
		res.set_content("test", "text/plain");
	});

	svr.listen("0.0.0.0", 8080);

	return 0;
}
```

**Comment by yhirose** [comment]
Hope this helps.
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/signal?view=msvc-170

**Comment by mcordova1967** [comment]
@kras95 The https server does not run at all, or it does abort after processing some requests? In any case the SIGPIPE problem should only happen if the server tries to write to a socket closed by client, is that your case?

If the https server is not running at all then I think you may have another problem, not having the PEM files in the same directory as your EXE does cause this problem, the SSLServer constructor does not trigger an exception, which is a problem until you realize you did not place the PEM files in the expected location.

If your server is not running at all and you see exit code 0, I suspect the listen() fails and program goes straight to return 0;

I suggest intercepting more signals with your signalHandler() if the cause of the problem is in fact signal, something like:

	std::signal(SIGINT, signalHandler);
	std::signal(SIGTERM, signalHandler);
	std::signal(SIGABRT, signalHandler);

SIGINT intercepts CTRL-C on Win/Linux and also service stop on Windows (I am using my https server as a Windows service), SIGTERM works for me on Linux when using kill -s SIGTERM, I have not intercepted a SIGABRT yet but I left it in place just in case.

Regards.

**Comment by kras95** [comment]
@mcordova1967 I think SIGPIPE is not supported in Windows.
I have added the following signal handlers and still no luck.
```
	signal(SIGABRT, signalHandler);
	signal(SIGFPE, signalHandler);
	signal(SIGILL, signalHandler);
	signal(SIGINT, signalHandler);
	signal(SIGSEGV, signalHandler);
	signal(SIGTERM, signalHandler);
	signal(EINVAL, signalHandler);
```

Yes, apparently the server doesn't run at all. The program jumps straight to return 0.
The certificates are in the same directory as the executable file.

@yhirose I read in the signal documentation that "Win32 operating systems generate a new thread to specifically handle that interrupt", could this be the issue here? I'm wondering if this signal can be caught at all. I'm compiling it on 32 bit.

**Comment by mcordova1967** [comment]
@kras95 I don't think it has to go with any signal, it's going straight to return 0; that happens when httplib::SSLServer svr("./cert.pem", "./key.pem"); fails, for any reason, if possible I suggest debug and step into the constructor to see where it goes, considering you are sure the .pem files are in place, another problem must be happening inside the constructor, my guess.

Regards.
