### ISSUE TITLE
Handle authorization for server and client

### ISSUE THREAD

**Issue by omaralvarez** [yhirose/cpp-httplib#127]
Would it be possible to add authentication support. I have looked through the examples and have not found anything related to that. It would be nice if at least the client had support for basic authentication using RFC2045-MIME with Base64 encoded user and password.

**Comment by yhirose** [comment]
@omaralvarez, thank you for the feedback. I added a unit test which shows how to do the basic authentication. Please look at https://github.com/yhirose/cpp-httplib/blob/master/test/test.cc#L297-L324.

As you can see there, we can use `httplib::Headers` to setup the basic authentication and pass it to a client HTTP method such as `Get`.  In order to handle Base64 encoding, you need to do by yourself, or let a Base64 encoding library do it. 

I thought about enhancing the client HTTP methods to take auth information as a parameter. But it doesn't look pretty at all. So unless I find better way or interface, I encourage people to use `httplib::Headers` even though it's not a convenient way.

Thanks for you idea. I'll keep it in mind, and might do something for it in the future when I have time.

**Comment by omaralvarez** [comment]
Thanks a lot for the quick response! Great project by the way!

I will take a look, I was exactly thinking of an option on the client methods, but if you think it does not fit naturally I trust your judgment. I will keep an eye from time to time to see if this is finally implemented.

**Comment by PixlRainbow** [comment]
@omaralvarez on a related note, check out #154. It's not nearly as convenient to end users and it's not nearly as elegant (access restrictions apply server-wide, not to specific pages) but it DOES allow you to restrict access only to users with credentials.

**Comment by omaralvarez** [comment]
@PixlRainbow Really nice, I was looking for a way to authenticate users and what you say is ideal.

**Comment by yhirose** [comment]
@omaralvarez, I implemented a helper function `make_basic_authentication_header` to make our life a bit easier. :)
https://github.com/yhirose/cpp-httplib#basic-authentication

**Comment by omaralvarez** [comment]
@yhirose You are the man! It works perfectly and this was exactly what I was looking for. Thanks a lot!
