### ISSUE TITLE
Recieve File as Client 

### ISSUE THREAD

**Issue by vikalp0299** [yhirose/cpp-httplib#1270]
Hi, I am very new to this and am using this library for a project. The examples helped me to understand how to upload a file from a client to server but how to download a file from server... I am not able to understand it. Can you please guide me to a function (for client and server) to download a file from the server?

**Comment by PixlRainbow** [comment]
1. use GET instead of POST
2. [use a content receiver](https://github.com/yhirose/cpp-httplib#receive-content-with-a-content-receiver-1) instead of content provider
3. inside the content receiver, use any method you like (either `std::ofstream` or plain C `FILE`) to stream one block of data to your file whenever the content receiver callback is triggered. The data is in `data` parameter and the number of bytes of the block is in `data_length` parameter.

For more information see https://github.com/yhirose/cpp-httplib/issues/1101#issuecomment-976414361

**Comment by vikalp0299** [comment]
Okay, so basically, we on the client side have to specify the file name, and we will only get the content of the file stored on the server. As opposed to upload in which we even send the file's name to the server? Do I understand this correctly?

**Comment by PixlRainbow** [comment]
The server *may* provide the file name [using a header value](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#as_a_response_header_for_the_main_body), but this is not a mandatory part of the HTTP spec, so not all servers will do this. Some servers use the URL as file name, but this is also not guaranteed for every web service.

Note that **if** the server uses a header to indicate file name, you will not be able to actually access the header from inside the content receiver; you will only be able to read the header after the response is fully received and parsed, which means that you may need to rename the file after you download it.

**Comment by vikalp0299** [comment]
Thanks alot, I am closing it
