### ISSUE TITLE
Server or Client failure when multiple clients send requests after each other

### ISSUE THREAD

**Issue by Rockybilly** [yhirose/cpp-httplib#1276]
I have been experiencing a problem with creating multiple clients to reduce the bottlenecking problem while using httplib. I tried to create a really simple code example, and encountered similar problems. 

Here is the code:

```
#include <iostream>
#include "include/httplib.h"
#include <thread>
#include <chrono>

#define CLIENT_COUNT 1

int main() {
    httplib::Server svr;

    svr.Get("/hi", [](const httplib::Request &, httplib::Response &res) {
        return 200;
    });

    std::cout << "Creating server." << std::endl;
    std::thread th(&httplib::Server::listen, &svr, "127.0.0.1", 9999, 0);
    std::this_thread::sleep_for(std::chrono::seconds(2));
    std::cout << "Started listening." << std::endl;

    httplib::Client* clients[CLIENT_COUNT];

    for(auto& client : clients){
        client = new httplib::Client("127.0.0.1:9999");
        client->set_read_timeout(1, 0);
        client->set_keep_alive(true);
    }

    for(auto& client : clients){
        auto r = client->Get("/hi");
        std::cout << r->status << " " << r.error() << std::endl;
    }

    std::cout << "Stopping server." << std::endl;

    auto t1 = std::chrono::high_resolution_clock::now();
    svr.stop();

    std::cout << "Joining thread." << std::endl;
    th.join();

    auto t2 = std::chrono::high_resolution_clock::now();
    auto td = std::chrono::duration_cast<std::chrono::milliseconds>(t2 - t1).count();

    std::cout << "Stopping the server took " << td << " ms." << std::endl;
    return 0;
}
```

Here are the outcomes:

`CLIENT_COUNT 1`

```
Creating server.
Started listening.
200 Success (0)
Stopping server.
Stopping the server took 5001 ms.
Joining thread.
```

`CLIENT_COUNT 3`

```
Creating server.
Started listening.
200 Success (0)
200 Success (0)
200 Success (0)
Stopping server.
Joining thread.
Stopping the server took 5004 ms.
```

`CLIENT_COUNT 5`

```
Creating server.
Started listening.
200 Success (0)
200 Success (0)
200 Success (0)
200 Success (0)
200 Success (0)
Stopping server.
Joining thread.
Stopping the server took 5003 ms.
```

`CLIENT_COUNT 9`

```
Creating server.
Started listening.
200 Success (0)
200 Success (0)
200 Success (0)
200 Success (0)
200 Success (0)
200 Success (0)
200 Success (0)
200 Success (0)

Process finished with exit code 11
```

exit code 11 turns out to be segmentation fault.

My conclusions and questions:

- There seems to be a limit of 8 clients, 9 clients test is failing. It is also the same in my original code.
- In my original code, the error presented itself as clients getting `Read` errors.
- This 5 second of wait in killing the server is consistent in this test code, however in my original code, it is not. It sometimes takes 5 seconds to stop the server, sometimes milliseconds. Is there a sleep line somewhere that I didn't see ?

Am I doing something wrong ?

**Comment by yhirose** [comment]
This is due to the thread pool count determined by the following code in httplib.h. I believe the count is 8 on your machine.

```cpp
#ifndef CPPHTTPLIB_THREAD_POOL_COUNT
#define CPPHTTPLIB_THREAD_POOL_COUNT                                           \
  ((std::max)(8u, std::thread::hardware_concurrency() > 0                      \
                      ? std::thread::hardware_concurrency() - 1                \
                      : 0))
#endif
```

You can make your code work with one of ways below:

1) Increase thread pool count with `CPPHTTPLIB_THREAD_POOL_COUNT` more than your simultaneous request count
2) Remove `client->set_keep_alive(true);`
3) Increase the read time out from 1 to more than 5 seconds, since the default value of  `CPPHTTPLIB_KEEPALIVE_TIMEOUT_SECOND` 5 seconds.
4) Simply `delete client` after a request is handled

The either way in the above should fix your problem.

Also your error handling code can be improved as below to show the error code.

```cpp
    for(auto& client : clients){
        auto r = client->Get("/hi");
        if(r){
            std::cout << r->status << " " << r.error() << std::endl;
        }
        else{
            std::cout << r.error() << std::endl;
        }
    }
```

Hope it helps.

**Comment by Rockybilly** [comment]
Shouldn't the server be able to handle more simultaneous requests than a predefined constant ? For example I could want my server to operate with 8 threads, but simply make the 9th request wait for response, rather than immediately return an error.

To my understanding, you are using this constant value `CPPHTTPLIB_THREAD_POOL_COUNT ` as also a maximum open connection count. Is there a way around this ? Because a 8 CPU computer could also be serving 1000 different connections all with keep_alives. It is also feasible in a hardware sense. But setting `CPPHTTPLIB_THREAD_POOL_COUNT  = 1000` would not be great because you may not need 1000 threads and need much more open connections than 1000.

Thank you for your time.

**Comment by yhirose** [comment]
It's very hard to implement the one best thread pool which can work on all the possible situations. That's why I made the interface `TaskQueue` , so that users can implement a better one and easily integrated it to a cpp-http server.

Please read the section [Default thread pool support](https://github.com/yhirose/cpp-httplib#default-thread-pool-support) and [Override the default thread pool with yours](https://github.com/yhirose/cpp-httplib#override-the-default-thread-pool-with-yours) for more information. If the default thread pool doesn't work for you, you should probably need to make your own task queue which fits in your needs.
