### ISSUE TITLE
Large URI payload handled incorrectly

### ISSUE THREAD

**Issue by lionkor** [yhirose/cpp-httplib#1288]
httplib denies any URI with length > CPPHTTPLIB_REQUEST_URI_MAX_LENGTH, even if the header `Content-Type` is set to `application/x-www-form-urlencoded`.

This can be reproduced by sending a form of size > 8192 to an httplib server. I believe this is due to a typo. PR coming up.

**Comment by yhirose** [comment]
@lionkor, thank you for the feedback. It's an intended behavior to protect a server from attacks. Please see #1134.

**Comment by lionkor** [comment]
The issue is that a large URI, which is accepted by all major web servers (like nginx), is getting rejected by cpp-httplib and there is no way to change the limit either.

This happens whent he request is an application/x-www-form-urlencoded.

So I'm understanding it's intended behavior that the URI can be any length, as long as it's not a form?

**Comment by yhirose** [comment]
@lionkor, both URI string and form-urlencoded string in payload are protected with `CPPHTTPLIB_REQUEST_URI_MAX_LENGTH`

URI string:
https://github.com/yhirose/cpp-httplib/blob/47044c05a8587dff86ab90526daabfef61079490/httplib.h#L5670

Form URL encoded string
https://github.com/yhirose/cpp-httplib/blob/47044c05a8587dff86ab90526daabfef61079490/httplib.h#L5192

As for the URL encoded string, it may be ok to introduce a new define symbol like `CPPHTTPLIB_FORM_URL_ENCODED_PAYLOAD_MAX_LENGTH`, so that a user can set larger length to it.

**Comment by yhirose** [comment]
@lionkor, `CPPHTTPLIB_FORM_URL_ENCODED_PAYLOAD_MAX_LENGTH` is now available in the latest httplib.h in the master branch. You can set an appropriated value that your server can accept for the application/x-www-form-urlencoded request.  (If a request containing a huge amount of form-urlencoded string is sent to cpp-httplib, it may affect the following query params parser which isn't fast and uses a certain amount of additional memory in nature.)

https://github.com/yhirose/cpp-httplib/blob/47044c05a8587dff86ab90526daabfef61079490/httplib.h#L5196

Hope it can resolve the issue that you are experience!
