### ISSUE TITLE
transfer closed with xxx bytes remaining to read

### ISSUE THREAD

**Issue by shiguowang** [yhirose/cpp-httplib#1293]
Hello, I want to use cpp-httplib as a http server. But When I use curl to get a large file, sometimes I got "transfer closed with xxx bytes remaining to read". After trying for a while, it still failed. Can you help me to find the problem?

Problem occur occasionally
![image](https://user-images.githubusercontent.com/3189971/170644093-c5b1d127-2887-47cd-9ef2-42ec35b38ea1.png)

this is my "server" code, very simple
![image](https://user-images.githubusercontent.com/3189971/170644414-ec91911f-254e-4b18-9fee-6a8408c28092.png)

**Comment by shiguowang** [comment]
@yhirose hello, what should I do now ? I notice you give a label "need more information to verify"

**Comment by yhirose** [comment]
@shiguowang 'need more information to verify' means that I haven't confirmed that the problem is reproducible on my machine, yet. When I have time, I'll try to do it on my macOS. Thanks for your patience!

**Comment by conghuawang** [comment]
@shiguowang maybe you should use "set_chunked_content_provider". example code:

svr.get("/test", [=](const httplib::Request& req, httplib::Response& resp)
{
    // open file
    const char* file_path = "D:/Project/hf_server/output/win64/bin/Debug/www/test.zip";
    std::ifstream file_reader(file_path, std::ifstream::binary);

    // get file size
    file_reader.seekg(0, file_reader.end);
    size_t file_size = file_reader.tellg();
    file_reader.seekg(0, file_reader.beg);

    // allocate buffer, and read the whole file into buffer
    char* buffer = new char[file_size];
    file_reader.read(buffer, file_size);

    // close file
    file_reader.close();

    const size_t chunk_len = 1024;

    resp.set_chunked_content_provider("application/octet-stream", [buffer, file_size, chunk_len](size_t offset, httplib::DataSink& sink) {
        if (file_size - offset >= chunk_len) {
            // write chunk
            sink.write(&buffer[offset], chunk_len);
        } else {
            // write last chunk
            sink.write(&buffer[offset], file_size - offset);
            // done after last chunk had write
            sink.done();
            // delete buffer
            delete[] buffer;
        }
        return true;
    }, [&](bool success) {
        // do nothing
    });
});


I recommand you that allocate a small buffer, and read file into buffer, and then write to DataSink. because if the file is very large, the buffer will be very large too.

**Comment by conghuawang** [comment]
@shiguowang if you realy want use "set_content_provider", this example code will help you:

```
svr.get("/test", [=](const httplib::Request& req, httplib::Response& resp)
{
    // open file
    const char* file_path = "D:/Project/hf_server/output/win64/bin/Debug/www/test.zip";
    std::ifstream file_reader(file_path, std::ifstream::binary | std::ifstream::in);

    // 404 not found
    if (!file_reader.good()) {
        resp.status = 404;
        resp.set_content("404 not found", "text/plain; charset=UTF-8");
        return;
    }

    // get file size
    file_reader.seekg(0, file_reader.end);
    size_t file_size = file_reader.tellg();
    file_reader.seekg(0, file_reader.beg);

    // allocate buffer
    std::vector<char> vec;
    vec.reserve(file_size);
    file_reader.read(&vec[0], file_size);
    auto buffer = new char[file_size];
    memcpy(buffer, &vec[0], file_size);

    // larger chunk size get faster download speed
    size_t chunk_len = 32 * 1024;

    resp.set_content_provider(file_size,
        "application/octet-stream",
        [buffer, file_size, chunk_len](size_t offset, size_t length, httplib::DataSink& sink) {
        if (file_size - offset >= chunk_len) {
            sink.write(&buffer[offset], chunk_len);
        } else {
            sink.write(&buffer[offset], file_size - offset);
            // whole buffer had write to sink, delet buffer
            delete[] buffer;
        }
        return true;
    });
});
```

notice that:
  1. don't use vec.insert(vec.begin(), std::istream_iterator<unsigned char>(file_reader), std::istream_iterator<unsigned char>());, it will take a long time to read large file into vec, the server's default "keep-alive-time" just 5 seconds. yout should instead it of file_reader.read(&vec[0], file_size);
  2. don't use std::copy(vec.begin(), vec.end(), buffer);, it take 3 iterator as arguments, you should instead it of memcpy(buffer, &vec[0], file_size);
  3. delete buffer in "ContentProvider", instead of delete buffer in "ContentProviderResourceReleaser". This way maybe cause memory leak due to "server error"
  4. this example read whole file into buffer, if the file is very large, it will task a large memory usage
  5. bigger chunk_len will get faster download speed

**Comment by conghuawang** [comment]
@shiguowang and there is a better way to send a large file to client use "set_chunked_content_provider"
  1. fast download speed
  2. no memory leak risk
  3. very small memory usage
  4. check file exists, cancel process if open file failed
  5. check file size, cancel process if file size is less than offset

example code:
```
svr.get("/test", [=](const httplib::Request& req, httplib::Response& resp)
{
    // file path
    const char* file_path = "D:/Project/hf_server/output/win64/bin/Debug/www/test.zip";
    
    // 404 not found, can't open file
    if (!std::ifstream(file_path, std::ifstream::binary | std::ifstream::in).good()) {
        resp.status = 404;
        resp.set_content("404 not found", "text/plain; charset=UTF-8");
        return;
    }

    resp.set_chunked_content_provider("application/octet-stream", [file_path](size_t offset, httplib::DataSink& sink) {
        // open file
        std::ifstream file_reader(file_path, std::ifstream::binary | std::ifstream::in);

        // can't open file, cancel process
        if (!file_reader.good())
            return false;

        // get file size
        file_reader.seekg(0, file_reader.end);
        size_t file_size = file_reader.tellg();
        file_reader.seekg(0, file_reader.beg);

        // check offset and file size, cancel process if offset >= file_size
        if (offset >= file_size)
            return false;
        
        // larger chunk size get faster download speed, more memory usage, more bandwidth usage, more disk I/O usage
        const size_t chunk_size = 32 * 1024;

        // prepare read size of chunk
        size_t read_size = 0;
        bool last_chunk = false;
        if (file_size - offset > chunk_size) {
            read_size = chunk_size;
            last_chunk = false;
        } else {
            read_size = file_size - offset;
            last_chunk = true;
        }

        // allocate temp buffer, and read file chunk into buffer
        std::vector<char> buffer;
        buffer.reserve(chunk_size);
        file_reader.seekg(offset, file_reader.beg);
        file_reader.read(&buffer[0], read_size);
        file_reader.close();

        // write buffer to sink
        sink.write(&buffer[0], read_size);

        // done after last chunk had write to sink
        if (last_chunk)
            sink.done();

        return true;
    });
});
```

**Comment by conghuawang** [comment]
@shiguowang in your original code, yout pass buffer to ContentProviderResourceReleaser as pointer reference in lambda capture, it will cause the buffer pointer as a wild pointer, when you delete the buffer, server will capture a exception, and the buffer can't be delete.

you can use "[buffer]" instead of "[&]" to fix this problem. The README.md give you the correct way to use it:
![Untitled](https://user-images.githubusercontent.com/16575549/170928624-eee692fa-1f1a-4426-9ce7-fa58e79ca8e6.png)

**Comment by shiguowang** [comment]
@conghuawang what is the difference between "set_chunked_content_provider" and "set_content_provider"? their parameters are almost the same.  which one is better If my use case is transfer large binary file, larger than 5G bytes.

and I do some test:
1、yes, "file_read.read(&vec[0], file_size)" is faster than "vec.insert(vec.begin())", time used are 23015ms vs 199ms when file_size is 270M+ bytes on my computer.

2、but "std::copy" and "memcpy" use almost same time.

**Comment by conghuawang** [comment]
@shiguowang 
if use method "set_chunked_content_provider", you have to call sink.done() manully when all data had wirte to sink. 
if use method "set_content_provider", you dont need to call sink.done() manully, because you pass "file_size" as a paramter to "set_content_provider", the server will auto process it.

both of "set_content_provider" and "set_chunked_content_provider" are good ways to send 5GB file to client, it based on your code impl. just remember that dont allocate big buffer for large files.
"set_chunked_content_provider" example: https://github.com/yhirose/cpp-httplib/issues/1293#issuecomment-1140395307
"set_content_provider" example:
```
svr.get("/test1", [=](const httplib::Request& req, httplib::Response& resp) {
    // open file
    const char* file_path = "D:/Project/hf_server/output/win64/bin/Debug/www/test.zip";
    std::ifstream file_reader(file_path, std::ifstream::binary | std::ifstream::in);

    // 404 not found
    if (!file_reader.good()) {
        resp.status = 404;
        resp.set_content("404 not found", "text/plain; charset=UTF-8");
        return;
    }

    // get file size
    file_reader.seekg(0, file_reader.end);
    size_t file_size = file_reader.tellg();
    file_reader.seekg(0, file_reader.beg);

    resp.set_content_provider(file_size, 
        "application/octet-stream",
        [file_path](size_t offset, size_t length, httplib::DataSink& sink) {
        // open file
        std::ifstream file_reader(file_path, std::ifstream::binary | std::ifstream::in);

        // can't open file, cancel process
        if (!file_reader.good())
            return false;

        // get file size
        file_reader.seekg(0, file_reader.end);
        size_t file_size = file_reader.tellg();
        file_reader.seekg(0, file_reader.beg);

        // check offset and file size, cancel process if offset >= file_size
        if (offset >= file_size)
            return false;

        // larger chunk size get faster download speed, more memory usage, more bandwidth usage, more disk I/O usage
        const size_t chunk_size = 32 * 1024;

        // prepare read size of chunk
        size_t read_size = 0;
        if (file_size - offset > chunk_size){
            read_size = chunk_size;
        } else {
            read_size = file_size - offset;
        }

        // allocate temp buffer, and read file chunk into buffer
        std::vector<char> buffer;
        buffer.reserve(chunk_size);
        file_reader.seekg(offset, file_reader.beg);
        file_reader.read(&buffer[0], read_size);
        file_reader.close();

        // write buffer to sink
        sink.write(&buffer[0], read_size);

        return true;
    });
});
```


the "std::copy" maybe cause "file is broken" error on client, because std::copy can't copy all data from vec iterator to buffer pointer, this code snipets show you the differences:
```
// init vec with 2 bytes
std::vector<char> tvec;
tvec.reserve(2);
// set values to tvec
tvec[0] = 0;
tvec[1] = 1;
// new buff with 2 bytes
char* tbuff = new char[2];
// test case 1, std::copy from vec iterator to buff pointer
memset(tbuff, -1, 2);
std::copy(tvec.begin(), tvec.end(), tbuff);
printf("test case 1, vec: %d %d buff: %d %d\n", tvec[0], tvec[1], tbuff[0], tbuff[1]);
// test case 2, std::copy from vec pointer to buff pointer
memset(tbuff, -1, 2);
std::copy(&tvec[0], &tvec[0] + 2, tbuff);
printf("test case 2, vec: %d %d buff: %d %d\n", tvec[0], tvec[1], tbuff[0], tbuff[1]);
// test case 3, std::copy_n from vec iterator to buff pointer
memset(tbuff, -1, 2);
std::copy_n(tvec.begin(), 2, tbuff);
printf("test case 3, vec: %d %d buff: %d %d\n", tvec[0], tvec[1], tbuff[0], tbuff[1]);
// test case 4, std::copy_n from vec pointer to buff pointer
memset(tbuff, -1, 2);
std::copy_n(&tvec[0], 2, tbuff);
printf("test case 4, vec: %d %d buff: %d %d\n", tvec[0], tvec[1], tbuff[0], tbuff[1]);
// test case 5, memcpy from vec pointer to buff pointer
memset(tbuff, -1, 2);
memcpy(tbuff, &tvec[0], 2);
printf("test case 5, vec: %d %d buff: %d %d\n", tvec[0], tvec[1], tbuff[0], tbuff[1]);
delete[] tbuff;
```
the results:
```
test case 1, vec: 0 1 buff: -1 -1
test case 2, vec: 0 1 buff: 0 1
test case 3, vec: 0 1 buff: 0 1
test case 4, vec: 0 1 buff: 0 1
test case 5, vec: 0 1 buff: 0 1
```
as you see, in "test case 1", vec values are "0 1 " but buffer values are "-1 -1", the data is broken in buffer. test case 2~5 are good ways to copy data into buffer.

**Comment by shiguowang** [comment]
@yhirose "curl httP://127.0.0.1:1234/update-packet/streamed-with-range --output a.tar.gz --max-time 120" will fix the problem, I think "--max-time 120" is the key, and my original server code is slow actually

I will close this issue if you feel ok, thank you.
