### ISSUE TITLE
How can you send raw html data?

### ISSUE THREAD

**Issue by crwn1337** [yhirose/cpp-httplib#1301]
I want to send raw data (without httplib adding headers), I need a very specific layout for an api. It seems the "Connection" header is forced no matter what [here](https://github.com/yhirose/cpp-httplib/blob/df20c27696c6dcb2b9ccecf3c4f9c3d06c1ecf8c/httplib.h#L5061=).

edit: i mistyped the title i meant raw http data, i cant edit because github doesnt allow it.

**Comment by yhirose** [comment]
@crwn1337, thanks for the feedback. I probably don't fully understand what you are talking about... Anyway, when `close_connection` member variable is `true`, the cpp-httplib server must add 'Connection: clone' to the HTTP header section for proper communication with a client.

**Comment by PixlRainbow** [comment]
You can edit the title by clicking the "edit" button on the right side of the title on the desktop web interface, or above the title on the mobile web interface.

@yhirose they are asking if it is possible to exclude all headers because they have some existing HTTP software that is incapable of parsing headers.

@crwn1337 although the HTTP standard doesn't require any headers to be included or parsed, having a HTTP client or server that is also unable to **_ignore_** existing headers is asking for trouble, as it will simply make it extremely difficult to co-exist with other software or collaborate with other developers. Minimally, your API should be capable of checking for the first occurrence of two successive `/r/n` sequences to indicate start of body, or it would not be HTTP standard compliant.
