### ISSUE TITLE
How to close an http request?

### ISSUE THREAD

**Issue by FeJQ** [yhirose/cpp-httplib#1380]
There is a very time-consuming http request (10 seconds+), I want to interrupt this request and release resources safely when the form program exits

**Comment by yhirose** [comment]
Thanks for the feedback. It depends on situations. If it's due to network slowness, there is no way manually, and only thing we can do is to set appropriate timeout values. If the payload side is an issue, then you can use the content receiver interface. You can see the information in README and a number of examples in `test/test.cc` Hope it helps!
