### ISSUE TITLE
Enable more simultaneous requests by rewriting process_and_close

### ISSUE THREAD

**Issue by timprepscius** [yhirose/cpp-httplib#1383]
Hey there,

I'm looking at your webserver.  Very impressive!

I was wondering what you think about a possible change.  Whether you think it would work, and/or whether it could be integrated at some later date if it did work.

If I understand httplib correctly, each request is bound to a single worker.
There is the process_and_close method, which is responsible for taking a socket, running the request, and then closing the socket afterwards.

I believe that it could be possible for the same number of threads to handle many more requests simultaneously using futures, or just a work queue (which could be the same work queue).

How it would work is this:

1. process_and_close would be renamed and reworked to be initiate_processing
2. initiate_processing would create a shared_ptr of a process_request object which, when destructed would close the socket.
3. the process_request object shared_ptr is sent into the function which does the handling.  The function which does the handling could either:
   a. do what it does now, and return, and since the process_request object would be destroyed thereby, it would close just as it does now.
  b.  it could retain the process_request object, and do work on it, via whatever it wants to do.

In my case I would do something like this:
 

```
void my_function(const std::shared_ptr<process_request_object> &pro)
{
   // uh oh I need to wait for something to finish, let's retain it.
   my_queue_of_things_to_do.push({
     pro,
     (returns some future)get_some_information_do_something_which_could_take_a_second(pro)
   );
}

void my_queue_of_things_to_do_processor_guy(const std::string &stuff)
{
  // somehow, something happened and we know to pop the queue
  auto pro = my_queue_of_things_to_do.pop();
  pro->write_some_stuff(stuff);

  // we are now done, so we allow the process_request_object to be destroyed
  // this would call close, etc
  pro = nullptr;
}

```

In this way, the work queue would be used to "initiate" the request.  But then also later write the response or do arbitrary work.
The number of simultaneous requests would be limited by the number of free sockets rather than free threads.

I'm not sure how clear I'm being.

It is also possible I have misunderstood your library in my rough reading.

-tim

**Comment by tugrul512bit** [comment]
You can also simply use 1000 threads to work on 1000 connections just with less efficiency due to context switching. I guess context switching overhead would only be visible when content size is too small and without any https encryption. And yes, extra threads mean extra memory requirement which is not good for a scalable server program. If there is enough I/O per thread, the context switching should be ok. Since I/O is done blocking (not asynchronous), it will be the bottleneck, at least for big contents.

**Comment by yhirose** [comment]
@timprepscius, I probably don't understand what you are trying to do, yet... Can the default thread pool support work on your situation? If not, you can override the default one with your own thread pool implementation.

https://github.com/yhirose/cpp-httplib#default-thread-pool-support
https://github.com/yhirose/cpp-httplib#override-the-default-thread-pool-with-yours

**Comment by PixlRainbow** [comment]
@timprepscius it doesn't appear obvious how you would be able to get any extra performance with your suggestion. Each request is still bound to a worker. The multiple write loops and I/O blocks still don't get split up, so requests will still block a thread.

I am guessing you are trying to add a "producer" queue such that there is a dedicated thread that listens for incoming requests and adds them to the queue to be processed by the thread pool, so that simultaneous requests simply take longer to fulfil without being dropped. But there is already a task queue (`TaskQueue` used by `ThreadPool`)

The only way you would get extra performance was if the request or response processing was rewritten in such a way that the stream read or write calls are non-blocking, and the thread would then put the request back into the queue if the read or write is not ready yet. However this would require significant rewriting of the core algorithm.

**Comment by timprepscius** [comment]
I'm trying the solve this problem:

1.  I receive a request
2. I start a process on a different computer.  This process takes X seconds.
3. I get a response from the other computer and write OK or FAIL to the original request

The time reading and writing the request is very low.
The time waiting for the request to finish is very high.

I'm looking for a way to avoid the thread pool filled by threads waiting for processes on another computer.

**Comment by PixlRainbow** [comment]
this will be highly complex, but possible:
1. set your project configuration to C++20 or newer
2. create a custom class that extends ThreadPool and override the methods to make use of C++20 Coroutines
3. in your server's request handler, use `co_await` calls to indicate "suspension points" where the thread may suspend or resume the stack if the result is not immediately available
4. your custom Worker class will then cycle through the tasks in the queue, running each one until the await statement is reached or until completion, whichever is necessary

You may want to use a library like [David-Haim/concurrencpp](https://github.com/David-Haim/concurrencpp) which provides a "worker thread executor" that handles point 4 for you

**Comment by timprepscius** [comment]
Yeah, no, that is needlessly complex.  At least for me.
If that process_and_close_socket was set up slightly differently, I could do everything in a more simple fashion.

Basically the closing of the socket needs to happen when a reference count == 0.

Anyhow.

**Comment by yhirose** [comment]
Thanks for comments. I am not planning to make any design change to the private method `process_and_close_socket` at this point. So I am closing this issue for now.

@timprepscius could you try your idea in your fork of cpp-httplib first to see if your idea can work? Then could you please send me a pull request? Thanks a lot!
