### ISSUE TITLE
Can I specify an output stream for large downloads?

### ISSUE THREAD

**Issue by spyang** [yhirose/cpp-httplib#139]
So far, I really like your library!

My use case is with the SSLClient.  The callback for displaying download progress is working.  However, I only know how to wait for the entire result first before writing to disk (by getting the body attribute from the result).  In my case, the file I may be downloading could be 1GB in size, so I'd prefer to write the result to disk as it comes in.  Is there a way to do this?

**Comment by yhirose** [comment]
@spyang, thank you for your feedback.

Sorry that there is no easy, built-in way... But if you check where `strm.read` is called, you may find a way to do it. Also you should probably remove `std::string body` from `Response` and add a callback function like `std::function<int (Stream& strm)> data_receiver` to take over the control of where the data should be stored.

Your request sounds a good idea anyway. Hope I can find a way to do it without changing the current httplib interface, so that existing users won't be affected and we can benefit from the new feature. Thanks!

**Comment by ivanenko** [comment]
Im also voting for this feature!

**Comment by yhirose** [comment]
The read handler should be`std::function<int (Stream& strm, size_t content_length)> data_receiver`.

We expect that `data_receiver` could be called in 3 different ways based on HTTP request type:
1. With content length (`content_length` should be greater than  -1)
2. Without content length ('content_length` should be -1)
3. Chunked transfer encoding (2. could be called more than once)

There is a big problem remaining still though, that is **'gzip' encoding support**. Right now, cpp-httlib inflates data after it receives entire data in `body` member. So if a user sets the `data_receiver`, it becomes now the users' responsibility to inflate data which is not an easy task...

**Comment by PixlRainbow** [comment]
I've made an implementation similar to your third suggested way in #181, and I've set it up such that gzip encoded data will be inflated chunk-by-chunk before being given to a handler.
To create a handler, for example, you could do this
```cpp
size_t write_offset = 0;
FILE *testfile = fopen("download_file", "wb");
//the callback handler
bool recvData(std::string chunk){
    usleep(1000000U);
    std::cerr << "Chunk No. " << count++ << ": " << chunk << std::endl;
    fwrite(chunk.c_str(), chunk.size(), write_offset, testfile);
    write_offset += chunk.size();
    return true;
}
```
and in your `main` code
```cpp
httplib::Client cli("somehost.com");
//path, progress callback, chunk callback
cli.Get("/HTTP/ChunkedScript", nullptr, recvData);
```
**However, this would only work for remote servers that actually support chunked downloads, and not for servers that offer a "vanilla" byte stream**

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the helpful information and pull request. I'll try to find a unified interface which can be used not only for the chunked transfer encoding, but also other situations I mentioned above. I'll do more research about it and how to accomplish it. I may need to do some refactoring before implementing this change. I'll come back to this issue when I am not busy since it doesn't seem to be a tedious task.

**Comment by PixlRainbow** [comment]
I actually based the design off existing code inside httplib for `Response.streamcb` in `Server` and by slightly modifying `detail::read_content_chunked`

**Comment by yhirose** [comment]
https://stackoverflow.com/questions/5280633/gzip-compression-of-chunked-encoding-response

**Comment by yhirose** [comment]
I have finally implemented this feature. It handles 'with content length', 'without content length' and 'chunked transfer encoding' seamlessly. Also 'gzip' encoding is fully supported when zlib is linked.

The usage is as below:

```c++
  std::string body;
  auto res = cli.Get("/large-data", [&](const char *data, size_t len) {
    body.append(data, len);
  });
  assert(res->body.empty());
```
