### ISSUE TITLE
Segmentation caused by big data

### ISSUE THREAD

**Issue by Gatsbyoo** [yhirose/cpp-httplib#1392]
First of all, thank you very much for developing this library and lightening my mental burden. 

When I'm using httplib::Client::Post, I'm requesting more than 2000 pieces of data from the server, which is a lot of data, so I get an error, and when I call it through const & to some other function (parsing JSON), I get a segment error, so I debug the core file, I found an error in the string constructor, so can someone help me?

like this:
auto x = m_client->Post(interface.c_str(), msg, "application/json");
jsonToStruct(x->body, info);

**Comment by yhirose** [comment]
@Gatsbyoo where does the segmentation fault happens, `m_client->Post` or `jsonToStruct`?

**Comment by Gatsbyoo** [comment]
It happened when I called jsonToStruct, I saw an issue before that said to add a function that can read partially, the Get function seems to have, can read data in batches, but Post does not. Is there any way to solve this?

**Comment by yhirose** [comment]
If it happens in `jsonToStruct`, I don't think it's a problem in cpp-httplib, but in `jsonToStruct`, and I can't give you any help... I'll close this issue soon for now due to the reason.

By the way, I didn't provide methods with `ContentReceiver` in `Client`, since HTTP POST is meant to 'post data' rather than to 'receive data'.
