### ISSUE TITLE
Filename downloading from endless stream

### ISSUE THREAD

**Issue by NuclearInstruments** [yhirose/cpp-httplib#1397]
Hi,
I want to thank you for your great work develeoping this very useful library

We are registering and endpoint to download on the computer of the user an endless stream and save on a file. It's waveform coming from a particle detector in binary format.
We have tree API, one to start the acquisitio, one to stop and the last to store data. I need to set a filename in the download file. Any solution is good, my first idea was to specify it in the url like this:
http://localhost:8080/mmc/Digitizer_0/dump_data/myfile.bin
where myfile.bin is the filename, but can be any, specified client side

So i imagined the possibility to have a wildchar after the path but it want work

```
 srv->Get(_path + "/dump_data/*", [&](const Request &req, Response &res) {
      res.set_content_provider(
        "text/plain", // Content type
        [&](size_t offset, DataSink &sink) {
          if (enable_dump ) {
            std::vector<char> data;
            for (int i =0;i<1000;i++) {
                data.push_back((char)i);
            }
            sink.write(data.data(), data.size());
            target_count++;
          } else {
            sink.done(); // No more data
          }
          return true; // return 'false' if you want to cancel the process.
        });
    });
```

i also tryed _path + R("/dump_data/(\s+)" but i got a 404 page not found

Do you have any idea?

Thank you
Andrea

**Comment by PixlRainbow** [comment]
im guessing based on your variable being named `srv` that you want to use httplib to host a server.
Note that the regex pattern `\s+` attempts to match at least one or more whitespace characters.
If you want a to match at least one or many of _any_ character then use `.+`

Also, note that adding `_path` to the front of your pattern means that the brackets in the string no longer properly wrap around your whole path. So if you have C++20 you may want to try:
```cpp
std::format(R"({}/dump_data/(.+))", path)
```
Otherwise old-style concatenation will work too
```cpp
"(" + _path + R"/dump_data/(.+))"
```
