### ISSUE TITLE
Documentation for Server Configuration Setters

### ISSUE THREAD

**Issue by theShmoo** [yhirose/cpp-httplib#1408]
There are some examples for configuring the cpp-httplib server, but there is no documentation what these settings actually do.

I am interested in the following settings:

* set_keep_alive_max_count
* set_keep_alive_timeout
* set_read_timeout
* set_write_timeout
* set_idle_interval

as we have issues with the keep alive messages with a client.

**Comment by yhirose** [comment]
@theShmoo, sorry that I am a lazy person for documenting. :)

* set_keep_alive_max_count
* set_keep_alive_timeout

They configure HTTP Keep-Alive behavior. With `set_keep_alive_max_count`, we can specify how many requests we can handle with one socket connection. With `set_keep_alive_timeout`, we can specify how many seconds we can wait for another HTTP request with the same keep-alive socket connection. 

You can see more information in [this MDN document](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive).

* set_read_timeout
* set_write_timeout

We can specify read/write timeout. The values will be used with `select` or `poll' system call.

* set_idle_interval

This is cpp-httplib specific concept. If a user wants to use his own `TaskQueue` instead of the default thread pool that cpp-httplib provides, you can control how often the `on_idle` method will be called by the HTTP server. It's pretty hard for me to explain it, but hope you can see how it works in the following code snippet.

https://github.com/yhirose/cpp-httplib/blob/27cd4e6ffeca2c9978ec1df7de3d22b9303a71b4/httplib.h#L5437-L5453

**Comment by theShmoo** [comment]
Thank you for your answer! 

This helps a lot!
