### ISSUE TITLE
Qusetion about receiving the request message

### ISSUE THREAD

**Issue by yanyipingpeter** [yhirose/cpp-httplib#1415]
Hello, I write a server.  when I receiving

 some long request, some times the server can receive the whole data at a time
![7% 5V96TS$1TS_{ 7@QBWQS](https://user-images.githubusercontent.com/68374297/199003828-59c3a52d-1fef-4553-9d01-79f5e92748dc.png)

however sometimes, the server the message is received participle. shown as figure below
Receiving part of  request in the first time 
![``6Q0FFM$LWJPUMAO@{OLC2](https://user-images.githubusercontent.com/68374297/199003865-02db026e-5953-4499-926e-45688cfa3610.png)

Receiving remaining part of  request in the second time 
![8TS0}S~VX A~1LNWV}D9ULQ](https://user-images.githubusercontent.com/68374297/199004181-683bdd24-6764-4634-8bf0-836ff694f675.png)

The second circumstances could cause error while parsing the json data. I'm wondering what can I to to ensure the whole data can be received at a time, just like the first circumstances?
Thank you.

**Comment by yhirose** [comment]
@yanyipingpeter, thanks for the report, but I honestly don't understand why the problem happens... Could you make sure that everything is all right on the client side? I'll close it for now and please submit an issue again when it turns out it's a really cpp-httplib problem. Thanks for your understanding!
