### ISSUE TITLE
Beginner's question

### ISSUE THREAD

**Issue by damian-tomczak** [yhirose/cpp-httplib#1497]
Hi,
Can somebody explain me, why my servers have to be run on separated threads?

Thanks in an advance.

**Comment by yhirose** [comment]
Sorry, I don't understand your question...

**Comment by PixlRainbow** [comment]
Hi, I assume you are referring to httplib server using a multithreaded model
This is because httplib is using the "blocking" socket API to handle networking, where a read or write operation on each connection will cause the thread to suspend until the connection is ready to accept more data. Thus, in the current default implementation, each connection requires a dedicated thread.
Furthermore, we do not make use of microtask technologies such as coroutines, so we cannot multiplex between multiple logical threads on one physical thread.

**Comment by damian-tomczak** [comment]
> Hi, I assume you are referring to httplib server using a multithreaded model This is because httplib is using the "blocking" socket API to handle networking, where a read or write operation on each connection will cause the thread to suspend until the connection is ready to accept more data. Thus, in the current default implementation, each connection requires a dedicated thread. Furthermore, we do not make use of microtask technologies such as coroutines, so we cannot multiplex between multiple logical workers on one physical thread.

Thank you very much <3
