### ISSUE TITLE
Use of resolv.h in this library causes issues with Eigen due to _res macro

### ISSUE THREAD

**Issue by matthews-jca** [yhirose/cpp-httplib#1508]
included at https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L182 https://github.com/lattera/glibc/blob/master/resolv/resolv.h#L165 defines a macro helper for _res which breaks external library Eigen that often uses _res for results (https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Core/products/SelfadjointMatrixMatrix.h#L349)

One of those really odd unintended errors that creates havoc with C defines. I know this is not at all unique to this library, but might be worth an undefine at the end of this library to avoid leaking

**Comment by yhirose** [comment]
@matthews-jca, I pondered over this thing. I concluded that we shouldn't do `#undef _res` in httplib.h, since `_res` is a private information in resolve.h and we shouldn't know the existence. Also the symbol may be removed or changed at any time in the future. This issue has to be handled by glib anyway.
