### ISSUE TITLE
Version Compatibility with OpenSSL version < 1.1.1

### ISSUE THREAD

**Issue by siiulan** [yhirose/cpp-httplib#1583]
I am currently using openSSL module but it's version has to be lower than 1.1.1, I found that you comment out the version conflict error message before v0.7.3, are they really compatible to use with openSSL < 1.1.1? If not, is there such a version? Thank you 😺

**Comment by yhirose** [comment]
@siiulan thanks for the question, but I cannot answer clearly. I basically trust only the latest release of cpp-httplib, and don't recommend users to use any lower versions since they may have serious security vulnerabilities. I also would like users to use OpenSSL versions which are officially supported. That's why I put the OpenSSL version check. Is there any reason to use old OpenSSL which is no longer supported? Just curious. :)

**Comment by siiulan** [comment]
Hi @yhirose, thanks for quick reply! It was only because my other lib/app are using fixed openSSL with version 1.0.2, for quickly testing http client, I am looking for a module that is compatible to this. I've tried other modules, but yours is certainly the best and easiest module. So, I came up asking this question to see whether I can use some old version.

**Comment by yhirose** [comment]
@siiulan thanks for the clarification. I'm not certain about the latest compatible version of OpenSSL 1.0.2, but if your project can be compiled, feel free to use a newer version whenever possible. As I mentioned, please keep in mind that older versions lack a number of security fixes. :)
