### ISSUE TITLE
Question: How to troubleshoot connection failed on HTTPClient side 

### ISSUE THREAD

**Issue by oakcode** [yhirose/cpp-httplib#1622]
Hi folks,

We have been using your library for some time, it is a great library and thank you for that.
Lately we have been getting a lot of complaints that the http client cannot be connected the address when application is running on some cloud environment. Destination address is also somewhere on same cloud environment. 
Do you folks have any advice on how to go about solving this problem? What we can dump from request, can we see somehow which IP address client using to connect if we provide hostname as address?

Thank you in advance!

**Comment by yhirose** [comment]
Thanks for the feedback. I have honestly no idea what's happing on our 'some cloud environment'. Can you able to see meaningful values from `host()` and `port()` method calls on a client object?

Since cpp-httplib is just a thin TCP/IP socket wrapper, you could diagnose the connection problem with a raw socket, or other HTTP client library. Sorry that I am not able to give you any helpful advice...
