### ISSUE TITLE
How to aware of connection disconnected on server side

### ISSUE THREAD

**Issue by Huweicai** [yhirose/cpp-httplib#1633]
My issue is similar to #1503, my client will send a request to server when started and keep this connection until client stopped,
 then the server has to release the related resource after connection closed, but how can server aware of this:
 
 ```c++
     svr.Post("/keep", [&](const httplib::Request &req, httplib::Response &res) {
        while (!res.connection_closed()){
            // running   
        }
        
        // release resources
    });
 ```

**Comment by yhirose** [comment]
@Huweicai thank you for the question. The answer is that you cannot check a state of a socket in a request handler since cpp-httplib server doesn't expose a created socket to us. Sorry for the inconvenience...

<img width="671" alt="image" src="https://github.com/yhirose/cpp-httplib/assets/357397/78d77cbd-17a9-4001-804a-2f0cc0616d8f">
