### ISSUE TITLE
Forward errors from underlying libraries. 

### ISSUE THREAD

**Issue by montarcannon** [yhirose/cpp-httplib#1712]
Cpp-httplib is using OpenSSL and bunch of other libraries but has very limited error messages. Most of those libraries are generating very informative errors. Isn't it possible to forward those errors to help with recognizing what's wrong?

**Comment by yhirose** [comment]
@montarcannon thanks for the feedback. At this point, I am not planning to enhance the current error handling code, since the following errors are enough and there is not necessity for my projects. If you have any idea, could you send a pull request? Thanks!

# For OpenSSL
SSLConnection,
SSLLoadingCerts,
SSLServerVerification,

# For compression libraries
Compression,
