### ISSUE TITLE
usage of rand() is not seeded and depends on seeding by parent program

### ISSUE THREAD

**Issue by braindigitalis** [yhirose/cpp-httplib#1747]
cpphttplib uses rand() in a function called `detail::random_string()` used for various security related things such as authorization headers, and the 407 CONNECT response.

Nothing in cpphttplib seeds rand() (and shouldnt) but rand is considered harmful for security sensitive calls. Considering the fact this is called for security/password related things, it should use something else instead such as `<random>` and `std::mt19937` with `std::random_device`, properly initialised, or should offer user callback to get random data for cpphttplib.

I do not think it is in anyones best interest for cpphttplib to directly srand() itself as this can break any expectations in the user program, and not doing anything is also bad as it can make the randomness predictable and not random at all.

Of the fixes proposed above, offering a user callback to obtain randomness is likely the best solution, in the short term documetation should clearly state that srand() should be called before any use of this library that involves proxy auth or normal auth!

**Comment by yhirose** [comment]
@braindigitalis thanks for the feedback. It's hard for me to understand this kind of security issue. :) Could you send a pull request that implements your proposed suggestions, so that I can fully understand what you mentions? Thanks a lot!

**Comment by braindigitalis** [comment]
I might have a go but it will be a while if I have to do it.

**Comment by sum01** [comment]
@yhirose 
> If [std::rand()](https://en.cppreference.com/w/cpp/numeric/random/rand) is used before any calls to srand(), [std::rand()](https://en.cppreference.com/w/cpp/numeric/random/rand) behaves as if it was seeded with srand(1).
>
> Each time [std::rand()](https://en.cppreference.com/w/cpp/numeric/random/rand) is seeded with the same seed, it must produce the same sequence of values.


Like @braindigitalis said, it'd be better to use the stuff from `<random>` instead. It's already being used in `make_multipart_data_boundary` anyways so it's not like the includes will change. Not to mention it's considered a better RNG source than `rand`.
> rand() is not recommended for serious random-number generation needs. It is recommended to use C++11's [random number generation](https://en.cppreference.com/w/cpp/numeric/random) facilities to replace rand().

Although to be honest, I'm simply not familiar with OpenSSL internals so I don't really know how this effects security after just skimming over `httplib.h`.

---
Anyways... A simple example of what you might do to `random_string` would be something like this
```cpp
inline std::string random_string(size_t length) {
	const std::string charset {"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"};

	// simple RNG using uniform distribution
	std::random_device rd;
	// use m19937_64 here instead if we want to bias towards 64-bit
	std::mt19937 gen(rd());
	std::uniform_int_distribution<> dist(0, charset.size() - 1);

	std::string rand_str;

	for (; length > 0; --length) {
		rand_str.push_back(charset.at(dist(gen)));
	}

	return rand_str;
}
```
Sidenote: I suppose you'd technically want to use `std::mt19937_64` if we're more biased towards 64-bit machines, as it'd have better [randomness](https://stackoverflow.com/a/22559797) and [performance](https://stackoverflow.com/a/39170215) on those machines. Not really sure what the target is for cpp-httplib, so I didn't bother...

---

Likewise, I do wonder if `make_multipart_data_boundary` couldn't just then use this revised `random_string` instead of doing what it does now. It looks to be doing mostly the same thing when it could just be this
```cpp
inline std::string make_multipart_data_boundary() {
	return "--cpp-httplib-multipart-data-" + detail::random_string(16);
}
```

---

All quotes can be found [here from cppreference](https://en.cppreference.com/w/cpp/numeric/random/rand)

**Comment by braindigitalis** [comment]
What @sum01 said but dont initialise `rd` every time you call random_string. You only want to seed once and set up the random number generator once, perhaps as a static member variable.

**Comment by sum01** [comment]
@braindigitalis I agree `random_device` should be `static` but shouldn't the generator be fine as-is? `<random>` generator's don't talk to OS API's like `random_device` does & are self-contained as far as I'm aware.

**Comment by yhirose** [comment]
> I might have a go but it will be a while if I have to do it.

@braindigitalis that's totally fine with me. So please send a pull request when you are available. Thanks a lot!

**Comment by yhirose** [comment]
@braindigitalis how long will it take for you to implement this?

**Comment by yhirose** [comment]
> @braindigitalis I agree `random_device` should be `static` but shouldn't the generator be fine as-is? `<random>` generator's don't talk to OS API's like `random_device` does & are self-contained as far as I'm aware.

@braindigitalis could you also reply to the question from @sum01?

**Comment by yhirose** [comment]
I implemented based on the idea from @sum01.
