### ISSUE TITLE
Support for systems with LibreSSL instead of OpenSSL

### ISSUE THREAD

**Issue by CyberTailor** [yhirose/cpp-httplib#1774]
LibreSSL doesn't have OpenSSL 3 APIs, making cpp-httlib unsusable on my system.

I don't think it's a good idea to support old OpenSSL 1.1 APIs, so the options are:

1. Add support for LibreSSL's `libtls` (portable version: https://git.causal.agency/libretls/about/)
2. Add support for another alternative library, such as GnuTLS
3. Provide bundled version of OpenSSL 3 and link with it statically

**Comment by yhirose** [comment]
@CyberTailor thanks for the suggestion, but I am not interested in supporting LibreSSL since I simply don't need it and don't have time to support it. Thanks for your understanding!

**Comment by CyberTailor** [comment]
That's basically forcing people on LibreSSL-enabled distros to use old and potentially vulnerable versions of `cpp-httplib` :woozy_face:

You understand that and choose to ignore the problem?

**Comment by kevinbcarpenter** [comment]
What I read is it is something he is unable to support.  I am sure you or someone else may be able to since it’s important for your use case.  I think that’s the beauty of open source projects like this.  We can always fork and add on.

Sent from my iPhone

On Feb 6, 2024, at 7:35 AM, Anna ***@***.***> wrote:

﻿

That's basically forcing people on LibreSSL-enabled distros to use old and potentially vulnerable versions of cpp-httplib 🥴

You understand that and choose to ignore the problem?
