### ISSUE TITLE
Error/Warning in Microsoft Visual Studio 2017 with WSASocketA

### ISSUE THREAD

**Issue by DJuego** [yhirose/cpp-httplib#182]
Hi! Thank you for your efforts!

Microsoft Visual Studio 2018 (Windows 10 x64) has a concern :-) :

`cpp-httplib\httplib.h(649): error C4996: 'WSASocketA': Use WSASocketW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings`

DJuego

**Comment by yhirose** [comment]
@DJuego, thanks for the build error report. It's caused by the change at #164. I'll take a look at it. Thanks!

**Comment by yhirose** [comment]
@DJuego, I changed to use WSASocketW. Hope it fixes the warning.

**Comment by DJuego** [comment]
Yes. It works! Thank you for your very quick fix! No problem in building now! Now i have to test in run-time. :-)

DJuego

**Comment by axel-habermaier** [comment]
Whether using ``WSASocketW`` or ``WSASocketA`` is correct depends on the project's Unicode compiler settings. It technically seems more correct to use ``WSASocket``, a macro which selects either ``WSASocketW`` or ``WSASocketA`` depending on the compiler settings; that's how the Win32 API works in general. You would still get the warning above (it's only an error if you compile with warning-as-errors) if you don't use Unicode, though. But forcing Unicode onto an app that otherwise doesn't use it also doesn't seem nice.
