### ISSUE TITLE
Failed to write connection

### ISSUE THREAD

**Issue by HanChinese-LIURUI** [yhirose/cpp-httplib#1924]
Hello, in actual use, httplib::Result will occasionally report this error Failed to write connection, what is the possible problem?

**Comment by yhirose** [comment]
To be honest, I don't know. The reason is that it varies depending on the individual network conditions (on the server side or the client side). What comes to mind is that either the socket on the other side was closed for some reason, or the network conditions are extremely poor.

**Comment by HanChinese-LIURUI** [comment]
Ok, thank you for your answer

**Comment by lilucpp** [comment]
I encountered a similar issue where the system returned error code 5 during network operations. This happened on Kylin Linux Desktop V10 (SP1).

In my case, the problem was caused by restrictions imposed by the Security Center - Network Protection module, which was blocking the process. After allowing the process through the security settings, the issue was resolved.

This is just for reference, but it may be worth checking whether network control policies or firewalls are blocking the process or the port being used.

**Comment by HanChinese-LIURUI** [comment]
发自我的iPhone
My situation is caused by the server disconnecting.

------------------ Original ------------------
From: lilucpp ***@***.***&gt;
Date: Fri,Jul 4,2025 4:20 PM
To: yhirose/cpp-httplib ***@***.***&gt;
Cc: 刘锐 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [yhirose/cpp-httplib] Failed to write connection (Issue #1924)



lilucpp left a comment (yhirose/cpp-httplib#1924)
 
I encountered a similar issue where the system returned error code 5 during network operations. This happened on Kylin Linux Desktop V10 (SP1).
 
In my case, the problem was caused by restrictions imposed by the Security Center - Network Protection module, which was blocking the process. After allowing the process through the security settings, the issue was resolved.
 
This is just for reference, but it may be worth checking whether network control policies or firewalls are blocking the process or the port being used.
