### ISSUE TITLE
Is Sink.is_writable() thread-safe

### ISSUE THREAD

**Issue by ochafik** [yhirose/cpp-httplib#1952]
Hi, I see a [fair bit](https://github.com/search?q=repo%3Ayhirose%2Fcpp-httplib+thread+safe&type=issues&p=2) of work has been done to make httplib threadsafe, wondering if that extends to Sink.is_writable()?

Context: trying to detect closed connections (in a set_content_provider setup) from another thread [in llama.cpp](https://github.com/ggerganov/llama.cpp/pull/9679#pullrequestreview-2339961217). Our writes are still happening only on the http thread, but knowing when to cancel the processing would be amazing.

**Comment by yhirose** [comment]
@ochafik thanks for the interesting question. 

According to the following article, POSIX socket operations like send/recv are atomic.
https://stackoverflow.com/questions/1981372/are-parallel-calls-to-send-recv-on-the-same-socket-valid

`is_writable` method consists of the subsequent `select_write` and `is_socket_alive` calls.
https://github.com/yhirose/cpp-httplib/blob/10d68cff5081d8c7b7cae74000e0c423107dc7b8/httplib.h#L5819-L5822


`select_write` doesn't write, but checks the write status of the socket with `poll` or `select`. I don't know they are atomic, but I think they are because of consistency with other socket system calls.
https://github.com/yhirose/cpp-httplib/blob/10d68cff5081d8c7b7cae74000e0c423107dc7b8/httplib.h#L3104-L3130

`is_socket_alive` ends up calling `recv` eventually, but it's an atomic call as mentioned in the above stackoverflow post.
https://github.com/yhirose/cpp-httplib/blob/10d68cff5081d8c7b7cae74000e0c423107dc7b8/httplib.h#L3189-L3198

So it seems like it's ok to call `is_writable` in different threads, but I am not 100% sure according to my limited knowledge.
Also WinSock2 on Windows may behave differently than Linux or macOS.

Did you find any actual problem in your project? If so I may be able to try to reproduce it on my machine.
Anyway, sorry that I am not able to give you a concrete answer, but hope my answer give you something helpful.

**Comment by ochafik** [comment]
@yhirose thank you so much for the detailed research and prompt reply! 

No actual problem but the question was raised by @ngxson in a [code review](https://github.com/ggerganov/llama.cpp/pull/9679#pullrequestreview-2339961217), hoping to avoid running into problems if that PR gets merged :-D

**Comment by ngxson** [comment]
Hmm in this case, if only taking into account POSIX (linux, bsd), then `is_writable()` is an atomic operation and should block until the last operation is finished.

For llama.cpp, this can have negative impact on inference if there're `select_write` being called multiple times from other threads (so one call has to wait for the other to finish). What I'm wondering is: can we only use `select_read` to determine if the connection is still alive. It seems to me that `select_read` will not compromise on performance, since it's never be used after HTTP request being processed.

**Comment by ochafik** [comment]
> What I'm wondering is: can we only use select_read to determine if the connection is still alive.

select_read alone didn't seem to cut it but is_socket_alive (= select_read + read_socket) seems to work -> https://github.com/yhirose/cpp-httplib/pull/1956

> Also WinSock2 on Windows may behave differently than Linux or macOS.

It looks like winsock should be [reasonably threadsafe](https://tangentsoft.com/wskfaq/intermediate.html#:~:text=3.10%20%2D%20Is%20Winsock%20thread%2Dsafe,()%20on%20a%20single%20socket.), with just undefined ordering behaviour for concurrent writes (not our case). [MSDN](https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-recv) doesn't spell much out though.
