### ISSUE TITLE
GET request failure against https server

### ISSUE THREAD

**Issue by ahojnnes** [yhirose/cpp-httplib#2004]
Using the vcpkg port `cpp-httplib[openssl]` (with openssl support), the following example crashes under Windows with an "Exception thrown at ... (libssl-3-arm64.dll)". The same error happens for version 0.18.0 and the 0.18.3 (see https://github.com/microsoft/vcpkg/pull/42663). The example passes without an issue on Mac/Linux.
```
std::string Download(const std::string& host, const std::string& path) {
  httplib::Client client(host);
  client.set_follow_location(true);
  httplib::Result result = client.Get(path);
  // ... skip error handling
  return result->body;
}

int main() {
  Download("http://eu.httpbin.org", "/"); // succeeds
  Download("https://google.com", "/");  // crashes
}
```

More detailed stacktrace in Visual Studio debugger:
![image](https://github.com/user-attachments/assets/c8795b15-6cbc-4fdf-873d-cc8083da0d14)

**Comment by yhirose** [comment]
@ahojnnes thanks for your report. However, I am not able to reproduce the problem on my Windows machine and on GitHub Actions workflow.

https://github.com/yhirose/cpp-httplib/commit/e6d71bd702d4ec224940c2c34e3d0b55c06eeb8b
https://github.com/yhirose/cpp-httplib/actions/runs/12306437291/job/34348151195

So it seems like the way to integrate OpenSSL into cpp-httplib in the vcpkg version causes the issue.

To be honest, I don't know anything about the port, since I am not managing it. So could you contact the person who manages the vcpkg port? Thanks!

**Comment by ahojnnes** [comment]
Thank you. The vcpkg port doesn't really do anything other than building openssl and linking against it. Since the crash happens in openssl, I am wondering whether the issue is either caused by it directly or changed underlying behavior vs. the version of openssl you are testing against. Which version of openssl did you use to replicate?

**Comment by yhirose** [comment]
3.4.0 installed by Chocolatey.
