### ISSUE TITLE
sse: set_chunked_content_provider: backend works slower when reload page

### ISSUE THREAD

**Issue by sitesv** [yhirose/cpp-httplib#2008]
Hello!
I'm faced with one thing while using sse.
Server app works slower and slower each time when reload page...
Should I do something in case of new connection (reload page) to server ('set_chunked_content_provider' executes again)?

If I remove my subscription to event, everything will work fine...
Any advise?

Thank you!

**Comment by yhirose** [comment]
Since I don't know your environment exactly, I am not able to answer your question correctly. Sorry about that.
But, one possibility is that the server receives too simultaneous requests. In this case, cpp-httplib isn't a good choice, since it is a multi-threaded HTTP server. It is better for you to find another HTTP server library which supports non-blocking I/O.
Hope it helps!

**Comment by sitesv** [comment]
> Since I don't know your environment exactly, I am not able to answer your question correctly. Sorry about that. But, one possibility is that the server receives too simultaneous requests. In this case, cpp-httplib isn't a good choice, since it is a multi-threaded HTTP server. It is better for you to find another HTTP server library which supports non-blocking I/O. Hope it helps!

I have only one page in the browser. I reload it by F5. So, the case with a lot requests are excluded. I use code based on yours ssesvr example.

**Comment by sitesv** [comment]
In your example event sends periodically alltime. But in my case I send event only in some conditions...
In this case httplib works not well... ((

**Comment by sitesv** [comment]
@yhirose could you please advice me how to fix this issue?
