### ISSUE TITLE
Connection refused if localhost

### ISSUE THREAD

**Issue by andre237** [yhirose/cpp-httplib#216]
I have the server running on a Raspberry PI. If I start the server passing the actual IP, it works just fine. However, if I pass "localhost", like this: `server.listen("localhost", 4444);` and then try to request something, it says connection refused. Is this regarding to the library or something on my network or raspberry that I am forgetting?

**Comment by yhirose** [comment]
@andre237, thanks for the question. If you are connecting to the server from another machine, this it the expected behavior. If you send a request from the same Raspberry PI but the server doesn't respond to it, please give me more details. The following stackoverflow post could be helpful. Thanks!

https://stackoverflow.com/questions/19482164/how-can-i-access-localhost-from-another-computer-in-the-same-network

**Comment by andre237** [comment]
Requesting from the same raspberry is OK, but I need to access it from other machines. I already know this raspberry IP address, it is 25. So I tried using  `curl http://192.168.0.25:4444/api` and it keeps returning connection refused. What intrigues me the most is that if I start the server like this: `server.listen("192.168.0.25", 4444);` I can access it from the outside without any problems. My guess it is something with the network but I'm not sure

**Comment by yhirose** [comment]
`localhost` is a loopback address which usually represents `127.0.0.1`, and it's not exposed to outside.
https://whatismyipaddress.com/localhost

Hope it helps as well:
https://stackoverflow.com/questions/5524116/accessing-localhost-xampp-from-another-computer-over-lan-network-how-to#answer-5524127

**Comment by andre237** [comment]
Yeah, I was misunderstanding those concepts, my bad. Thanks for your help
