### ISSUE TITLE
Async notification to client

### ISSUE THREAD

**Issue by elli-one** [yhirose/cpp-httplib#233]
Maybe not possible? Any chance to implement async notification to client without polling
from client otherwise I must go to to raw socket again.

**Comment by yhirose** [comment]
@elli-one, are you talking about sending event messages to clients with this HTTP server library? If so, it's not easy to do it. You may be able to use SSE (Server-Sent Events technique, but I would rather recommend you to find websocket libraries instead of using this library. Please see #45 to see more information for SSE. Thank you for asking!

**Comment by PixlRainbow** [comment]
It easy to create an SSE implementation from the server side, but at the moment, not possible to do so from the client side
