### ISSUE TITLE
Support for Content-type "Application/gzip"

### ISSUE THREAD

**Issue by sharatk** [yhirose/cpp-httplib#255]
First of all thanks for this wonderful library!. I have a requirement for the server to receive a tar.gz file via a PUT and also to send a tar.gz file in response to a GET.  The server does not have to compress or decompress. The application is responsible for tarring and untaring the tar.gz files.  Is there any support for this ? I don't see the content-type "Application/gzip" listed anywhere in the documentation or the code.
Thank you
Shaks

**Comment by yhirose** [comment]
@sharatk, thanks for the question. cpp-httplib doesn't do any special treatment except for `application/x-www-form-urlencoded` and `multipart/form-data` content types.

Since tar.gz files are just binary files, you don't have to do any thing special when handling tar.gz files with cpp-httplib. (a tar.gz file is not different from a jpeg file at all from the cpp-httplib standpoint.)

Hope the explanation helps!

**Comment by sharatk** [comment]
Thank you! Appreciate much!!
