### ISSUE TITLE
extra data present in body

### ISSUE THREAD

**Issue by cryguy** [yhirose/cpp-httplib#26]
when writing the response body to a file, i found that it contained extra unwanted data.  I was trying to make it get a file from a api, the data is in base64 and it appends value before the expected data

![image](https://user-images.githubusercontent.com/26816658/33362192-342c265e-d516-11e7-8c72-79eca292ed3a.png)

the expected result =

![image](https://user-images.githubusercontent.com/26816658/33362220-480abf50-d516-11e7-8474-11ce703b22e4.png)

Any help would be appreciated

used code -
```
httplib::SSLClient client("example.com", 443);
auto logincheck = "/load?username=" + user + "&product=" + product;
const char* chr = _strdup(logincheck.c_str());
auto res = client.get(chr);
if (res && res->status == 200)
encoded << res->body;
```

sorry for the bad code format

edit : found that it might be caused by it displaying chunks as the server is sending it with "Transfer-Encoding: chunked"

**Comment by yhirose** [comment]
@cryguy, thanks for the report. Yes, this is caused by the server sending the body data with '[HTTP/1.1 Chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding

`httplib::SSLClient` sends a HTTP request with 'HTTP/1.0". ([code](https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L748))
But it seems like the server doesn't respect the HTTP version of the client request and send the chunked data.

If 'ignoring HTTP version' is a common behavior of popular HTTP server such as Apache or nginx. I am thinking to support the HTTP/1.1 Chunked transfer encodingin httplib::SSLClient and httplib::Client when I have time.

Thanks!
