### ISSUE TITLE
Motivation and Roadmap

### ISSUE THREAD

**Issue by drocdotCode** [yhirose/cpp-httplib#261]
Could the author provide a brief history, motivation, and intention for the library for the short term and possibly long term plans moving forward?

**Comment by PixlRainbow** [comment]
I can't find where it's written anymore, but I believe I remember that this library was originally written to provide an interface very similar to Express.js in C++

**Comment by yhirose** [comment]
Yes, I needed a cross platform HTTP server that has simple interface like Express.js and Sinatra. Also I kept it in mind that it can be very easily embedded in other applications. That's why I made is as a single-file header-only library.

Since this is just my personal project that I can work on in my spare time, I don't have any short term and long term plans. But you can see some github issues labeled with 'enhancement' that I might support in the future when I am not busy. When serious bugs are reported, I'll try to work on them as soon as possible, of course. :)
