### ISSUE TITLE
Any plan to support basic/digest proxy and CONNECT support?

### ISSUE THREAD

**Issue by WanpengQian** [yhirose/cpp-httplib#262]
Currently the code is not support basic/digest proxy support.
also proxy via CONNECT method.

Any plan to implement them?
thanks.

**Comment by yhirose** [comment]
@WanpengQian, thanks for the feature request. Are you talking about the feature on client?

**Comment by PixlRainbow** [comment]
I looked over the specification for HTTP CONNECT, and basic/digest authentication. As far as I can tell, they are implementable by downstream developers without needing to make any changes to the code base.

**Comment by WanpengQian** [comment]
@yhirose yes. I am talking about Client side.  
@PixlRainbow yes. your investigation is correct. ```cpp-httplib``` should implement a HTTP CONNECT method, and then keep that connection open. after that, a new Client(HTTP/HTTPS) will using that connection to access HTTP/HTTPS contents.  
I have already implement above code and it works. I just don't know my idear is correct or not. otherwise I will make a pull-request.

**Comment by yhirose** [comment]
@WanpengQian and @PixlRainbow, thank you for the investigation!

According to my understanding, if you send a **HTTP** message via proxy, you can do it with the current cpp-httplib. What you need to do is to just add a 'Proxy-Authorization' header to your request structure. (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authorization)

When it comes to sending a **HTTPS** message via proxy, cpp-httplib needs to keep the connection alive after sending a CONNECTION request as you mentioned. This page explains very well how curl deals with HTTPS proxy connections (https://ec.haxx.se/usingcurl-proxies.html#https-and-proxy). According to it, we can send a HTTPS message via proxy in one shot as below:
```
curl -x proxy.example.com:80 https://example.com/
```
It means that this curl command actually sends two requests, CONNECT request first, then GET request with the same TCP connection. I could probably do the same, so that users don't need to send a CONNECT message by themselves, but cpp-httlib could handle it for users secretly. Since I have recently added the keep-alive capability on client side, it may not be too difficult to implement.

**Comment by WanpengQian** [comment]
@yhirose yes. you are correct.  
HTTP Proxy has two types, one is via basic/digest, currently cpp-httplib only has basic auth, and lack of digest auth support,  you can check [rfc2617](https://tools.ietf.org/html/rfc2617) for detail.
for basic, as you said, it is simple, just add auth info to HTTP headers. and for digest, you have to parse the response header and caculate the correct response value.

since Basic/Digest have to know the HTTP header, for HTTPS, proxy didn't have the key to parse the HTTP header, that bring the CONNECT method. actually, CONNECT proxy can support many TCP protocols other than HTTP/HTTPS.

I am expecting the implement. thanks!

**Comment by yhirose** [comment]
I am now planning to separate this issue into two, one is 'digest authentication support on client', the other one is 'CONNECT method support on client'.

**Comment by yhirose** [comment]
Closed by #266 and #267.
