### ISSUE TITLE
'inet_pton': identifier not found

### ISSUE THREAD

**Issue by ParticleG** [yhirose/cpp-httplib#269]
I'm currently write project with Visual Studio 2019, vcpkg and CMake. But when I tried to compile the program, it gave me an error: 
E:\quin_plugin\src\httplib.h(3625,7): error C3861: “inet_pton”: identifier not found[E:\quin_plugin\build\Release\app.vcxproj]
I'm on Windows 10 with Win10 SDK installed.
Don't know why this happened.

**Comment by PixlRainbow** [comment]
[Have you linked ws2_32.lib or dll?](https://social.msdn.microsoft.com/Forums/vstudio/en-US/cfefa4a5-1f1a-4987-8bc7-f3197cb5826c/how-to-link-ws232lib?forum=vcgeneral)

**Comment by yhirose** [comment]
@ParticleG, `inet_pton` is declared in `ws2tcpip.h`.
https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-inet_pton

 `ws2tcpip.h` is included at the following line in httplib.h:
https://github.com/yhirose/cpp-httplib/blob/d8da740597e3ab400f2939864fbed1255a048f1d/httplib.h#L94

The file inclusion takes place under `ifdef _WIN32`:
https://github.com/yhirose/cpp-httplib/blob/d8da740597e3ab400f2939864fbed1255a048f1d/httplib.h#L59

I have been using cpp-httplib in VS 2019 projects with no problem at all. So your project environment (vcpkg and CMake) seems to be causing the problem. Could you check your project carefully?

**Comment by yhirose** [comment]
@ParticleG, please let me know when you find the real cause of the problem. Thanks for your help!

**Comment by JavierPAYTEF** [comment]
I'm sorry if I'm bringing an old issue, but just wanted to leave my two cents in case anyone ever has the same problem.

The file ws2tcpip.h only includes the function if a certain condition with NTDDI_VERSION is met.
In my case I was redefining NTDDI_VERSION to an incorrect value and that's why it wasn't working.
I've also read that including windows.h without the WIN32_LEAN_AND_MEAN might cause issues.

This is the portion of the file that checks the condition:
![image](https://user-images.githubusercontent.com/40425968/140268209-e6370a05-c024-4fa3-bf37-3242a18c48da.png)

**Comment by jphz** [comment]
vistual studio 2022 add -D_WIN32_WINNT=0x0601 or -D_WIN32_WINNT=0x0A00
