### ISSUE TITLE
Serving static files from several folders

### ISSUE THREAD

**Issue by javValverde** [yhirose/cpp-httplib#276]
For serving static files, the following is used:
`svr.set_base_dir("./folder1");`

If I have `folder2` from which I also want to serve files, is it possible?

I found [this example](https://stackoverflow.com/a/12648349) using express.js, and it is exactly what I want to do

**Comment by yhirose** [comment]
@javValverde, thanks for the feedback! It's not possible with the current httplib.h. Please see the following code:

https://github.com/yhirose/cpp-httplib/blob/6f58dc728f6f30df6c5b17c8f2cbdb887ff41077/httplib.h#L573

I could change `std::string base_dir_` to be an array like `std::vector<std::string> base_dirs_`. so that you could do the following:

```cpp
svr.set_base_dir("./folder1");
svr.set_base_dir("./folder2");
```

But, the above behavior may confuse users, because they may expect that the second call will change the base directory instead of adding it. I'll ponder over better API to accomplish this feature.

Just for your information: I checked the stackoverflow post. They can mount a directory to whatever path like '/public', but unfortunately `svr.set_base_dir` always mounts a directory to the root path '/'.

**Comment by PixlRainbow** [comment]
perhaps have two parameters, the first parameter being path to folder, and the second being the mounted path? The second parameter would be optional and default to "/". If the same mounted path is used again, it will replace. This could be implemented using `std::unordered_map<std::string, std::string>`

**Comment by javValverde** [comment]
Thank you guys for the quick answer.

I think what @PixlRainbow suggests is really neat. It would support my usecase and wouldn't break the existing API. In my opinion adding an extra function is not neccessary

**Comment by yhirose** [comment]
I added the 'mounting point' parameter to `set_base_dir`. The default value is "/".

So we now can do like this:

```cpp
svr.set_base_dir("./folder1", "aaa");
svr.set_base_dir("./folder2", "bbb");
```

If we set a mounting point to more than one directories, cpp-httplib will try to find the specified file in the directories in the registered older. If you do the following, all three directories are mapped to the `public`, and cpp-httplib will try to look `./folder1` first.

```cpp
svr.set_base_dir("./folder1", "public");
svr.set_base_dir("./folder2", "public");
svr.set_base_dir("./folder3", "public");
```
This behavior is exactly same as express.js. So I understand the method name is now a bit confusing, but I think it's acceptable.

Thanks for the feature request!
