### ISSUE TITLE
clang++-8 can't compile with -static 

### ISSUE THREAD

**Issue by zoruamonster** [yhirose/cpp-httplib#301]
1>**/usr/bin/ld : error : /mnt/c/Users/username1/Downloads/crash291fix/obj/x86/Release/libcrash291.o: in function `int httplib::detail::create_socket<httplib::detail::create_client_socket(char const*, int, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda(int, addrinfo&)%1}>(char const*, int, httplib::detail::create_client_socket(char const*, int, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda(int, addrinfo&)%1}, int)':
1>**

Visual Studio 2019 linux c++ project 
compiler "clang for WSL"

[error_clang_static_m32.zip](https://github.com/yhirose/cpp-httplib/files/3993571/error_clang_static_m32.zip)

**Comment by yhirose** [comment]
@zoruamonster, thanks for the report. Could you look into it more to find a real cause of it? If you can make a pull request, it would be the best. :) I wish I could reproduce it, but I don't have my personal Windows box...

**Comment by PixlRainbow** [comment]
You did not quote the full error message. That is only part of the stack trace.

**Comment by zoruamonster** [comment]
> You did not quote the full error message. That is only part of the stack trace.
@PixlRainbow but no errors before, this is one error

@yhirose on linux this compiled without errors with clang++-8 with -m32 and -static? I don't have linux)) only Windows))

**Comment by PixlRainbow** [comment]
The error you have shown says "in function: <function signature>:"  
The colon at the end indicates that the error message continues on another line.

**Comment by yhirose** [comment]
I did some research about this issue regarding `-static` option. It seems it is a known issue.

https://stackoverflow.com/questions/2725255/create-statically-linked-binary-that-uses-getaddrinfo
https://stackoverflow.com/questions/2725255/create-statically-linked-binary-that-uses-getaddrinfo/37245653#37245653
https://sourceware.org/glibc/wiki/FAQ#Even_statically_linked_programs_need_some_shared_libraries_which_is_not_acceptable_for_me.__What_can_I_do.3F

If you need more info, you can easily google it with 'Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking'.

In order to fix the linker warning, you have to build your own version of glibc with `--enable-static-nss` and link it to your executable. Unfortunately, there is no way to fix this problem on cpp-httplib side. So I am thinking to close it. Sorry about that.

**Comment by zoruamonster** [comment]
@yhirose clang: error: unsupported option '--enable-static-nss'

**Comment by zoruamonster** [comment]
@yhirose no alternatives for getaddrinfo outside of glibc ? or this can't fix static compile ?

**Comment by yhirose** [comment]
@zoruamonster, the following article is only information that I found regarding it.
https://stackoverflow.com/questions/2725255/create-statically-linked-binary-that-uses-getaddrinfo#answer-37245653

**Comment by zoruamonster** [comment]
> @zoruamonster, the following article is only information that I found regarding it.
> https://stackoverflow.com/questions/2725255/create-statically-linked-binary-that-uses-getaddrinfo#answer-37245653

@yhirose but i need support c++ and 32bit linux


https://github.com/Wangzg123/DnsParse this can't replace getaddrinfo ?
