### ISSUE TITLE
How to compile the project, please specify in the documentation

### ISSUE THREAD

**Issue by tianxingqian** [yhirose/cpp-httplib#320]
How to compile the project, please specify in the documentation。

**Comment by PixlRainbow** [comment]
if you are using g++/gcc on Linux,
```sh
g++ yourfiles.cpp -o yourProgramName -pthread
```
if you are using compression, also add `-lz`, make sure `zlib1g-dev` is installed  
if you are using secure networking, also add `-lcrypto -lssl`, make sure OpenSSL is installed  

If you are using Visual Studio on Windows, the process is much more difficult, as you will have to manually indicate the include paths and dll paths in your project settings for each dependency. Make sure threads library is linked.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the excellent explanation!

**Comment by yhirose** [comment]
@tianxingqian, as you can see the above comment from @PixlRainbow, it depends on what compiler operating system (and OS distribution), and build environment that you are using. Since it's just a single file header-only library, I guess it's not too hard to integrate it into whatever situation without any documentation. But I'll think about it in the future. Hope @PixlRainbow, comment helps for now!

**Comment by tianxingqian** [comment]
Unfortunately, in the Windows environment, VisualStudio is used. Try to compile first, and then ask for help if there is a problem. Thank you all.
