### ISSUE TITLE
Is there encodeURIComponent equivalent?

### ISSUE THREAD

**Issue by yay** [yhirose/cpp-httplib#323]
If not, please consider adding:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

I only managed to find the `encode_url` method.

**Comment by yhirose** [comment]
@yay, I feel that it's not a cpp-httplib responsibility to provide such a function. That's why I keep `encode_url` as a **private** function under `detail` namespace in `httplib.h`. So for now, I am not planning to provide such escape functions, and suggest users to make their own functions which satisfy their exact needs. But thanks for your suggestion anyway that gave me an opportunity to think about this matter deeply.

By the way, I did some research on the curl repo, and found that it provides [curl_easy_escape](https://curl.haxx.se/libcurl/c/curl_easy_escape.html) API. But it is not compatible with JavaScript encodeURIComponent or encodeURI either. You can verify the behavior with [this code](https://github.com/curl/curl/blob/2e496108534ed20c82cf96f77443e81605f78f92/lib/escape.c#L44-L65).

**Comment by yay** [comment]
Thank for you for considering this and suggesting alternatives!
