### ISSUE TITLE
curl multipart form data with (File + key-param) value shows as file only

### ISSUE THREAD

**Issue by prabindh** [yhirose/cpp-httplib#343]
When sending multipart form data as below from the client:

`curl -X POST -F "key=value" -F "file=@image.png" myURL`

The request is received in the  POST handler, as 2 files --> key and file. It is expected that `key` will be a param instead.  Is this a bug, or should the `key` be indeed read as a file and parsed on the server to get the `value` field ? 

Other info:
In the POST handler, req.has_param("key") returns empty.
In the POST handler, `file` field is correctly received

**Comment by PixlRainbow** [comment]
I think `req.has_param` refers to url encoded POST requests only, and thus does not have an effect on multipart requests. Thus, `key` does not show up as a param either, as multipart requests do not encode values in the format of query parameters.  
According to the [multipart specification](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4), there is no difference between text input and file input other than the fact that text inputs don't declare a file type or filename.

**Comment by prabindh** [comment]
This seems to be a difference in expected behaviour, because other (server side) handlers do treat content-disposition with "filename" differently from other content-disposition parts. Ex,  https://stackoverflow.com/questions/8616010/multipart-message-and-post-parameters-on-server-side
I managed to read my input as file, but wouldnt it be convenient to have similar behaviour as other frameworks ?

**Comment by yhirose** [comment]
@prabindh and @PixlRainbow, thanks for the information. I now understand how PHP treats the text type multipart/form data with `$_POST`. Also despite a bit inconvenient, it seems clearer to me to keep both text and file type items in the same `struct MultipartFormData` as it does right now,  because they are from the same place. Including the text type items in `params` member in `struct Request` is actually pretty easy, but I don't have a full confidence if I should do it,  because cpp-httplib is not a Web framework like PHP or rails, but more like a primitive http library. I'll ponder over it more, then decide what to do. Anyway, thanks for bringing this thing up.

**Comment by prabindh** [comment]
@yhirose Thanks,

**Comment by prabindh** [comment]
Since I have a working solution at hand, closing this.
