### ISSUE TITLE
Bug found

### ISSUE THREAD

**Issue by danipellex** [yhirose/cpp-httplib#345]
The line

              detail::select_read(sock, CPPHTTPLIB_KEEPALIVE_TIMEOUT_SECOND, CPPHTTPLIB_KEEPALIVE_TIMEOUT_USECOND) > 0)) {

in method:

namespace detail {
    template <typename U, typename V, typename T>
    inline bool process_and_close_socket_ssl(

should be 

detail::select_read(sock, read_timeout_sec, read_timeout_usec) > 0)) {

**Comment by yhirose** [comment]
@danipellex, thank you for the report, but this is intentional and correct. `CPPHTTPLIB_KEEPALIVE_TIMEOUT_SECOND ` and `CPPHTTPLIB_KEEPALIVE_TIMEOUT_USECOND ` are used for checking 'keepalive timeout' instead of 'read timeout'. For checking 'read timeout', cpp-htpplib uses `CPPHTTPLIB_READ_TIMEOUT_SECOND` and `CPPHTTPLIB_READ_TIMEOUT_USECOND` as default values. Hope it helps.

**Comment by danipellex** [comment]
Ohhh, yes, I misread the code. I am sorry, and thank you very much.
