### ISSUE TITLE
[INFORMATION] Download files from the web.

### ISSUE THREAD

**Issue by Moltivie** [yhirose/cpp-httplib#348]
Hello community,

I going to start by saying that this is not an issue but just an information I would like to know.

Does the [GET with Content Receiver (Client)](https://github.com/yhirose/cpp-httplib#get-with-content-receiver) is meant also to be used to download files? 

Thanks.

**Comment by yhirose** [comment]
It can be used for various purposes actually, not only for downloading a file, but also receiving chunked stream. Hope it helps.

**Comment by Moltivie** [comment]
Could you link me a snippet code showing how you would download files/chunks?

**Comment by yhirose** [comment]
README and some unit test cases are only information that I have. Sorry about that...

**Comment by PixlRainbow** [comment]
@Moltivie you can use content receiver, but you can also just use `Get`. There is no difference other than the fact that one is streamed and the other downloads the entire file into memory first.

**Comment by Moltivie** [comment]
I managed to work it out. Thanks @PixlRainbow

**Comment by Fohlen** [comment]
Could you provide an example of how file downloads would look with `httplib`?

**Comment by PixlRainbow** [comment]
@Fohlen the simplest way would be to [just do a basic GET operation](https://github.com/yhirose/cpp-httplib/blob/master/README.md#client-example) but instead of printing the response body you write the contents of body directly to a new file.  
Note that this is not recommended for large files because this method will try to download everything to RAM first.
