### ISSUE TITLE
Discussion: simpler API entry point to get a URL?

### ISSUE THREAD

**Issue by samhocevar** [yhirose/cpp-httplib#357]
There is currently no simple way to download a URL; one has to use the scheme in order to decide which client to create (`Client` or `SSLClient`), then use the host and port to decide where to connect (`Client::Client()` arguments), and finally the path in order to decide what to get (`Get()` argument).

At the same time, most of that logic is already present in `Client::redirect()` which has a regex that parses the location URL to deduce the scheme, host and path. Here is a trivial proof of concept that can be added to `Client`:

    std::shared_ptr<Response> Client::GetUrl(const char *url)
    {
      auto req = Request();
      req.method = "GET";
      req.redirect_count = 1;

      auto res = std::make_shared<Response>();
      res->set_header("location", url);
      redirect(req, *res);
      return res;
    }

Test with `auto res = Client("").GetUrl("https://github.com/yhirose/cpp-httplib");`.

Do you think such a `GetUrl` method (not designed as a hack around `redirect()`, of course) would make sense?

**Comment by PixlRainbow** [comment]
Protocol support (http vs https) is currently implemented in seperate classes to account for the fact that not everyone may need or want to link the openssl libraries.

**Comment by samhocevar** [comment]
I’m well aware of that fact (yet `SSLClient` will create a `Client` when redirected to an HTTP URL, and conversely if available). Does it mean there is a problem with my suggestion?

**Comment by yhirose** [comment]
@PixlRainbow, that's exactly what I intended.

@samhocevar, I have been thinking of providing such convenient functions taking URL for long time, since I saw some users made mistakes due to the fact. (#189, #202, #236...) I haven't done it so far, because I simply didn't have time to maintain 2 sets of APIs ('Get/Post/Put...' and 'GetUrl/PostUrl/PutUrl...'). Also if we want to send a number of requests to the same host, the 'convenient functions' are not efficient, because we need to create a Client object each time. Also this library is not like 'curl', but I made it a more primitive HTTP server/client library.

When it comes to your suggestion, unfortunately it doesn't work properly in some cases due to the poor URL parser implementation in the redirect method. The parser doesn't parse 'port' number. So it cannot handle 'http://localhost:1234/hi'. Also it's not enough at all to provide just `GetUrl(const char *url)`., rather we have to provide all of methods that Client class has. Otherwise, users will start complaining about it soon. Of course the new functions should be well tested as we do for the Client and SSClient.

But I understand some benefit of it, but I am not 100% sure that it's worth putting the efforts because I was able to go without it. Of course I would like to make everyone happy, but my time is limited also. :)

Anyway, I'll ponder over it. Thanks!

**Comment by TheMaverickProgrammer** [comment]
@yhirose per providing all the methods that Client class has...

It could be circumvented by having a special GET routine: `httplib::GetSimpleUrl(const char*)`. The "Simple" in the name implies is carries no special parsing nor requires settings from a client object.

**Comment by yhirose** [comment]
Just an idea...

```cpp
TEST(YahooRedirectTest, Redirect) {
  httplib::Client cli("yahoo.com");

  auto res = cli.Get("/");
  ASSERT_TRUE(res != nullptr);
  EXPECT_EQ(301, res->status);

  cli.set_follow_location(true);
  res = cli.Get("/");
  ASSERT_TRUE(res != nullptr);
  EXPECT_EQ(200, res->status);
}

TEST(YahooRedirectTestWithURL, Redirect) {
  auto res = httplib::url::request("http://yahoo.com");
  ASSERT_TRUE(res != nullptr);
  EXPECT_EQ(301, res->status);

  res = httplib::url::request("http://yahoo.com", {
    { httplib::url::option::follow_location, true },
  });
  ASSERT_TRUE(res != nullptr);
  EXPECT_EQ(200, res->status);
}
```

**Comment by yhirose** [comment]
My first attempt for the simple API.

```cpp
httplib::url::Options options;
options.follow_location = true;

auto res = httplib::url::Get(
    "https://httpbin.org/redirect-to?url=http%3A%2F%2Fwww.google.com&status_code=302",
    options);
```

**Comment by yhirose** [comment]
The previous one has been removed. The new version is here:

```cpp
httplib::Client2 cli("https://httpbin.org");
cli.set_follow_location(true);
auto res = cli.Get("/redirect-to?url=http%3A%2F%2Fwww.google.com&status_code=302");
```

**Comment by yhirose** [comment]
Please don't use the above in production, because it's just an experimental solution and subject to change.

**Comment by samhocevar** [comment]
Not sure if it fits with your vision, but if you make it so that `set_follow_location` returns `*this` the user can also use a more fire-and-forget approach:

```cpp
auto res = httplib::Client2("https://httpbin.org")
           .set_follow_location(true)
           ... /* other options maybe */
           .get("/redirect-to?url=http%3A%2F%2Fwww.google.com&status_code=302");
```

**Comment by yhirose** [comment]
@TheMaverickProgrammer, I implemented it.

**Comment by samhocevar** [comment]
I think you @’d the wrong person, but yes, I think it’s a very convenient API :-)

**Comment by yhirose** [comment]
@samhocevar, sorry about that...
