### ISSUE TITLE
Unicode filename or foldername

### ISSUE THREAD

**Issue by CharlesMengCA** [yhirose/cpp-httplib#361]
Hi,

When a HTML file has Unicode filename or is in a folder with Unicode char in the name.

it will get 404 not found error.

Current library can not handle the /%XX%XX%XX%XX/ in the URL.

**Comment by yhirose** [comment]
@CharlesMengCA, thanks for the report, but the library actually handle the 'percent-encoded form' here:

https://github.com/yhirose/cpp-httplib/blob/9a663aa94e005434c0e7dc2cc21eef2d11485c24/test/test.cc#L1044-L1052

I guess this is caused by the encoding mismatch between the server and client. Hope it helps!

**Comment by CharlesMengCA** [comment]
The problem came from here. 

If the path has Unicode chars in it.  such as E:\Pages\测试\index.htm. 
the is_file will return file not found.

`if (detail::is_file(path)) {
						detail::read_file(path, res.body);
						auto type =
							detail::find_content_type(path, file_extension_and_mimetype_map_);
						if (type) { res.set_header("Content-Type", type); }
						res.status = 200;
						if (!head && file_request_handler_) {
							file_request_handler_(req, res);
						}
						return true;
					}`
