### ISSUE TITLE
About file proxy

### ISSUE THREAD

**Issue by sayiwen** [yhirose/cpp-httplib#365]
Hello , I want to micro file proxy module to protect the real url . can i realize that by this lib?

example : 
Real url : http://www.test.com/hello.mp4

In electron 
```
<video src="localhost:1234/hello.4"></vide>
```

thanks

**Comment by yhirose** [comment]
Thank you for the question. But I don't  understand what you are asking... It seems it has nothing to do with cpp-httplib.

**Comment by PixlRainbow** [comment]
I think his example is showing that he has an app that uses electron for user interface and wants to use cpp-httplib to build a proxy that acts as a locally hosted middleman between his interface and his remote server, so that his users cannot view the full remote URL by simply opening the electron developer panel
