### ISSUE TITLE
How to build with Mingw on Windows?

### ISSUE THREAD

**Issue by Ajusa** [yhirose/cpp-httplib#37]
Hey there,

I really like the idea behind this library, but I am running into a few issues when trying to include this with my project. I am using g++ with Mingw on Windows, rather than Visual Studio.

My current command to run everything looks like this: 
```
g++ test.cpp httplib.h -DWEBVIEW_WINAPI=1 -lole32 -lcomctl32 -loleaut32 -luuid -mwindows -DGTEST_USE_OWN_TR1_TUPLE -I.. -I. -Wall -Wextraw
```
I am also using a Webview library to create a browser. The errors that I receive are related to " undefined reference to `_imp__freeaddrinfo@4'" for example, so linker errors. 

Any ideas?

**Comment by yhirose** [comment]
@Ajusa, thanks for your interest. Since I have never tested this library on Mingw, I am not sure of the exact reason why the linker complains. But according to the following stackoverflow answer, adding `-lws2_32` may solve the problem.
https://stackoverflow.com/questions/2033608/mingw-linker-error-winsock

**Comment by yhirose** [comment]
@Ajusa, please let me know if you still have this problem.

**Comment by munxar** [comment]
@yhirose FYI: the `-lws2_32` flag solved it for me.
