### ISSUE TITLE
Doc should talk about "set_base_dir"

### ISSUE THREAD

**Issue by sepatin** [yhirose/cpp-httplib#371]
Hi 

Great lib , thanks !
Perhaps you should add set_base_dir to documentation for serving files from directory.

Greetings.

**Comment by yhirose** [comment]
@sepatin, thank you for the feedback. In fact, `set_base_dir` is deprecated and superseded by `set_mounting_point`. Please see the following issue: #341.

https://github.com/yhirose/cpp-httplib/blob/bf7700d1924e12a27faa5d346a5b8a9f8e163b61/httplib.h#L466-L469

I discourage users from using `set_base_dir`, since it has limitations and `set_mounting_point` is complete and more flexible. That's why README describes only for `set_mounting_point`.

Hope this explanation helps, and thank you for your interest in this library!

**Comment by sepatin** [comment]
Thanks for your answer and explanation, i misundesrtood some points...
I was also wondering if there was a way to mount only files (not all files of a directory) ?
