### ISSUE TITLE
Basic/digest authentication support on server

### ISSUE THREAD

**Issue by pampo** [yhirose/cpp-httplib#375]
Hello from Italy and many thanks for this library!

Is it possible to authenticate a remote browser (with basic or digest mode), i.e add authentication support on server?

Regards,

Matteo

**Comment by yhirose** [comment]
@pampo, thank you for the feedback. But unfortunately, authentication support on server is out of scope of this library. (In fact, the authentication support on client is much easier, and it has been already implemented in cpp-httplib. This is because it doesn't require any another resource.)

In order to support the feature on server, there are a number of different ways to do depending on user's requirements and user's environments. For example, how to store and secure user names and passwords? on database, or encrypted hidden, or just plain text file? Supporting digest authentication requires more such as how to manage values such as `nonce` and `cnonce` on server.

So I decided keep cpp-httplib simple by not providing any particular implementation for authentication support on server. It seems like other light-weight HTTP libraries such as Flask are taking the same way. Flask itself doesn't provide authentication, but we can add the feature with an external plugin like Flask-HTTPAuth. But Flask-HTTPAuth may not fit in all the situations. In that case, you have to find another plugin.

You actually receive all you need via HTTP headers from client to handle authentication. It's difficult to handle the digest authentication by yourself, but it's not too difficult to handle the basic authentication on your own. Because the basic authentication header is pretty simple for extracting username and password.

Hope it helps!

**Comment by pampo** [comment]
Many thanks for your kind and exhaustive reply!

Regards, Matteo
