### ISSUE TITLE
Please add big file upload example

### ISSUE THREAD

**Issue by miketsts** [yhirose/cpp-httplib#389]
Hi,

It would be nice to have a client example of a big file upload. 

I can see separate examples "POST with Multipart Form Data", which sends a small file preloaded in a memory buffer, a server example of using a content provider, receiving chunked data, using progress callback. I probably need to combine them all together, and can't quite figure out how to do this. Add to this that my file is actually an ASCII one which would be nice to compress on the wire. 

A corresponding server example can be probably nice as well.

Thanks.

**Comment by yhirose** [comment]
@miketsts, I actually don't understand what you are really asking for... Could you explain it more clearly? Thank you.

**Comment by PixlRainbow** [comment]
He wants a *streamed* multipart POST, with compressed encoding, on client (optionally server), but he is unable to figure out how the seperate examples are intended to be combined.

**Comment by miketsts** [comment]
Yes, @PixlRainbow is basically right. 
Generally, I want to upload a big file to a server. I may be wrong, but I figure that the way to do it is using multpart POST with content provider. I would be glad to learn another way if it exists, without reading the entire file to memory.

**Comment by yhirose** [comment]
@miketsts, @PixlRainbow, I got it now, thanks for the clarification!

The short answer is you cannot use content provider in multipart-form-data at this point. Sorry about that...

Also the current compression implementation like gzip stores the compressed body data entirely on memory before sending it onto the wire...

In order to support content provider in multipart-form-data, cpp-httplib may need to enhance `MultipartFormData` to have at least another two member variables as bellow:

```cpp
struct MultipartFormData {
  std::string name;
  std::string content;
  std::string filename;
  std::string content_type;
  // New members for content provider support
  ContentProvider content_provider;
  size_t content_length;
};
```

As for compress, you can find what it actually does in the following code:

https://github.com/yhirose/cpp-httplib/blob/b0af78e340761114cf107f68f839241627235d3e/httplib.h#L3935-L3965

As you can see above, the compression data is stored in `req.body`. I wish I could avoid this unnecessary memory consumption. But 'Content-Length' should be calculated and sent before sending compressed data, but there is no way to figure out content length unless we get the entire compressed data on hand...

Anyway, handling content provider in multipart-form-data is technically possible once I come up with good and user friendly interface. When I have time, I'll consider to implement it.

Thanks for your fine feedback!

**Comment by miketsts** [comment]
@yhirose thank you.
I'll think about a better solution for me. Either run curl /gzip as external shell command or implement this functionality :-). I can't promise that in the coming days though.

**Comment by yhirose** [comment]
Hope your solution will go well!
