### ISSUE TITLE
no answer if upload file with Cyrillic path multipart/form-data (server)

### ISSUE THREAD

**Issue by 2020karaulov2020** [yhirose/cpp-httplib#393]
Example file name : **d:\Games\Warcraft III 126\Maps\Download\Варкравт.w3x**
httplib can't process request from client if I upload file with these name!

**Comment by 2020karaulov2020** [comment]
Possible problem in regex and need escape strings ?!

**Comment by ben-sol** [comment]
does the server side spin on the request? It may be related to #396

**Comment by 2020karaulov2020** [comment]
@ben-sol i don't test it, but possible. Only with these file name.... Very strange...

**Comment by yhirose** [comment]
@2020karaulov2020, thank you for the feedback, but it's not enough information to identify the real cause of the problem. Could you give me a smallest possible code example of your server, and show me the actual HTTP multipart-form data from the client that you are using? Then, I'll try to reproduce it on my machine and add it to the unit test cases. Thanks.

**Comment by 2020karaulov2020** [comment]
@yhirose Strange, but the problem resolved by itself)))

**Comment by yhirose** [comment]
@2020karaulov2020, glad to hear the report. But it cannot be resolved by itself. :) Since the cpp-httplib code stays, the real cause must apparently have been in you code. Do you remember what change you made in your code that may have fixed the path problem? Is it an encoding problem of your file path? Your answer could be helpful for others. Thank you!

**Comment by 2020karaulov2020** [comment]
@yhirose sorry i just remove unused pages from code. (before not working page)
no more changes....
