### ISSUE TITLE
help needed to use cpp-httplib in https://github.com/bstarynk/helpcovid

### ISSUE THREAD

**Issue by bstarynk** [yhirose/cpp-httplib#401]
We are coding https://github.com/bstarynk/helpcovid  which uses cpp-httplib and we need some help.

* how to limit the number of threads to a small amount (e.g. 4) during debugging?

* how to exit the HTTP server? 
That is quit the event loop.

If possible, contact me by email.

Thanks

<basile@starynkevitch.net>

http://starynkevitch.net/Basile/

(near Paris, France)

**Comment by PixlRainbow** [comment]
Hi @bstarynk , I am uncertain if this query has been responded to as private emails do not appear in GitHub issue tracking. So I will write a response here anyway just in case, and so that other people with similar issues may find it.  

1. **How to exit the http server?** You can use [the `.stop()` method](https://github.com/yhirose/cpp-httplib/blob/master/README.md#server-example) on the server. This must be done either in an alternate thread or in a path handler, because `listen` will block it's calling thread.
2. **How to limit number of threads to a small amount?** You may set the value of [the macro `CPPHTTPLIB_THREAD_POOL_COUNT`](https://github.com/yhirose/cpp-httplib/blob/master/README.md#default-thread-pool-support) to change the default thread count.

If you feel your questions have been answered, you may click the close issue button.

**Comment by bstarynk** [comment]
On 3/25/20 1:46 PM, PixlRainbow wrote:
>
> Hi @bstarynk <https://github.com/bstarynk> , I am uncertain if this 
> query has been responded to as private emails do not appear in GitHub 
> issue tracking. So I will write a response here anyway just in case, 
> and so that other people with similar issues may find it.
>
>  1. *How to exit the http server?* You can use the |.stop()| method
>     <https://github.com/yhirose/cpp-httplib/blob/master/README.md#server-example>
>     on the server. This must be done either in an alternate thread or
>     in a path handler, because |listen| will block it's calling thread.
>  2. *How to limit number of threads to a small amount?* You may set
>     the value of the macro |CPPHTTPLIB_THREAD_POOL_COUNT|
>     <https://github.com/yhirose/cpp-httplib/blob/master/README.md#default-thread-pool-support>
>     to change the default thread count.
>
> If you feel your questions have been answered, you may click the close 
> issue button.
>

You can contact me directly by email to basile@starynkevitch.net (or on 
WhatSapp)

> -- 
>
Basile STARYNKEVITCH   == http://starynkevitch.net/Basile
opinions are mine only - les opinions sont seulement miennes
Bourg La Reine, France; <basile@starynkevitch.net>
(mobile phone: cf my web page / voir ma page web...)

**Comment by yhirose** [comment]
@bstarynk, in addition to the @PixlRainbow's comment, you can see how to use `.stop()` method in the following unit test:

https://github.com/yhirose/cpp-httplib/blob/5b51aa6851d4b03753ec359362b3b6a598b3845e/test/test.cc#L2139-L2177

You can also find more unit test cases that use the method in test/test.cc.

As for thread count, please read [here](https://github.com/yhirose/cpp-httplib#default-thread-pool-support) in README.

If the default thread pool implementation doesn't satisfy your needs, you can replace it with your own better implementation. Please see [here](https://github.com/yhirose/cpp-httplib#override-the-default-thread-pool-with-yours).

Hope it helps.
