### ISSUE TITLE
Bad behavior on Windows 7

### ISSUE THREAD

**Issue by SLIpros** [yhirose/cpp-httplib#410]
Hey, some of my users that use Windows 7 receive incorrect GET response. It's has some random bytes of data in it. This is not server related. I am using Windows 10 and don't have such behavior. Any ideas what can that be? Data on screenshot is base64 encoded string.

It's looks like a chunks of data at Windows 7. 
![2020-04-02_23-07-31](https://user-images.githubusercontent.com/6332783/78296664-cf033880-7536-11ea-920c-1af2560ebc02.png)

On Windows 10 it's a whole piece of data.
![2020-04-02_23-19-48](https://user-images.githubusercontent.com/6332783/78297591-851b5200-7538-11ea-8455-f5c3d8ed61fd.png)

+ i found another bug. Status code is -1 when server answer with 200 for same Windows 7 users.

**Comment by yhirose** [comment]
@SLIpros, thanks for the feedback. Since I don't have Windows 7, I am not able to reproduce and fix this problem on my machine. Sorry about that. Of cause, a pull request from you is always welcome!

As you know, Windows 7 support by Microsoft is actually ended on January 14, 2020. So I personally don't have any motivation to support cpp-httplib on such an out of date operating system which might expose users to dangerous security problems. I am rather thinking to mention that cpp-httplib doesn't support Windows 7 in README.

Please see the similar issue for old versions of OpenSSL:
https://github.com/yhirose/cpp-httplib/issues/192

Anyway, thank you for your interest in this library and the valuable report!

**Comment by SLIpros** [comment]
@yhirose Thanks for fast reply. As a maintainer can you mention a places in a source code of cpp-httplib where you think I can start to search this error happens? Source code is big and for first look it's looks like a voodoo magic for me (sorry) ))

**Comment by PixlRainbow** [comment]
Looking closer at the data, it doesn't look like it is incorrect data. It looks like one of them has defaulted to http chunked encoding scheme and the other defaulted to one shot encoding.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the comment. Yes, you are right. The first response is a chunked format data.

@SLIpros, could you respond to @PixlRainbow's comment? Also when you debug in cpp-httplib, `process_request` method is a good place to set a break point.

**Comment by SLIpros** [comment]
@PixlRainbow Thanks for info i will look in that.
@yhirose Thanks. When i got something i will report here.

**Comment by yhirose** [comment]
@SLIpros, please let me know if it's really a problem in cpp-httplib. For now, I close it. Thanks!
