### ISSUE TITLE
What is the role of the first argument to httplib::Server::listen?

### ISSUE THREAD

**Issue by bstarynk** [yhirose/cpp-httplib#414]
What is the *exact* role of the first argument to `httplib::Server::listen`?

Should it be set to `"0.0.0.0"`  for a server running on host `b-star-y.tech` ? I was expecting to set it to `"b-star-y.tech"` ...

Or is a terminating dot required??

Can you give us a working example?

We are using commit 1ccddd1b0b33d782df3b2b of httplib.h in our program [helpcovid](https://github.com/bstarynk/helpcovid) its [commit 7aff319220cf4ab](https://github.com/bstarynk/helpcovid/commit/7aff319220cf4ab9141be6f20a83e6382ebc3481)

(Debian Buster) which we try to run on `http://b-star-y.tech:8089/` or on  `https://b-star-y.tech:8089/` 

so far without success....

<basile@starynkevitch.net> near Paris in France

http://starynkevitch.net/Basile/

**Comment by PixlRainbow** [comment]
It makes the server listen on a specific network interface. The actual value of the argument needed will depend on your system network configuration.
IETF defines that operating systems and TCP/IP stacks must interpret a binding request of `0.0.0.0` as meaning "all interfaces", while `127.0.0.1` must refer to the loopback ("this machine only") interface.
You may be able to set it to a domain name, but it will only work if your OS has been configured to recognize a particular network interface as "owning" the domain name.

**Comment by bstarynk** [comment]
On 4/6/20 7:07 PM, PixlRainbow wrote:
>
> It makes the server listen on a specific network interface. The actual 
> value of the argument needed will depend on your system network 
> configuration.
> IETF defines that operating systems and TCP/IP stacks must interpret a 
> binding request of |0.0.0.0| as meaning "all interfaces", while 
> |127.0.0.1| must refer to the loopback ("this machine only") interface.
> You may be able to set it to a domain name, but it will only work if 
> your OS has been configured to recognize a particular network 
> interface as "owning" the domain name.
>

But what is the exact syntax, assuming I own the b-star-y.tech DNS and 
am renting a VPS running it on IPv4 address 185.98.128.180


Is it "b-star-y.tech" or ".tech.b-star-y" ?



> -- 
>
Basile STARYNKEVITCH   == http://starynkevitch.net/Basile
opinions are mine only - les opinions sont seulement miennes
Bourg La Reine, France; <basile@starynkevitch.net>
(mobile phone: cf my web page / voir ma page web...)

**Comment by yhirose** [comment]
In addition to the @PixlRainbow, answer, `httplib::Server::listen` calls the following socket system calls in order:

  * `getaddrinfo`
  * `bind`
  * `listen`

Your IP address or host name will be resolved with `getaddrinfo` into a `struct addrinfo` items list. cpp-httplib tries to use one of `struct addrinfo` items in the list to make a server socket.

You can see how "0.0.0.0" or "b-star-y.tech" are resolved in your your network setting with the following  simple Python HTTP server code:

```
python3 -m http.server [PORT] --bind [IP or HOSTNAME]
```

Once you figure out which one should be used, you can pass it to the 1st parameter of `httplib::Server::listen`, and the cpp-httplib server should work like the simple Python server.

That's all that I can say to you at this point. Since your question has nothing to do with cpp-httplib, rather it's a general TCP/IP question, you can find more information from [linux system call manual](http://man7.org/linux/man-pages/man3/getaddrinfo.3.html) or other stackoverflow post like [this](https://stackoverflow.com/questions/7942969/getting-server-ip-0-0-0-00-from-getaddrinfo).

Anyway, thank you for your interest in this library. Hope this explanation helps you.

**Comment by bstarynk** [comment]
On 4/7/20 11:30 PM, yhirose wrote:
>
> In addition to the @PixlRainbow <https://github.com/PixlRainbow>, 
> answer, |httplib::Server::listen| calls the following socket system 
> calls in order:
>
>   * |getaddrinfo|
>   * |bind|
>   * |listen|
>
> Your IP address or host name will be resolved with |getaddrinfo| into 
> a |struct addrinfo| items list. cpp-httplib tries to use one of 
> |struct addrinfo| items in the list to make a server socket.
>
> You can see how "0.0.0.0" or "b-star-y.tech" are resolved in your your 
> network setting with the following simple Python HTTP server code:
>
> |python3 -m http.server [PORT] --bind [IP or HOSTNAME] |
>
> Once you figure out which one should be used, you can pass it to the 
> 1st parameter of |httplib::Server::listen|, and the cpp-httplib server 
> should work like the simple Python server.
>
> That's all that I can say to you at this point. Since your question 
> has nothing to do with cpp-httplib, rather it's a general TCP/IP 
> question, you can find more information from linux system call manual 
> <http://man7.org/linux/man-pages/man3/getaddrinfo.3.html> or other 
> stackoverflow post like this 
> <https://stackoverflow.com/questions/7942969/getting-server-ip-0-0-0-00-from-getaddrinfo>.
>
> Anyway, thank you for your interest in this library. Hope this 
> explanation helps you.
>
> —
>

Sorry for having asked. It turned out that the VPS we are using on 
b-star-y.tech for testing purposes had most of it IP ports closed, with 
a very bad web user interface.

Thanks

-- 
Basile STARYNKEVITCH   == http://starynkevitch.net/Basile
opinions are mine only - les opinions sont seulement miennes
Bourg La Reine, France; <basile@starynkevitch.net>
(mobile phone: cf my web page / voir ma page web...)
