### ISSUE TITLE
using httplib cmake target

### ISSUE THREAD

**Issue by guteksan** [yhirose/cpp-httplib#421]
Hi,
I am having a problem with linking httplib library to my project.
I have built httplib and installed it in a certain destination <httplib-install>

My CMakeList.txt contains:
```
find_package(httplib CONFIG REQUIRED)
...
add_executable(${PROJECT_NAME} ${SRC})
target_link_libraries(${PROJECT_NAME} PUBLIC httplib)
```

This works, and the Cmake cache contains valid entry for httplib_DIR where the httplibConfig.cmake is located. But when I try to compile my project, it can't find the httplib.h, which I include. I looked into httplibConfig.cmake and there is created an INTERFACE target httplib (without any namespace), so I believe linking targets it the way I did should be enough to pass all directories. Could you please point out what is missing?

**Comment by yhirose** [comment]
@guteksan, thank you for the feedback. Did you install httplib via CMakeLists.txt in this project? If so, this CMakeLists.txt has been contributed by other user, and I am not familiar to what it actually do (, even I am thinking of removing the file from this project).

Since this library is a 'header-only' library, it doesn't need to link anything. So once you manually copy httplib.h to one of include directories in your system, it much be compiled without any other treatment.

Hope it help!

**Comment by guteksan** [comment]
Hi, @yhirose , thank you for prompt reply.
Yes, I did use CMakeLists.txt from this project to build and install the library. It went smooth, so I thought it is the right way, 
I know that header only libraries do not need to be linked, anyway I always prefered to separate my original code from the 3rd party dependencies, and using targets installed in the system is a nice way to do it. You might want to have a look at the Eigen library, which is also header only and allows to be used as targets in own projects.

**Comment by yhirose** [comment]
@guteksan, if "It went smooth, so I thought it is the right way" is true,  what do you think causes the problem, in CMakeLists.txt in cpp-httplib, or the one in your project?

Since I haven't used the CMakeLists.txt at all and even tested it, I am tending to remove it from this repo though...

**Comment by PixlRainbow** [comment]
Header only libraries on cmake are not linked against. Instead `target_include_directory` is used with the found directory.

**Comment by guteksan** [comment]
@PixlRainbow: not exactly. I am not talking about linking in a proper sense, but about linking in a cmake buildsystem sense. Cmake has a concept of targets which combine information about both libs and include directiories, and the proper way of adding the dependency to a target is by: ```target_link_libraries```, even if this is header only library. CMakeLists.txt attached to a project created a target named ```httplib```, so that method should be used. Out of curiosity I checked if ```target_include_directiories``` will work on ```httplib``` target, but it didn't.

**Comment by yhirose** [comment]
@guteksan, if you think the current CMakeLists.txt has a problem and causes the confusion, I'll get rid of it from this project because I don't use it and I am not planning to maintain it. Please let me know. Thanks!

**Comment by sum01** [comment]
Why would you remove it? Having a Cmake file available is nice, even for header-only. It also affects the Conan package (at least future versions).

The problem is that the file just had minor errors. It included the wrong path versus where it installed it to.

If you wish, I could submit a fix, as well as some improvements upon the file, considering the file is missing some important things (dependencies like openssl or zlib, versioning).

**Comment by sum01** [comment]
Could you consider bringing the file back? Having a Cmake file available is nice, even for header-only. It also affects the Conan package (at least future versions).

The problem was probably where it installed to. For example, it was installing to `/usr/include/httplib/httplib.h` on Linux, but I'm assuming the OP was doing `#include <httplib.h>`. I personally tested v0.5.9, and it worked as-is with only a change to `#include <httplib/httplib.h>`.

If you wish, I could submit a fix so it's just `#include <httplib.h>`, as well as some improvements upon the file, considering the file is missing some important things (opt. deps like openssl or zlib, threads, versioning).
