### ISSUE TITLE
Support server stop

### ISSUE THREAD

**Issue by malkindan** [yhirose/cpp-httplib#43]
How does the library Server object support stopping the listener ?

**Comment by yhirose** [comment]
@malkindan, the Server has [the `stop` method](https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L202).

This method should be called in a different thread from the thread where the server is running. I am using it in [my example](https://github.com/yhirose/cpp-httplib/blob/master/example/server.cc#L102-L104).
```cpp
    svr.get("/stop", [&](const auto& /*req*/, auto& /*res*/) {
        svr.stop();
    });
```

**Comment by malkindan** [comment]
Yes . I found it . Exactly what I am doing.
I am hosting the server inside Windows service. After I call stop() it just
hangs

**Comment by yhirose** [comment]
Sorry to hear that... Actually, the above example that I mentioned isn't good. [This example](https://github.com/yhirose/cpp-httplib/blob/master/test/test.cc#L272-L284) in my unit test could be better.

```cpp
        t_ = thread([&](){
            svr_.listen(HOST, PORT);
        });

        while (!svr_.is_running()) {
            msleep(1);
        }
    }

    virtual void TearDown() {
        svr_.stop();
        t_.join();
    }
```

The point is that the `listen` method runs in a different thread from a thread where the `stop` method runs.

If it still doesn't help you, could you show me how to call the `listen` and `stop` methods in your code in order to understand the problem more clearly?

Thanks!

**Comment by malkindan** [comment]
Thank you. I will test tomorrow and tell you if this worked

**Comment by malkindan** [comment]
I downloaded the new version of httplib and now stop works well.

**Comment by yhirose** [comment]
Thanks for the report! 😄

**Comment by Shielsy** [comment]
I'm seeing the same problem - calling stop() had no effect on listen. It just hangs. I'm calling stop in a different thread.  Is this a bug?
