### ISSUE TITLE
Incomplete type errors on Cygwin/Windows10

### ISSUE THREAD

**Issue by TR-SLimey** [yhirose/cpp-httplib#433]
I get `has incomplete type and cannot be defined` errors when compiling a project using httplib on Windows10 under Cygwin with G++. The same project compiles fine under Ubuntu and the errors from httplib are the only ones when switching to Windows.

The whole error log is here: https://pastebin.com/YF4jpKTs

**Comment by yhirose** [comment]
@TR-SLimey, thank you for the feedback. Since I don't use Cygwin and have little knowledge about it, I am not able to help you. The only information that I found is [this stack overflow post](https://stackoverflow.com/questions/4162237/c-socket-programming-with-cygwin). But I don't think it's helpful. Sorry about that...

I'll add a note that cpp-httplib doesn't support cygwin on Windows in README, so that users don't get confused. Then I'll close this issue. Or, if you find how to fix it, please send me a pull request.

Thank you for your interest in this library and contribution!

**Comment by TR-SLimey** [comment]
Okay. Will do
