### ISSUE TITLE
Receving SIGPIPE signal if the hostname / port is wrong

### ISSUE THREAD

**Issue by lasryaric** [yhirose/cpp-httplib#44]
When using the code sample : 

` ``
 std::thread signaling_health_thread([] () {
      printf("hey from new thread!\n");
      httplib::Client cli("localhost", 1234);

    auto res = cli.get("/hi");
    printf("I have got a res!\n");
    if (res && res->status == 200) {
      std::cout << res->body << std::endl;
    }
    });
    signaling_health_thread.join(); 
```

I get a SIGPIPE signal if there is no port open on localhost:1234.

Is that expected ? Thanks.

**Comment by adamshapiro0** [comment]
I'm hitting the same issue. The call to `send()` in `SocketStream::write()` is issuing a SIGPIPE since the endpoint doesn't exist.

The issue seems be when `create_client_socket()` tries to establish a connection to the remote machine. It does that by setting the socket to non-blocking before calling `connect()`, presumably so the connection attempt returns quickly instead of waiting for a connection timeout. In non-blocking mode, `connect()` returns `EINPROGRESS` if the connection can't be established _immediately_, but that doesn't necessarily mean the remote machine isn't listening. For a viable connection, it's possible (likely) that the connection is still being established and the `send()` call will still work eventually once the connection is made. `is_connection_error()` appears to ignore `E_INPROGRESS` to get around this.

If the remote machine actually does not exist, though, you're still likely to get `EINPROGRESS` immediately after calling `connect()` since the connection attempt may take some time to fail. I'm not sure doing a non-blocking connection attempt is the right behavior here, especially since all send calls themselves are blocking so the caller doesn't have any real expectation of a fast return. Switching to blocking before calling `connect()` appears to work just fine (it catches `ECONNREFUSED` and fails gracefully).

Is there any particular reason the `connect()` call is being done as a non-blocking call? Would it be a problem to switch to blocking?

It might also be helpful to add a helper function to test if a connection can be established, separate from actually issuing a send (e.g., `Client::test_connection()`, which simply tries to create and connect a socket). That way, the caller can distinguish between a failed connection and a failed send.

**Comment by adamshapiro0** [comment]
Took a quick look at the git log and it looks like @yhirose made this change in December in #40 to resolve #34 (add connection timeout support). @yhirose, would you mind commenting on the blocking/non-blocking connection attempt?

**Comment by yhirose** [comment]
@lasryaric, @adamshapiro0, thank you for the valuable feedback.

Please see my following comment regarding the non-blocking connection attempt:
https://github.com/yhirose/cpp-httplib/issues/34#issuecomment-354567796

As you see in the comment, #40 implements the connection timeout feature that someone requested. I tried it in the cross-platform way as cURL does to work on MacOS, Linux and Windows. Here is an example.

```cpp
httplib::Client cli("google.com", 8080, 5);
auto res = cli.get("/"); // Timeouts in 5 seconds
asseet(ret == false);
```

But you both reported, my implementation (and possibly cURL's implementation as well?) seems to have a problem.

I tried to reproduce the problem with @lasryaric's sample code, but I don't get the `SIGPIPE` signal on my MacBook. Could you give me what OS (and other environment information) you are running this sample on?

I appreciate any helpful information. Thanks!

**Comment by lasryaric** [comment]
I was running it on ubuntu:16.04 over docker for macos.
Does that help you or do you need more information?

Also, I have no idea why, but it seemed to do that the port 1234 (as per the example) but not when using the port 81, which was closed. 
I will try to reproduce and give you more information if I can .

**Comment by adamshapiro0** [comment]
I was also using Ubuntu 16.04 on a bare metal machine. Did you try running in GDB? I found that with even core dumps enabled, if you run it outside of a debugger it just crashes silently. When I run in GDB the `SIGPIPE` is obvious.

I was able to replicate it with this:

```c++
#include <cstdio>
#include <httplib.h>

int main(int argc, const char* argv[])
{
    httplib::Client* connection = new httplib::Client("localhost", 12345);
    auto response = connection->head("/non_existent");
    if(response)
    {
        printf("Worked: status=%d\n", response->status);
    }
    else
    {
        printf("Connection failed!\n");
    }

    return 0;
}
```

**Comment by yhirose** [comment]
Thank you for the comments and sample code. I am now able to reproduce it.

**Comment by yhirose** [comment]
@adamshapiro0, your comment regarding `EINPROGRES` gave me a good insight.

I checked this matter with the UNIX Network Programming by W. Richard Stevens, and found a correct way to handle the non-blocking connection at §16.4 of the book. ([sample code](https://github.com/hailinzeng/Unix-Network-Programming/blob/master/lib/connect_nonb.c))

When I have free time this weekend, I'll work on this problem.

Thanks again for your helpful comment!

**Comment by adamshapiro0** [comment]
Great - glad I could help!

**Comment by yhirose** [comment]
@lasryaric, @adamshapiro0, I fixed this issue, and confirmed on Mac OS, Windows and Ubuntu 16.04.
When you have time, could try the latest `httplib.h`?

**Comment by lasryaric** [comment]
thank you @adamshapiro0 , I should start testing it on Monday or Tuesday so I will keep you posted.

**Comment by adamshapiro0** [comment]
That seems to be working for me. Thanks!
