### ISSUE TITLE
Method to retrieve port after starting with port 0?

### ISSUE THREAD

**Issue by sgraham** [yhirose/cpp-httplib#46]
I was trying to use cpp-httplib for running tests, so I'd like to start it on a system-selected port, and then have clients connect to that port. I don't want to pre-select a port number to avoid collisions with other things on the system, or when tests are run in parallel.

When I do the common thing of passing 0 as the server port everything seems to work, and I was able to hunt down the actual port by running netstat, and when I then connect to that port things work just fine.

Would it be possible to have a method to retrieve port that the server's running on? (Or is that already possible and I missed how to do so?)

**Comment by yhirose** [comment]
@sgraham, thanks for the feedback. cpp-httplib doesn't have a method that tells the actual port.

It seems like we can the figure out the actual port with `getsockname` system call. But it's a bit difficult to pass it to a user, since `Server::listen` method is a blocking method. 

One solution is to make a method like `Server::get_actuall_port`. But a user has to call the method only on a different thread.

Another way is that we could make a method like `Server::on_conneced` which takes a callback function where we will receive the actual port number.

I'll get back to you when I decide which solution should be taken.

**Comment by sgraham** [comment]
Thank you for considering this request! Perhaps an on_connected() would be slightly simpler conceptually, but either of those solutions seem fine to me.

**Comment by sgraham** [comment]
Another thought I just had... I think the port is selected by this point? https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L1413

Perhaps it would be possible to split optionally split `listen()` at that location, so that the user can call something like `bind_to_any()`, which could return the selected port, and then call `listen_after_bind()`. I'm not sure if that's better or worse than an optional callback though.

**Comment by sgraham** [comment]
Something like https://github.com/yhirose/cpp-httplib/compare/master...sgraham:system-assigned-port?expand=1 is what I was thinking for above, if you like that approach.

**Comment by yhirose** [comment]
@sgraham, your approach looks much better than mine! Could you make a pull request, so that I could merge it to my master. The only thing is the name of `bind_to_any()`. Could something like `bind_to_any_port()` be clearer to users?
