### ISSUE TITLE
Bearer token authorization

### ISSUE THREAD

**Issue by miketsts** [yhirose/cpp-httplib#484]
I'm developing a REST client to a service using bearer token authorization. Meaning "Authorization" header having "Bearer XXXXXX" content. Currently I just add this header (the token is predefined) to each client request.
As I see this library provides support for basic user/password authorization, can it make sense to provide also token authorization in a similar way? For example, it may be a plug-in authorization class, either basic, bearer or other, which is once installed to the client and then used automatically with each request.

Thank you.

**Comment by yhirose** [comment]
@miketsts, thank you for your feedback! This library currently supports basic and digest authorizations only. I am not using the Bearer token authorization and don't know how to implement it at this point. A pull request for it is always welcome of course!

The authorization plug-in sounds great idea. But I feel it's not easy to accomplish as we think, since each authorization has its own unique specification. You can see how I handled basic and digest authorizations in httplib.h. I couldn't handle them in a same spot, rather they are handled in different places... It would be nice if we could find a cleaner way to integrate any authorization scheme.

**Comment by Bendr0id** [comment]
Bearer AUTH is very trivial and you can already use it.

On the client: 
```
req.set_header("Authorization", "Bearer XXXXXXXXXX");
```

On the server:
```
m_srv->Get(R"(/.*)", [this](const httplib::Request& req, httplib::Response& res)
{
  int status = HTTP_OK;

  auto authHeader = req.get_header_value("Authorization");
  auto credentials = std::string("Bearer XXXXXXXXXX");

  if (!authHeader.empty() && credentials == authHeader)
  {
    // handle the GET request here...    
    // status = this->handleGET(req, res);
  }
  else if (authHeader.empty())
  {
    status = HTTP_UNAUTHORIZED;
  }
  else
  {
    status = HTTP_FORBIDDEN;
  }

  res.status = status;

  res.set_header("Access-Control-Allow-Origin", "*");
  res.set_header("Access-Control-Allow-Methods", "POST, GET, OPTIONS");
  res.set_header("Access-Control-Allow-Headers", "Content-Type, Authorization");
  res.set_header("WWW-Authenticate", "Basic");
  res.set_header("WWW-Authenticate", "Bearer");
});
```
