### ISSUE TITLE
Can you provide API thread safety info in the README doc?

### ISSUE THREAD

**Issue by Kexiii** [yhirose/cpp-httplib#492]
I think it's necessary to tell the user whether the API is thread safe(e.g. Is Client::Get(..) thread safe?).

**Comment by yhirose** [comment]
@Kexiii, basically, `Client` is not thread-safe. Only one thread can own the Client instance. But as you can see in the Client class, `sock_` is declared as `std::atomic<socket_t>`.  You can hold it in a different thread and safely call `stop()` method safely. In this particular case only, `Client` can be said as thread-safe.

Sorry for the incomplete documentation on README. Since this is just my 'after work'/'weekend' project, I simply don't have time to update it... I'll improve the documentation when I have time. I guess I need to mention thread-safety for the server as well.

Thanks for your interest!
