### ISSUE TITLE
Client doesn't work if protocol is specified manually

### ISSUE THREAD

**Issue by Pospelove** [yhirose/cpp-httplib#507]
Hi. Is that behavior expected?
```c++
httplib::Client("cdnjs.cloudflare.com").Get("/ajax/libs/chai/4.2.0/chai.js"); // OK
httplib::Client("https://cdnjs.cloudflare.com").Get("/ajax/libs/chai/4.2.0/chai.js"); // nullptr
```
Reproduced on 0.5.1

**Comment by yhirose** [comment]
@Pospelove, thanks for the question. It's exactly expected, because the first parameter in the constructor takes hostname. If you want https, you have to use `httplib::SSLClient`.

I recently added the experimental class `httplib::Client2` which takes scheme + hostname. So the following should work:

```cpp
httplib::Client2("https://cdnjs.cloudflare.com").Get("/ajax/libs/chai/4.2.0/chai.js");
```

Hope it helps.
