### ISSUE TITLE
POST with empty content but without Content-Length: 0 returns 400

### ISSUE THREAD

**Issue by mestag-a** [yhirose/cpp-httplib#523]
I'm trying a simple program which logs part of the URL. Everything works fine with GET, but not with POST. Here is the code :
```C++
#include <httplib.h>
#include <iostream>

int main() {
  namespace http = httplib;

  auto log = [](http::Request const& req, http::Response& res) {
    auto payload = req.matches[1];
    std::cout << "Payload: " << payload << '\n';
  };
  http::Server srv;
  srv.set_error_handler([](auto const& req, auto& res) {
      std::cerr << "Error\n";
    });
  srv.Get("/in/(.*)", log);
  srv.Post("/in/(.*)", log);
  srv.listen("localhost", 8080);
  return 0;
}
```
Compiled with `g++ -I.. -std=c++14 post_no_content.cc -lpthread`, from the `example` folder of the repository.

Here are the tests, using `cURL` :
- Using a GET request, returns code `200 OK`, fine.
```
$ curl -X GET "http://127.0.0.1:8080/in/yolo" -w '%{http_code}\n'
200
```
- Using a POST request, hangs for 5 seconds, and returns code `400`.
```
$ curl -X POST "http://127.0.0.1:8080/in/yolo" -w '%{http_code}\n' 
400
```
- Using a POST request, but explicitly specifying an empty content, returns code 200, fine.
```
$ curl -X POST "http://127.0.0.1:8080/in/yolo" -w '%{http_code}\n' -d ''
200
```

I made a packet capture using `tcpdump` and looked at the 2 POST requests :
```
POST /in/yolo HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: curl/7.47.0
Accept: */*

```
```
POST /in/yolo HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: curl/7.47.0
Accept: */*
Content-Length: 0
Content-Type: application/x-www-form-urlencoded

```

After looking at the code, my understanding is that the difference in behaviour is due to the lack of the header `Content-Length: 0` in the 1st POST request.
If the header `Content-Length` isn't found, the library calls `read_content_without_length()` which ends up calling `select()` on the socket, which returns 0, since there nothing left to read on the socket.

I'm not enough of an HTTP guru to know what's right and wrong, but the behaviour seems buggy to me.
I compared with a equivalent Python program using `aiohttp`, and it returns `200 OK` for the 3 test cases.
```python
#!/usr/bin/env python3

from aiohttp import web


async def handle(request):
    payload = request.match_info.get('payload')
    print(payload)
    return web.Response()

app = web.Application()
app.add_routes([web.get('/in/{payload}', handle),
                web.post('/in/{payload}', handle)])

if __name__ == '__main__':
    web.run_app(app)
```

To make it work, I commented the `else if` part from the following code from
```C++
template <typename T>
bool read_content(Stream &strm, T &x, size_t payload_max_length, int &status,
	          Progress progress, ContentReceiver receiver,
                  bool decompress) {
  ...

  if (is_chunked_transfer_encoding(x.headers)) {
    ret = read_content_chunked(strm, out);
  } else if (!has_header(x.headers, "Content-Length")) {
    ret = read_content_without_length(strm, out);
  } else {
  ...
}
```

**Comment by yhirose** [comment]
@mestag-a, thank you for the feedback and detailed investigation! Currently, this is an intentional behavior on cpp-httplib.

I did some research about how other HTTP servers handle this situation:
https://stackoverflow.com/questions/1233372/is-an-http-put-request-required-to-include-a-body
https://redmine.lighttpd.net/boards/3/topics/5851
https://issues.apache.org/jira/browse/TS-2902
https://serverfault.com/questions/315849/curl-post-411-length-required

As you can see the above, it seems like [RFC7230 - 3.3.2](http://tools.ietf.org/html/rfc7230#section-3.3.2.) is interpreted differently among HTTP servers...

So I'll keep the current behavior for now, since some HTTP clients actually send content body without Content-Length. (I know the client behavior is really bad though.)

In your case, Lighttpd returns with status 411 (411 - Length Required). It makes sense to me even though some argue about it. I am thinking of implementing it as optional on cpp-httplib as well.

If you don't want to wait 5 seconds, you can adjust the reading timeout with  `set_read_timeout` or `CPPHTTPLIB_READ_TIMEOUT_SECOND`.

Anyway, thanks for the observation!

**Comment by mestag-a** [comment]
Alright, thank you for the information, I'll close the issue then :+1:
