### ISSUE TITLE
Session management

### ISSUE THREAD

**Issue by mbnoimi** [yhirose/cpp-httplib#524]
Hi,

I read about Authorization issue (#127) which is really cool but I wonder what about session management!

Is there any session management in cpp-httplib? If not; What's your suggestion(s) for handling it?

**Comment by mbnoimi** [comment]
Do you consider [handling sessions in frontend](https://medium.com/@rossbulat/using-cookies-in-react-redux-and-react-router-4-f5f6079905dc) side is a good practice or it suppose to be handled by the server (cpp-httplib sever)

**Comment by yhirose** [comment]
@mbnoimi, thanks for your feedback. In fact, cpp-httplib doesn't provides Basic/Digest auth support for server. In order to support it on server, we still have to write code to authenticate users' requests. It requires the server to store users' credentials somewhere in a storage like a DB or a file. The suitable solution depends on each system that the server is running on. This is out of scope of cpp-httplib, because it's a simple HTTP library which can be used for various purposes not only for web services. (Basic/Digest auth support on client is a different story. It does't require the client to store anything during the authorization process.)

The same principle applies to the session management. So I would like not to provide any particular session implementation on cpp-httplib. (Also it seems very difficult for me to implement cross-platform, robust and most importantly, secure session management. I don't think I have enough sill to do it. 😢 )

Anyway, thank you for your idea!
