### ISSUE TITLE
Crash on Windows

### ISSUE THREAD

**Issue by vvanelslande** [yhirose/cpp-httplib#525]
LibreSSL 2.7.2
Windows 7 and 10
Visual Studio 2019

After updating from ec00fe5d5bb2edacf2c6af500623a7220f05f4ff to 144114f316c406423c3686b2379a708b26a54e26, https://github.com/libressl-portable/portable/issues/266 started happening.

**Comment by yhirose** [comment]
@vvanelslande, thanks for the report. However, I don't officially support LibreSSL. Sorry about that... (Please see README which mentions only OpenSSL support. https://github.com/yhirose/cpp-httplib#openssl-support)

I'll close it for now, since I am not planning to support LibreSSL in the future, and OpenSSL works fine on Windows right now. But of course, your pull request is always welcome to fix this problem.

Thank you for your understainding!
