### ISSUE TITLE
Re-constructing/Re-initializing SSLClient

### ISSUE THREAD

**Issue by cflint987** [yhirose/cpp-httplib#560]
Hi I am not sure if I am doing something wrong, but I am unable to re-construct the SSLClient with a new hostname.

The 264 issue seems to indicate that 
cli = httplib::SSLClient(newHostname);
can be used to re-construct the SSLClient.

However, when I try to do it VS 2019 gives me the following compiler error:
Error	C2280	'httplib::SSLClient &httplib::SSLClient::operator =(const httplib::SSLClient &)': attempting to reference a deleted function

https://github.com/yhirose/cpp-httplib/issues/264

**Comment by yhirose** [comment]
@cflint987, thanks for the feedback. Unfortunately, SSLClient (and Client as well) is no longer re-constructable since #499. More precisely, the client classes don't have copy constructor and assignment operator. Alternate way is to use a smart pointer such as `std::shared_ptr` or `std::unique_ptr`.

```cpp
auto cli = std::make_shared<httplib::SSLClient>(...);
cli = std::make_shared<httplib::SSLClient>(...);
```

Hope it helps!
