### ISSUE TITLE
RESTful web server

### ISSUE THREAD

**Issue by DJuego** [yhirose/cpp-httplib#57]
Thank you for this project! Thank you for your effort!

Header-only, no dependencies. cross-platform, light and elegant... It's the closest thing to the solution I was looking for.

Only I miss a more complete interface (with PUT and DELETE and perhaps, others). Any reason not to implement those features?

In any case I am not an expert and I think that what your project offers is enough for my purposes.  :-)

Thanks again!

DJuego

**Comment by yhirose** [comment]
@DJuego, thank you for the feedback. There wasn't any particular reason why I haven't implemented other methods like PUT and DELETE. I only needed GET and PUT when I wrote this library. I may add missing HTTP methods in the future. Thanks for asking!

**Comment by yhirose** [comment]
Also need OPTIONS (#62).

**Comment by yhirose** [comment]
Providing `Server::delete` method is not possible since `delete` is a C++ reserved keyword. So we have to compromise to choose a different name like `del`. Or we could use `DELETE`. If we choose such a word with all capital letters, I guess others like `get`, `head` and `post` also should be changed to `GET`, `HEAD`, and `POST` for consistency. It'll cause a breaking change, but it seems like that's the way we should take.
