### ISSUE TITLE
Addendum to using cpp-httplib in Windows

### ISSUE THREAD

**Issue by flameoftheforest** [yhirose/cpp-httplib#575]
When I am using CMake to build my W32 executable with cpp-httplib using MingGW. I found that I need the follow for the project to build:
```
if (WIN32)
  target_link_libraries(${PROJECT_NAME} wsock32 ws2_32)
endif()
``` 
I reckon it's important to document this in your readme for other users?

Thanks!

**Comment by yhirose** [comment]
@sum01, do you have any thought on this issue?

**Comment by sum01** [comment]
It might be because `_MSC_VER` isn't defined on non-MSVC compilers (like Mingw), which means https://github.com/yhirose/cpp-httplib/blob/15c4106a362cc1af719a05072540cf6aeb9c6f18/httplib.h#L137-L141 doesn't ever get defined.

So maybe we need to link to it in Cmake.  
But this should also mean that people not using Cmake also can't compile it? Maybe?

I tried to compile using MinGW (installed on Windows with Msys2) and it worked without edits to the `CMakeLists.txt`, so not too sure about that.

Was this Linux cross-compilation for Windows using MinGW?

**Comment by yhirose** [comment]
@flameoftheforest, could you answer the above question from @sum01?

**Comment by flameoftheforest** [comment]
I will try my best. I am not too good at this, honestly.

`Was this Linux cross-compilation for Windows using MinGW?` 
-> I am using MingGW (i686) on windows, my cmake runs off cmake-tools in VSCode.

`Also, are you sure we need wsock32 as well if we're linking ws2_32?` 
-> i tested based on @sum01's reply. wsock32 is not necessary! i am just using the answer i found here: https://stackoverflow.com/a/15124455

**Comment by sum01** [comment]
Before you commented I attempted a Linux cross-compilation for Windows using MinGW and it actually does fail without those libs.

So I suppose we need to link them either way. I'll push a fix.

**Comment by flameoftheforest** [comment]
Thanks the great work @yhirose  & @sum01 !
