### ISSUE TITLE
Using cpp-httplib to serve MJPEG over HTTP?

### ISSUE THREAD

**Issue by roddypratt** [yhirose/cpp-httplib#610]
I'm hoping to serve motion JPEG images over HTTP, but not sure if this is possible with cpp-httplib.

(outline of spec is here. https://en.wikipedia.org/wiki/Motion_JPEG#M-JPEG_over_HTTP - basically sending multipart data one frame at a time.)

If I've understood the library code, "multipart" boundary data is only sent when the "Ranges" are known in advance, which isn't possible  because images are rendered on the fly. 

I think I need to use a contentProvider and manually insert the boundary markers and relevant headers. Does this make sense?

**Comment by yhirose** [comment]
@roddypratt, thanks for the feedback. It seems that MJPEG over HTTP needs the content provider support without content length. I have just implemented it in httplib.h. I think you now have everything you need to support in. Please let me know if there is something missing.

https://github.com/yhirose/cpp-httplib/blob/e5dd410256de59e4ff0da91d87102d8e43f50cdd/test/test.cc#L2735-L2745

**Comment by roddypratt** [comment]
Thanks so much, that's working for me. It would be ideal if the manual header writing could be avoided, but this is looking good.

```C++
    resp.set_content_provider(
        "multipart/x-mixed-replace;boundary=MJP",
        [receiver](size_t offset, httplib::DataSink &sink) {
 
         // get JPEG data and size
          char * data = something; 
          long int size = sizeof(something);
  
          sink.os << "--MJP\r\n"
                     "Content-Type: image/jpeg\r\n"
                     "Content-Length: " << to_string(size) << "\r\n\r\n";
          sink.os.write(data, size);  // write JPEG data

          return true; // return 'false' if you want to cancel the process.
        },
        [] {});
```

**Comment by yhirose** [comment]
@roddypratt, glad to hear the news. 

As for avoiding manually writing the header, the chunked content provider (`set_chunked_content_provider`) does something similar. It handles dirty manual work for us, and we can just focus on providing chunked data.

https://github.com/yhirose/cpp-httplib/blob/e5dd410256de59e4ff0da91d87102d8e43f50cdd/httplib.h#L2722-L2822

We could do the similar for the multipart data as well (`set_multipart_data_provider` or something?). I am not planning to implement it, since I don't have any need in my projects for now. But I'll keep the idea in mind.

Thanks!
