### ISSUE TITLE
Silly question

### ISSUE THREAD

**Issue by HideakiAtsuyo** [yhirose/cpp-httplib#611]
I see cmake folder with others builds things i don't need only the [httplib.h](https://github.com/yhirose/cpp-httplib/blob/master/httplib.h) file?
Can i have an example to build it if i need to build it?

**Comment by yhirose** [comment]
@HideakiAtsuyo, thank you for the question. Since this is a single file header-only library, what you need to do is just to include `httplib.h` in your C++ source code. That's it!

So you don't have to use cmake to use this library at all. You can see more client and server examples in the examples folder. Hope it helps!
