### ISSUE TITLE
Use system proxy automatically

### ISSUE THREAD

**Issue by kotori2** [yhirose/cpp-httplib#631]
There are some APIs for different system to read system proxy instead from shell/cmd.
Such as [WinHttpGetIEProxyConfigForCurrentUser](https://docs.microsoft.com/en-us/windows/win32/api/winhttp/nf-winhttp-winhttpgetieproxyconfigforcurrentuser) or [SCDynamicStoreCopyProxies](https://developer.apple.com/documentation/systemconfiguration/1517088-scdynamicstorecopyproxies). It will be cool if there is function that can read this automatically.

**Comment by yhirose** [comment]
@kotori2, thank you for the feedback. I am not interested in supporting this at this moment, since I feel it's not the cpp-httlib's responsibility. For instance, cURL doesn't support it. Also it's not easy to provide the same functionality to all the platform, Linux OSs, macOS and Windows. But a pull request is always welcome of course. :)

**Comment by kotori2** [comment]
Actually cURL have plan to support it ~~but deferred for 4 years~~
https://curl.haxx.se/docs/todo.html#auto_detect_proxy
It seems like the upstream `libproxy` is not that reliable at that time.
