### ISSUE TITLE
Client: path as a const string&

### ISSUE THREAD

**Issue by mipac** [yhirose/cpp-httplib#657]
I wonder why the path in Get, Put, ... , methods is a const char *
In fine, this path is copied in Request::path which is a string

could it be more efficient to change the path argument type to cons string& ?

**Comment by yhirose** [comment]
@mipac, yes, `const string&` is of course more efficient. But if a user passes a raw C string, it will end up making a copy of it. On my use cases, there are more cases to pass C raw string rather than std::string.

It's easy to provide `const std::string&` version of Get, Put, Head, Post Patch, Option and Delete. (Too many...) A problem is that total number of client methods will be double. I am thinking that when I move this library to C++17, I'll use `std::string_view` which can handle any style of 'string'.

Thanks for your attention for it!

**Comment by mipac** [comment]
thank you for reply, and for that lib!

well, with in fine a copy in Request struct it's not a hot point to try to optimize memory alloc
I mean, it would be great to be able to manage allocation for requests and replies giving a way to use a pre allocated memory, and not create and destroy buffers
I go out of subject :) 
I'll post an issue to open the discussion

regards
