### ISSUE TITLE
HTTPS Proxy support

### ISSUE THREAD

**Issue by hanslivingstone** [yhirose/cpp-httplib#658]
Howdy, 

The HTTP proxy support for Client and SSLClient is awesome! It doesn't appear that there is support for connecting to an HTTPS proxy server yet though. I'd like to propose a feature to allow the SSLClient and Client (because users may want to make HTTP calls though an HTTPS proxy) to use an HTTPS proxy.

**Question:** Does this seem like a reasonable feature to pursue? We can probably start work an a PR if so.

Potential modifications:
- Update [ClientImpl::send()](https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L4685) to support a TLS handshake with the proxy. 
- Add new set_proxy_...() functions to provide an X509 store to validate the identity of the proxy server.
- _Stretch:_ Provide a way to use a separate mTLS client identity with the proxy server, since the proxy may require a different certificate than the destination server.

**Comment by yhirose** [comment]
@hanslivingstone, thanks for your suggestion. I don't have time to implement the feature though, you are very much welcome to the pull request. When you prepare it, I would like to ask you for the followings:

* Keep the addition simple as much as possible, and make it pluggable with `#ifdef CPPHTTPLIB_HTTPS_PROXY_SUPPORT`
* No additional third-party library
* Add necessary unit tests in `test/test.cpp`, so that they will catch any regressions

Than't all. Thank you for your contribution!

**Comment by hanslivingstone** [comment]
Thanks for the feedback. We'll work on a PR following your guidance (not sure when it can be started yet though, this may take a while).

**Comment by yhirose** [comment]
@hanslivingstone, any response? I am thinking to close this issue for now, since I am not interested in this feature yet, and no one asked for it. When you are ready to start implementing it, please let me know and I'll reopen it. Thanks!
