### ISSUE TITLE
Returning gzip encoded data

### ISSUE THREAD

**Issue by leonardorame** [yhirose/cpp-httplib#663]
I'm serving server-generated png images and wonder if I can gzip them before returning.

Currently I'm doing this:

```
std::string imageAsBytes = image->getTransformedImageAsBytes(zoom_factor, window_width, window_center, clip_left, clip_top, clip_width, clip_height);                                       
res.set_content(imageAsBytes.c_str(), imageAsBytes.size(), "image/png");
```

Is there a method to return a gzipped version of the same `imageAsBytes.c_str()`?.

**Comment by yhirose** [comment]
@leonardorame, thanks for the feedback. This library automatically applies gzip (or brotli) compression to a given input if a client accepts the compression format, but not for images or binaries because the compression doesn't work very well for such binary data. Please see this article for more information: https://stackoverflow.com/questions/11289369/why-png-size-doesnt-change-after-using-http-gzip-compression

But it's technically possible for you to do it by adding `image/png` to the following code:

https://github.com/yhirose/cpp-httplib/blob/b8cf739d275d636fa3a30f56e16c26080ef86578/httplib.h#L2147-L2154

Hope it helps.
