### ISSUE TITLE
Error::SSLServerVerification Linux only

### ISSUE THREAD

**Issue by gtnardy** [yhirose/cpp-httplib#673]
I'm getting this error when making HTTP requests (Client), but only on Linux, what does that error mean?
On my windows build there is no error with the same request/url.

I started getting this problem after this commit https://github.com/yhirose/cpp-httplib/commit/c4f3f9529b1cfe2ae861086e62ca9632e21f6843

**Comment by yhirose** [comment]
@gtnardy, thanks for the feedback.

Before the commit, it set `server_certificate_verification_` to `false` as default in order to ignore the server certificate verification logic. Of course, that's really bad for security. So, I changed the default value to `true`, and try to load the system ca_bundle. On your machine, `load_system_certs_on_windows` seems to be working correctly, but `SSL_CTX_set_default_verify_paths` doesn't. That's not a problem of httplib.h, but your linux system seems to cause the problem.

This change is same as `curl --insecure URL`. If you want to skip the verification, please call `enable_server_certificate_verification` with `false`.

Hope it helps!

**Comment by gtnardy** [comment]
Hey @yhirose thank you for the answer! I've tried recompiling it with `server_certificate_verification_ = false` but now I get error 4 (`Error::Read`). Would you know what does that mean?

**Comment by yhirose** [comment]
@gtnardy, `Error:Read` means that socket reading failed. You may get more information from unit tests with `cd test; make test`.

**Comment by gtnardy** [comment]
Okay, after further investigation, my problems started after https://github.com/yhirose/cpp-httplib/commit/6e1297cab01c2a4b1f68f82681d048361c5faff3.

**Comment by gtnardy** [comment]
Okay, after several tried, I figured it out it was a timeout problem. The server was taking more than 5 seconds to answer (`#define CPPHTTPLIB_READ_TIMEOUT_SECOND 5`), which curiously was triggering `Error::Read` only on linux, maybe that can be a bug on the lib idk. But that was what solved this.
Thank you @yhirose for the lib and for the time answering this ;)

**Comment by yhirose** [comment]
@gtnardy, thank you for the detailed report, and glad to hear your project is now working!
