### ISSUE TITLE
Delay in shutdown since moving to HTTP/1.1

### ISSUE THREAD

**Issue by sgraham** [yhirose/cpp-httplib#71]
Hello,

I had been using the default setting for the server which was HTTP/1.0 until recently. In test situations, the client code sends one request, and after the server has sent its response, it calls Server::stop(), ending the test. This still works correctly, however, I believe because of the change to 1.1, causes the server to wait for 5s (CPPHTTPLIB_KEEPALIVE_TIMEOUT_SECOND) before termination, which makes the tests take longer than necessary.

I can work around this by locally patching CPPHTTPLIB_KEEPALIVE_MAX_COUNT to 1, but I was just wondering if there's something different I should be sending from the client (I'm only using cpp-httplib for the server, not the client side). Alternatively, maybe it would be possible to have Server::stop() signal to the select() somehow that it should shut down immediately?

**Comment by yhirose** [comment]
@sgraham, I couldn't foresee the situation when I made the change. Sorry about that...

If you set 'close' value to the HTTP 'Connection' header in your client request, the server will close the session immediately after it sends the response. Does it work for you?
https://github.com/yhirose/cpp-httplib/blob/master/httplib.h#L1764-L1767

If it's not, I am thinking to add a new method like 'set_keepalive_max_count' or add another parameter to the constructor on the Sever class, so that we could configure the max count value . 

Please let me know your thought.

**Comment by sgraham** [comment]
Hi, thanks for looking and for the suggestion! It certainly wasn't obvious to me either that the change would cause this behaviour.

I tried adding "connection: close" on Mac, Linux, and Windows, and got three different results:

- On Windows (connecting using winhttp), adding connection:close makes it work as expected.
- On Linux (connecting directly with socket and some custom code), it doesn't seem necessary (i.e. was never broken) but I don't understand why.
- On Mac (connecting using NSURLConnection) it seems that the system code overrides the "connection" header value, and it always specifies keep-alive, so the server still hangs.

I'm not sure if it's really a "bug", but I feel like it would be nicer if the server did not have to rely on headers that the client set for it to behave in particular way (however, this is only for test code, so it's a bit artificial anyway).

I'll investigate what's happening on Linux, perhaps that will offer a simple solution.

**Comment by sgraham** [comment]
I'm still not sure why Linux doesn't delay for a long time. The select() on the worker thread just returns quickly (saying that there's something to read, a return of 1). Mac and Windows eventually timeout with a return of 0. I don't know why the behaviour is different though.

**Comment by yhirose** [comment]
Thanks for the investigation. For the linux problem, I made a separate issue (#73). I'll take a look at it when I have time.

It seems like the behavior of handling the HTTP Connection header is not consistent among operating systems. So I added 'set_keep_alive_max_count' method on Server class. Do you think if it can work for you?

**Comment by sgraham** [comment]
Thanks, that works perfectly!

**Comment by yhirose** [comment]
@sgraham, it's too late though, it seems I finally found the reason of this problem. This is because the way to handle the 'Keep-Alive' connection on HTTP/1.0 was incorrect...
I found it when I was testing the cpp-httplib server with Apache Bench which sends HTTP/1.0 requests, and the test gave me the same exact behavior as you reported.

I fixed it at cb11d9412e8705058f3b9ec7892ec2cde6ea7862. With this version, we don't have to adjust the keep alive max count anymore.

**Comment by sgraham** [comment]
Thanks, good news. I'll try updating and testing when I get a moment.

**Comment by jdbool** [comment]
@yhirose This is a huge problem for me on linux. By default, every client request takes around 5 minutes (300 seconds).

If I do this:
```cpp
client.set_timeout_sec(3);
client.set_keep_alive_max_count(0);
```
Every request still takes 3 seconds, even if the server is actually responding pretty much instantly.
I also tried setting the "Connection" request header to "close", no difference.

**Comment by jdbool** [comment]
I can "fix" it by using the direct IP with a "Host" header instead of using a domain name.

But, it isn't a DNS problem. If I set the timeout to 1 second it'll take 1 second, and if I set it to 100 seconds it'll take 100 seconds.
