### ISSUE TITLE
Client error codes meaning

### ISSUE THREAD

**Issue by grcasanova** [yhirose/cpp-httplib#724]
What do return integers (1, 2, sometimes 4) from method _error()_ mean?

Example code:
```
if(auto res = client.Post(...)) {
  ...
} else {
  cout<<res.error();
}
```

**Comment by yhirose** [comment]
@grcasanova, thanks for the question. Here is the list of possible errors:

https://github.com/yhirose/cpp-httplib/blob/536e7eb7f2ed27109423bea95c4c6ed41fbf040a/httplib.h#L725-L738

Since the error report has recently been added, I haven't had time to update README, yet.
I'll update it when I have time. Thanks!

**Comment by grcasanova** [comment]
Thanks for the reply.
I’m still confused, what does BindIP means? Connection? As broken link or a 500 http response?

**Comment by PixlRainbow** [comment]
BindIP is for server mode I think. If the server is unable to bind to the network interface?

**Comment by yhirose** [comment]
Yes.

https://github.com/yhirose/cpp-httplib/blob/536e7eb7f2ed27109423bea95c4c6ed41fbf040a/httplib.h#L1987-L1990

**Comment by grcasanova** [comment]
Ok great to know about 500 http and other error responses. It wouldn’t make sense to
treat them as library errors.

One last thing, I keep getting errors 2 and 4.
As I see that, it means sometimes the connection drops (err 2) and in other cases an invalid http response is given (err 4). Do you confirm?
