### ISSUE TITLE
React app as server frontend

### ISSUE THREAD

**Issue by noctera** [yhirose/cpp-httplib#742]
Is there any way i can use a react app as my server frontend?
Let's say i run my server on 127.0.0.1:8000 and I want to build a react frontend that runs on 127.0.0.1:8000 also where you can log in with 127.0.0.1:8000/login and change settings regarding to the server

**Comment by PixlRainbow** [comment]
This kind of question should really be asked over on stackoverflow instead of here.

Assuming that you are using React as a strictly browser-based library and NOT depending on Node.js to generate the views server-side, you may simply just dump the javascript, html and other asset files into a folder and [configure static file serving from that folder](https://github.com/yhirose/cpp-httplib#static-file-server).

If you are using React server-side as well, then you will have to set up Node.js on port 8000 to proxy/forward API backend requests to cpp-httplib server running on a different port. Configuration of node.js or React is not our responsibility.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the clear explanation!

**Comment by noctera** [comment]
Thank you for the explanation. I didn't think about the possibility asking this question on Stackoverflow.  I apologize for this
