### ISSUE TITLE
Wildcard or default sink?

### ISSUE THREAD

**Issue by Narase33** [yhirose/cpp-httplib#757]
Would it be possible to add a wildcard or default sink system to the lib?

Background: When I specify targets and a client tries to call a target I didnt specify, I dont get any notice of that. Not on server and not an client side. It would be very helpful if it would be possible to create a sink for targets that are not specifies. Something along

`httplib::Server::DefaultSink(Handler handler);`

TIA, Narase

**Comment by PixlRainbow** [comment]
I feel like this has been answered before, but I cannot find the other issue that mentions something similar at the moment.

There are two ways to accomplish what you are asking.
1. Since the target path is a regex pattern, you can simply create a target for `R".*"` and it will match all paths. I have not yet tested if existing paths take priority over such a general pattern however.
2. The [error handler](https://github.com/yhirose/cpp-httplib#error-handler) should handle any 404s, though it may also trigger on other errors as well.

**Comment by yhirose** [comment]
@Narase33, thank you for your question. As @PixlRainbow mentioned, you call `svr.Get(".*", ...)` at the last of your handler sequence.

Please see:
https://github.com/yhirose/cpp-httplib/blob/95d0b073bd3ae1300aad65d1ab95a43bcbeb30f0/httplib.h#L4474-L4485
