### ISSUE TITLE
Signal: SIGPIPE (Broken pipe) when client closes connection

### ISSUE THREAD

**Issue by JulZimmermann** [yhirose/cpp-httplib#77]
Hi,
when a client closes the connection to the cpp-httplib sever while the server is still processing the request, a sigpipe will occur: 

> SIGPIPE (Broken pipe)

This happens here:
```
 inline int SocketStream::write(const char* ptr, size_t size)
    {
        return send(sock_, ptr, size, 0);
    }
```

I fixed this problem by passing MSG_NOSIGNAL to send:
`send(sock_, ptr, size, MSG_NOSIGNAL)`

I sow e4ef0828b097eb52afc20d3accd675e5a0ab650a already tried to prevent signals, but this doesn't  work for me (probably some other library activates them again).

I think deactivating signals inside the library with MSG_NOSIGNAL would be a better approach then deactivate them globally via `signal(SIGPIPE, SIG_IGN);`

**Comment by yhirose** [comment]
@JulZimmermann, thanks for the bug report. Before implementing your suggestion, I would like to reproduce it on my machine and add a unit test for it as I do usually when fixing any problem. Could you show me a simple code snippet that reveals the problem, so that I could add it to test/test.cc? (Also could you tell what OS you are running on and what library do you think that activates signals again?) Thanks for your help!

**Comment by yhirose** [comment]
https://github.com/stephane/libmodbus/issues/175
https://github.com/lpeterse/haskell-socket/issues/8
