### ISSUE TITLE
How can I upload raw bytes using httplib::MultipartFormDataItems

### ISSUE THREAD

**Issue by fatrolls** [yhirose/cpp-httplib#789]
I tried using std::vector because it doesn't have problems I encountered in the past with 0x0 byte, but I can't seem to use it.

	httplib::MultipartFormDataItems items = {
		{ "version", "12345", "", "text/plain" },
		{ "upload", std::vector<unsigned char>(file, file + len).data(), "test.bin", "application/octet-stream" },
	};

also tried

	httplib::MultipartFormDataItems items = {
		{ "version", "12345", "", "text/plain" },
		{ "upload", std::vector<unsigned char>(file, file + len), "test.bin", "application/octet-stream" },
	};

I get this error

`Error	C2440	'initializing': cannot convert from 'initializer list' to 'std::vector<httplib::MultipartFormData,std::allocator<httplib::MultipartFormData>>'`

Before I used

	httplib::MultipartFormDataItems items = {
		{ "version", "12345", "", "text/plain" },
		{ "upload", std::string((char*)file, len), "test.bin", "application/octet-stream" },
	};

and it works no problem, but my product is experiencing crashes from long periods of time, so i'm trying to fix bugs all over the place and I can't figure out how to do this right

but I started to refactor my code to remove `std::string` from raw bytes even though it works fine with `std::string`, but ever since I started to work with crypto `std::string` was not good, I have no idea why `std::string` works good here even though I have alot of 0x0 bytes in `unsigned char* file`

**Comment by PixlRainbow** [comment]
when you provide `std::string((char*)file, len)`, you construct an object that carries both the `char*` data as well as the `len` and so you explicitly declare the length of the data and the compiler does not need to guess it.

If you simply put `std::vector::data()` it will return a raw `char*` with no length attribute, so when the compiler automatically inserts an `std::string` constructor it will use automatic length detection which will stop at the first `0x0` byte as it will assume it is a null-terminated human readable string by default.

If you simply put in `std::vector` directly it will fail because the the struct definition of `MultiPartFormData` requires that the `content` field be implicitly convertible to the type `std::string`, which `std::vector` is not.

___

Thus, if you require the use of an `std::vector` to hold your unsigned char array for some reason, you will have to convert it to an `std::string` while preserving the length information:
```cpp
std::string(myvector.begin(), myvector.end())
```
The constructor will compute the difference between the address of the first element `begin` and the address of the last element `end` and get the length that way.
___
> I have no idea why std::string works good here even though I have alot of 0x0 bytes in unsigned char* file

`std::string` isn't only for human readable strings. It is simply a wrapper around `char*` that adds some convenience features, such as automatic copying in function parameters, length tracking, concatenation, substring, etc. So `std::string` can hold any binary data, even if it has null/`0x0` bytes, as long as you make sure to explicitly specify the appropriate parameters in the constructor.

**Comment by fatrolls** [comment]
Oh thank you, I didn't know std::string had a `.data()` feature, learn something new everyday thank you :)
