### ISSUE TITLE
ssesrv example crash

### ISSUE THREAD

**Issue by fidodido2503** [yhirose/cpp-httplib#796]
when i run sse server (example ssesrv.cc ), and open url in chrome,it work fine,but when i close the tab or refresh page,server crash

**Comment by yhirose** [comment]
@fidodido2503, I have just tried it on my macOS, but it works fine even after closing the tab or refresh the page...

**Comment by fidodido2503** [comment]
I test in ubuntu 16.04, I just found in Windows 10 and MacOS don't have this problem, I changing send() call use the MSG_NOSIGNAL option, the crashing in linux problem is gone, I dont konw this way is reasonable

**Comment by yhirose** [comment]
@fidodido2503, thanks for the detail. I'll try to reproduce it on my Ubuntu (20.04).

**Comment by yhirose** [comment]
@fidodido2503, I just tested on Ubuntu (20.04), and it works fine as well. 

Server: Ubuntu 20.04 on VirtualBox on macOS
Client: Chrome on macOS

I'll close it for now until I get further evidence that helps me to reproduce the problem on my machine, so that I can debug it. Hope this information helps.

**Comment by fidodido2503** [comment]
I found the cause of the crash, because the vscode remote debug puglin, I used to remotely go to the host to debug via ssh, run the program in vscode, the vscode will automatically open a port forwarding, so this connection has not been truly disconected
