### ISSUE TITLE
Rating limits

### ISSUE THREAD

**Issue by portsip** [yhirose/cpp-httplib#807]
Hi, it's a great library, but could you please add the rating limits feature that silences to reject the request if the request is exceeds rating limits?

Thanks!

**Comment by yhirose** [comment]
@portsip, thanks for the feedback. It's a big thing and currently out of scope of this light-weight HTTP library. I think 'rate limit' can be done in various ways depending on what users want (Site level, API endpoint level, User session level, also strategies of recovery, and so on).

So it's too much for cpp-httplib to handle the rate limit feature as Nignx or other web servers do. But I may be able to allow 'middle-ware' support, so that users can supply such a functionality according to their needs.
