### ISSUE TITLE
Support http server poll one

### ISSUE THREAD

**Issue by cloudfreexiao** [yhirose/cpp-httplib#81]
my project want use cpp-httplib serve but I found it could  not third logic control the server poll
so my project when use listen  is blocking 
dose have any solution
something like this I think is nice [poll_one api](https://github.com/qicosmos/cinatra/blob/master/http_server.hpp#L133)
 thank you

**Comment by yhirose** [comment]
@cloudfreexiao, thank you for the feedback. I probably don't fully understand what you are trying to say. If you are requesting 'non-blocking' behavior like libuv, I am not planning to handle it because it's not easy for me to implement it correctly and support it on all three platforms, Linux, Mac and Windows. (Of course, a pull request is always welcome!)
