### ISSUE TITLE
SOURCETABLE 200 OK issue

### ISSUE THREAD

**Issue by ZmoOag** [yhirose/cpp-httplib#810]
Hi,
I code a NTRIP client for RTCM correction with a get request and I have a res.error()=4.
After investgation, I think it's because to "SOURCETABLE" word before "200".
It's funny, because the library works with only this URL :
http://rtk2go.com:2101
But not with some other like :
http://caster.centipede.fr:2101
My code :

	void ntrip_roscore::run() {
	    ros::Rate update_rate(10);
	    int conteur = 0;
	    std::thread get_thread([]() {
	            httplib::Client cli("http://rtk2go.com:2101");
	   	    if (auto res = cli.Get("/")) {
	 	        if (res->status == 200) {
		            std::cout << res->body << std::endl;
		    	}
		    } else {
		    	auto err = res.error();
		    	ROS_INFO("%i\n", err);
		    }
	    });
	    
	    while (ros::ok()) {
	    	if(conteur == 0){    
		    get_thread.join();
		    conteur = 1;
		}
		ros::spinOnce();
	    }
	}

Do you have a solution to fix this issue ?

**Comment by PixlRainbow** [comment]
Although NTRIP is *based on* http, it is not fully compliant with http, and thus is not compatible with http clients designed to stick to specifications.
The reason the first server works is because it can check for client NTRIP compatibility and wrap it's own NTRIP response in a http compliant response as needed. The second server does not do this. You can check by visiting the sites with a web browser to see if it says "invalid response".

If you would like httplib to support the NTRIP protocol, you should create a fork that implements changes to accept NTRIP responses instead of `http/1.1` responses. I do not think we can do this on the main repo without violating http specifications.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for the comment.
