### ISSUE TITLE
https client make request sometimes always blocking and not return.at windows system

### ISSUE THREAD

**Issue by xtayaitak** [yhirose/cpp-httplib#859]
I using https client for request more than 10000 times and use Proxy.
Sometimes it will never return,it is blocking and never return.
I was debug and find the call stack.the function block at openssl socket recv function. 

![image](https://user-images.githubusercontent.com/4498459/107678826-d490e980-6cd6-11eb-80bd-e1f2d7a7c94d.png)

How i can solve this prolem?

**Comment by yhirose** [comment]
@xtayaitak, thanks for the report, but I honestly don't know where the real cause of the symptom, since a number of factors are around the cpp-httplib. Once thing you could do is to run your server itself without, and try other servers on the proxy to see what will happen. Sorry that I can't help you much...
