### ISSUE TITLE
Issue with Regex

### ISSUE THREAD

**Issue by shoomoohin** [yhirose/cpp-httplib#860]
The regex on line 5260 that you're matching against on line 5263, appears to have an extra whitespace that causes the std::regex_match to fail and the response to not be sent ... at least in my circumstances (a GET)
Changing 
const static std::regex re("(HTTP/1\\.[01]) (\\d{3}) (.*?)\r\n");
to
const static std::regex re("(HTTP/1\\.[01]) (\\d{3})(.*?)\r\n");
does the trick.

This is working in VisStudio 2017 community fwiw ...

**Comment by PixlRainbow** [comment]
hi, please format your post and use backticks \` to wrap code snippets
This is because asterisks, underscores and other special characters will be consumed by the markdown formatter and used to activate italics, bold, etc. Backticks indicate that a line contains code and should not be auto reformatted.

**Comment by yhirose** [comment]
@shoomoohin, I think your trick actually breaks `Response::reason`...

**Comment by yhirose** [comment]
I fixed it in a correct way.
