### ISSUE TITLE
Sock5 Proxy Support?

### ISSUE THREAD

**Issue by NE1W01F** [yhirose/cpp-httplib#871]
hello 

i wanted to use the tor proxy to connect to my site but when i try it failed because it sent it as a http proxy and not a sock5 proxy. 
i have tried other methods like making tor open a HTTP Proxy but then i get request not supported. its a shame because this would be good to be able to use HTTP/HTTPS and SOCK Proxys.

```cpp
httplib::Client client(host.c_str());
    client.set_proxy("127.0.0.1", 9080);

    auto res = client.Get("/");
    if (res == nullptr) {
        std::cout << "[-] Failed\n";
        return;
    }
    if (res->status == 200) {
        std::cout << "[+] Connected to Tor Site\n";
        std::cout << res->body << std::endl;
    }
```

this was a simple test to see if it would work

```html
<html>
<head>
<title>This is an HTTP CONNECT tunnel, not a full HTTP Proxy</title>
</head>
<body>
<h1>This is an HTTP CONNECT tunnel, not an HTTP proxy.</h1>
<p>
It appears you have configured your web browser to use this Tor port as
an HTTP proxy.
</p><p>
This is not correct: This port is configured as a CONNECT tunnel, not
an HTTP proxy. Please configure your client accordingly.  You can also
use HTTPS; then the client should automatically use HTTP CONNECT.</p>
<p>
See <a href="https://www.torproject.org/documentation.html">https://www.torproject.org/documentation.html</a> for more information.
</p>
</body>
</html>
```
I added HTTP proxy port to the tocc file but thats the responce i get. is they a work around for this or would you need to add a sock5 support.

**Comment by yhirose** [comment]
@NE1W01F, I probably don't understand what you are trying to do, also I guess you are talking about socks5 instead of sock5.

Anyway, cpp-httplib supports HTTP proxy with Basic Auth and Digest Auth. You can see unit text examples [here](https://github.com/yhirose/cpp-httplib/blob/master/test/test_proxy.cc).

As for socks5, I am not planning to support it at this point because my personal projects and projects at work don't need it, and it seems it is not an easy task to implement it. But a pull request from you is always welcome! Hope it helps.
