### ISSUE TITLE
Headers and params

### ISSUE THREAD

**Issue by oofsamy** [yhirose/cpp-httplib#897]
Hey, it's me again, sorry if I waste your guys' time, but I just read the reply to my issue, and helped me, apart from the fact that I'm not sure on how to implement headers with params, (I might be misunderstanding what params is, because in my eyes, it's the body/payload/content, but I need the header to put the authorization and application/json).

**Comment by yhirose** [comment]
@oofsamy, it actually don't understand the question that you are asking... Could you try what you want with curl first, since curl has everything you want and well documented. When you succeed, please let me know what you did with curl. Then, I'll point out where you need to see in README. Sorry that I can't give you much help...

**Comment by PixlRainbow** [comment]
Params is a different object type and can be provided as a separate parameter. You can provide both headers and params at the same time. Just read the code and choose the most appropriate [function overload](https://www.geeksforgeeks.org/function-overloading-c/).
**For example:**
https://github.com/yhirose/cpp-httplib/blob/6ff84d34d15c8cec51cd36246412b159bbb48484/httplib.h#L6077-L6081
This Client Post() function variant has headers as the second parameter and params as the third parameter.
