### ISSUE TITLE
[Question] Client send multi-part using file streams.

### ISSUE THREAD

**Issue by FrozenSource** [yhirose/cpp-httplib#922]
Hi,

I have a question. The samples provide a very detailed way of receiving multipart files.
Now my question is how would one send files based on a std::ifstream?
I have two files that I need to send in one request. Now I could implement it myself but you, as the developer(s), might know the best way.

This is what I have at the backend:
```
    std::ofstream out;
    std::unordered_map<string, string> files;
    if (!content_reader(
            [&](const httplib::MultipartFormData& file) {
                size_t existend = 0;
                string file_out = uploads_root + file.filename;
                while (std::filesystem::is_regular_file(file_out)) {
                    file_out = uploads_root + file.filename + std::to_string(++existend);
                }

                out.open(file_out);

                if (!out.good()) return false;

                files.try_emplace(file.name, file_out);

                return true;
            },
            [&](const char* data, size_t data_length) {
                out.write(data, data_length);
                return true;
            }));
```

Similarly, I want to do the same on the client but then with an input stream, since these files are quite large (like gigabytes)...
Do you have a nice way of doing this?

Sincerely,
FrozenSource

**Comment by yhirose** [comment]
@FrozenSource, thank you for the feedback. In fact, there is no easy way to do it on client so far. The following API is an only API to handle multipart form data items, and it requires to set your data to `std::string content` in `struct MultipartFormData` beforehand.

```cpp
  Result Post(const char *path, const MultipartFormDataItems &items);
```

https://github.com/yhirose/cpp-httplib/blob/2a70c45697822621c4c50b5e26834d42ed41df01/httplib.h#L6159

If `struct MutipartFormData` can have `ContentProvider`, you can do what you want. But it requires a quite bit change to support it, and I am not planning to do it at this point. (Of course a pull require is always welcome. :))

You can actually construct and send multipart form data manually via ContentProvider as below.

```cpp
size_t multipart_form_data_size = ???; // You should calculate the total size of data beforehand.
cli.Post(
  "/stream",
  multipart_form_data_size,
  [](size_t offset, size_t length, DataSink &sink) {
    // Output multipart form data manually with calling sink.write(..., ...);
    return true;
  },
  content_type.c_str());
```

It's not convenient, but it gives the best performance because you can control everything.
Hope it helps!

**Comment by FrozenSource** [comment]
Thanks, Thats kind of what I was expecting :). Next month I have some free time. Will look into this!
