### ISSUE TITLE
Unresolved externals after linking

### ISSUE THREAD

**Issue by ANF-Studios** [yhirose/cpp-httplib#924]
Hello there,
I'm trying to get OpenSSL support and I'm having a hard time linking. It works just fine, except it throws a few linker errors (undefined references) when I link my version of a static library to an executable:
![image](https://user-images.githubusercontent.com/68814933/116952657-310e0000-ac59-11eb-8b42-29565102bada.png)

I have no idea why this is happening. I have a primary project, to which I link those two dependencies listed [here](https://github.com/yhirose/cpp-httplib#ssl-support), and then, the final static lib links to the executable, which fails. And, of course, linking those two static libraries to both doesn't make a difference.

Any assistance regarding this matter?

PS: You can inspect the project/setup here on [this repo](https://github.com/ANF-Studios/pastemyst.cpp/tree/dab382604f1fee4f0c0a9babaddd13f906bf3d7a).

**Comment by yhirose** [comment]
@ANF-Studios, you could take a look at CMakeLists.txt that @sum01 kindly maintains. It supports Windows environment as well. In my case, I use vkpkg to install the latest OpenSSL and there is no problem to build. Hope it helps!

**Comment by sum01** [comment]
@ANF-Studios It looks like [you're trying to link old libraries.](https://github.com/ANF-Studios/pastemyst.cpp/blob/dab382604f1fee4f0c0a9babaddd13f906bf3d7a/premake5.lua#L42-L43)

The library names changed sometime ago, and [cpp-httplib requires >= v1.1.1](https://github.com/yhirose/cpp-httplib/issues/192)
The new names are `crypto` and `ssl`.

Not sure about the specific names to look for since I don't use Windows, but I'm sure you can find whichever it's supposed to be in your install dir.
