### ISSUE TITLE
Split server code into different cpp files

### ISSUE THREAD

**Issue by krish-2214** [yhirose/cpp-httplib#925]
I've written a http server using this library. It is working as expected when accessed by clients. My server code is written in single c++ source file, is there a way to split them across different source files? As I have many service end points, file becomes larger and not easily maintainable. 
For example, all urls with root context **/app/...** to be in root_app.cpp
all urls wih root **/device/..** to be in device.cpp
At the end all services must be accessible at the same port.

**Comment by yhirose** [comment]
@krish-2214, yes you can. The one way is to make the server as a global variable and your can refer to it in other source files. Or you can define functions taking a reference of the server in other sources, so that you can pass the server instance in the main source to the functions in other sources. This issue has actually nothing to do with cpp-httplib, but a general C++ question though...
