### ISSUE TITLE
bad body return with params

### ISSUE THREAD

**Issue by equisde** [yhirose/cpp-httplib#927]
hello i'm new to C++ and i've been trying this library but for some reason i'm getting a bad body after sending a request with params
what i except to get is `done`
what i'm getting is  `ù§]i☻@F§]i☻bad hwid` it always change except for bad hwid since its printed by doing comparison
this is my code
```
#include <iostream>

#include "httprquest.hpp"

	int auth() {
	httplib::Client cli("http://test.net");
	const char* username = "sometestuser";
	const char* password = "sometestpassword";
	const char* hwid = "sometesthwid";
	httplib::Params params{
		{"username", username},
		{"password", password},
		{"hwid", hwid},
	};
	auto res = cli.Post("/something.php",params);
    std::string test = res->body;
	printf((const char *)&test);
	if (test == "Access Granted#") {
		return 1;
	}
	else if(test == "Bad Access") {
		return 2;
	}
	else {
		return 3;
	}

	}

int main()
{

	if (auth() == 1) {
		printf("done");
	}
	else if (auth() == 2) {
		printf("not granted");
	}
	else {
		printf("bad hwid");
	}
}
```
by testing with the full uri with static params i get what i want but when using the params function i can't get what i want
any help? thanks in advance

**Comment by PixlRainbow** [comment]
hi, you cannot simply cast a `std::string *` into a `const char *`.

std strings are structured C++ objects that manage an underlying `char *`. They contain data like the allocated size of the underlying buffer and an address pointing to the actual buffer as well as other helper data. If you attempt to cast an std string pointer directly into a const char pointer, you are telling C++ that you want to access the std string object structure itself as if it was an array of bytes/chars.

What you really want to do is access the string's underlying buffer, not the whole object itself. std string has a class method called `c_str()` or `data()` which you can use. So instead of `printf((const char *)&test)` you would use `printf(test.c_str())` for example.

**Comment by PixlRainbow** [comment]
Another unrelated but important note: you are potentially calling the `auth()` function twice here:
```cpp
	if (auth() == 1) {
		printf("done");
	}
	else if (auth() == 2) {
		printf("not granted");
	}
	else {
		printf("bad hwid");
	}
```
When the first `if` statement fails, the second `else if` will be run, which will call `auth` a second time in order to compare the return value with `2`

**Comment by PixlRainbow** [comment]
> by testing with **the full uri with static params** i get what i want but when using **the params function** i can't get what i want

Note that the params parameter of the post function does NOT construct and append the query parameters to the URL path. The params parameter of the post function will add the query parameters to the post request body following the `application/x-www-form-urlencoded` format. In other words, it behaves differently from the params parameter of the get function.

However, you should still be able to call `httplib::detail::append_query_params(path, params)` manually to add the params to the URL.

**Comment by yhirose** [comment]
@PixlRainbow, thanks for answering this question!
