### ISSUE TITLE
SSL suites support

### ISSUE THREAD

**Issue by samthesuperhero** [yhirose/cpp-httplib#933]
Dear contributors,

fighting with server / client implementation,

can't understand, where can I see if any of these four supported ?
`TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256`
`TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384`
`TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256`
`TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384`

Because what I get is that when I use my certificates / keys generated for `ECDHE`, `ECDSA` and `SHA256` - server replies with Fatal Handshake Failure (see it through Wireshark..)

Libraries version: `OpenSSL 1.1.1k FIPS 25 Mar 2021`

Because I can't see any logging or diagnostics, but I have to use el. curves X.509 authentication (due to project requirements..), no other way...

Can you please help where to look for issue ?

And, with certificates given in `test` folder all my code works.

[my-certs-used.zip](https://github.com/yhirose/cpp-httplib/files/6478104/my-certs-used.zip)

**Comment by yhirose** [comment]
@samthesuperhero, thank you for the feedback. Since I am not an expert of OpenSSL, I am not in a position to give you a meaningful help... But at least on client size, you can obtain the `SSL_CTX *` via `ssl_context()` method, and call whatever necessary OpenSSL APIs with it.
https://github.com/yhirose/cpp-httplib/blob/75fdb06696d4e27b590135c1e4a226b4e13e9bd7/httplib.h#L1355
As for server side, I haven't added the `ssl_context()` method, yet. If you need it, I'll added it to SSLServer class as well.

**Comment by samthesuperhero** [comment]
@yhirose, thank you, now clear, !!
