### ISSUE TITLE
Question: how to check authentication server-side?

### ISSUE THREAD

**Issue by codic12** [yhirose/cpp-httplib#974]
`cpp-httplib` supports basic authentication on the client side, but how do we validate it on the server side? I couldn't find any examples, so I thought I'd just ask on GitHub Issues. Also, thanks for your work on the awesome library!

**Comment by codic12** [comment]
Wrote a simple parser, but I think that there should be library support for this feature.
```cpp
#include "base64.hh"
#include "httplib.h"
#include <iostream>
#include <sstream>
#include <vector>
using namespace httplib;

int main(void) {
  Server svr;

  svr.Get("/hi", [](const Request &req, Response &res) {
    if (req.has_header("Authorization")) {
      std::cout << "Auth\n";
      auto val = req.get_header_value("Authorization");
      std::cout << val << '\n';
      std::vector<std::string> tokens;
      std::stringstream ss(val);
      std::string buf;
      while (ss >> buf) {
        tokens.push_back(buf);
      }
      if (tokens.at(0) != "Basic") {
        std::cout << "Not basic auth\n";
        return; // we only support basic auth
      }

      auto decoded = base64_decode(tokens.at(1));
      tokens.clear();
      std::cout << decoded << '\n';
      ss = std::stringstream(decoded);
      while (std::getline(ss, buf, ':')) {
        tokens.push_back(buf);
      }
      auto username = tokens.at(0);
      auto pass = tokens.at(1);
      std::cout << "username is: " << username << " and password is: " << pass
                << '\n';
    }
    res.set_content("Hello World!", "text/plain");
  });

  svr.listen("localhost", 8080);
}
```

**Comment by codic12** [comment]
Also, how do I set the response code?

**Comment by yhirose** [comment]
@codic12, thank you for the feedback. As you noticed, there is no authentication support on server side... (I haven't needed it in my projects so far. That's why it's not supported yet.) Your implementation looks good to me. Sorry that you have to do it manually. I am ok to provide such a helper function to parse the authorization header. The only thing is that once the basic authorization is supported, others (like digest and bearer token auth) should be supported as well for consistency. But I simply don't have time to work on it unless my projects need the functionality.

> Also, how do I set the response code?

You can simply set status code to `res.status` as below.

https://github.com/yhirose/cpp-httplib/blob/80be649de7cd821652aa1be4d0c9cf5930f18225/test/test.cc#L1045-L1048

**Comment by codic12** [comment]
Got it, thank you for the informative reply! I will look into writing bearer and digest implementations and then maybe submit a pull request.

**Comment by codic12** [comment]
Never mind, just saw this https://github.com/yhirose/cpp-httplib/issues/375#issuecomment-597319746
