### ISSUE TITLE
Why doesn't this library work for manual mapping injection?

### ISSUE THREAD

**Issue by fatrolls** [yhirose/cpp-httplib#985]
When I inject a DLL which contains some HTTPS GET/POST Requests none of them have error  Result.error() always returns 0. (which means Success).

Try using this injector below with settings Injection type: (Manual mapping),  (native inject works fine (which is just LoadLibrary).

I used API Monitor it seems the connect() function contains wrong addr_info? maybe i'm wrong. But the connect() does return SOCKET_ERROR 10035= A non-blocking socket operation could not be completed immediately.

I attached a project for a Proof of Concept you can recompile it, it's fully compiled for both x64 and x86, and the Xenos Injector is setup for Notepad.exe in C:\Windows\System32 you can try it yourself you will see it give error =0.

Manual Mapping is a good method I use for my project and it's a shame I cannot use HTTP Requests from this library together with it, can you suggest a hack if it's not fixable?

[HttpLibDLLTestManualMapping.zip](https://github.com/yhirose/cpp-httplib/files/6774837/HttpLibDLLTestManualMapping.zip)

**Comment by yhirose** [comment]
@fatrolls, thanks for the feedback, but I am in a good position to look into it since I don't know anything about 'manual mmapping injection' and simply don't have time to debug it.

I feel that it's not cpp-httplib specific problem, but a general program with WinSock2 usage. Could you first make sure of it?

Thanks!

**Comment by fatrolls** [comment]
I tried regular Winsock2 usage as you said and yes it works fine for both Native Inject and Manual Mapping injection.

I think the problem is your pointer to addr_info gets changed during the loop iteration of getaddressinfo, since the connect_or_bind is a r lambda, it doesn't fire instantly as the looping is in progress but more like a delayed callback firing my assumption. (but im just making stuff up lol not a good C++ coder).

[HttpLibDLLTestManualMapping(Regular Winsock2 Example).zip](https://github.com/yhirose/cpp-httplib/files/6779522/HttpLibDLLTestManualMapping.Regular.Winsock2.Example.zip)

**Comment by yhirose** [comment]
@fatrolls, glad to hear that the direct WinSock2 access fixes the issue! So please keep using your WinSock2 native implementation in your project instead of cpp-httplib. Since the main purpose of this library is to give a cross-platform HTTP functionality to my personal projects and projects at work, your situation seems to be out of scope of this library...

As you can see the code httplib.h, it's just a very thin wrapper over OS provided socket API (POSIX on Linux and macOS, WinSock2 on Windows). So if you already find the workable solution, I think it isn't hard to port it to httplib.h. 

Thank you for your understanding!
