### ISSUE TITLE
Upgrade to Websocket

### ISSUE THREAD

**Issue by codic12** [yhirose/cpp-httplib#992]
Hello,
 While websocket server support is out of scope for this library, is there any way to integrate another websocket server library into httplib and upgrade requests at a specific path only?

**Comment by yhirose** [comment]
@codic12, thanks for the feedback. I don't come up with any easy way to support websockt unless making a big surgery to `process_request `. If a request from client is upgrade request and a server accepts the request and respond, `process_request` needs to keep the tcp socket alive and pass it to a websocket manager. I am not planning to do such enhancement for now since my projects don't need websocket support. But you can try it on your fork of cpp-httplib and please send a pull request if it succeeds. Thanks!
