### ISSUE TITLE
Need documentation for post-stream

### ISSUE THREAD

**Issue by elcuco** [yhirose/cpp-httplib#994]
I am porting my code from another library to this one, and my code is something like:

``` C++
// I also add some headers, but this is not relevant to this example
auto client = std::make_unique<old_client>("http://somwhere");

// I am streaming data as I read it from the sync device, 
// in practice this will be a chunked upload - as I don't know the exact length 
do {
   std::vector<char> data = read_data();
   if (data.size() < 0) {
     break;
   }
   client->send(data);
} while (true);
```

I am trying to understand how to implement this on this library, but documentation is lacking.  I found `ContentProviderWithoutLength` but this seems like an async way, and my code is very synchronous.

Is this supported at all?

**Comment by yhirose** [comment]
@elcuco, thanks for the feedback. Unfortunately, cpp-httplib only supports the chunked transfer encoding for streaming data with indefinite length. Here is the documentation in README. Also you can find some examples for both server and client sides in`test/test.cc`.
https://github.com/yhirose/cpp-httplib#chunked-transfer-encoding-1

Sorry that this library doesn't come with good documentation, since this is just my after-work personal project. :)
Hope the comment helps you!

**Comment by PixlRainbow** [comment]
@elcuco the writing style may seem async, but the client is actually single-threaded and synchronous.
```cpp
httplib::Client client("http://somewhere");
auto res = client.Post("/somepath", [&](size_t offset, httplib::DataSink &sink) { // lambda subroutine that will be repeated until sink marked done
  std::vector<char> data = read_data();
  if (data.size() < 0) {
    sink.done();
  } else {
    std::copy(data.begin(), data.end(), std::ostream_iterator<char>(sink.os));
  }
  return true;
}); // this call will block until the loop is complete
```

**Comment by DiegoActionItem** [comment]
> Sorry that this library doesn't come with good documentation, since this is just my after-work personal project. :)

No problems, everything is good.
The API you link me to is async, and this kinda messes my workflow, as I need this to be synchroneous (aka, no callbacks).  Does this library support this?

**Comment by yhirose** [comment]
It doesn't.

**Comment by elcuco** [comment]
> @elcuco the writing style may seem async, but the client is actually single-threaded and synchronous.
> 
> ```c++
> httplib::Client client("http://somewhere");
> auto res = client.Post("/somepath", [&](size_t offset, httplib::DataSink &sink) {
>   // this lambda subroutine will be repeated until sink marked done OR the return value is false
>   std::vector<char> data = read_data();
>   if (data.size() < 0) {
>     sink.done();
>   } else {
>     std::copy(data.begin(), data.end(), std::ostream_iterator<char>(sink.os));
>   }
>   return true;
> }); // this call will block until the loop is complete
> ```
OK - this complicates things for me... as my app is actually single threaded (code should compile on ESP and Linux - and we are restricted from doing much modifications to the code). 

How could I approach this port? (I assume I would run the http requests in another thread... and then send data from the main thread to this new thread). What other alternatives do I have?

**Comment by PixlRainbow** [comment]
The simplest option is to use C++ standard library's `std::async`, example [here](https://github.com/yhirose/cpp-httplib/issues/312#issuecomment-570812127), but as someone else in that issue explains, this may incur some performance cost if you do requests very frequently and rapidly because `std::async` will create and destroy threads for each instance.
