### ISSUE TITLE
KEEPALIVE_MAX_COUNT and THREAD_POOL_COUNT

### ISSUE THREAD

**Issue by tomgrean** [yhirose/cpp-httplib#997]
I think CPPHTTPLIB_KEEPALIVE_MAX_COUNT should be less than CPPHTTPLIB_THREAD_POOL_COUNT.
I made a small server, and configured CPPHTTPLIB_THREAD_POOL_COUNT to 3, and use the default value of CPPHTTPLIB_KEEPALIVE_MAX_COUNT (5).
Then found that some browsers (such as chrome) would make many parallel connection with keep-alive header. thus the server stop serving the incoming connection until any of the 3 threads timed out for CPPHTTPLIB_KEEPALIVE_TIMEOUT_SECOND.

maybe adding some check and give compile warning on such miss-configured macro values is a good choice.

**Comment by yhirose** [comment]
@tomgrean, thanks for the report. Yes, this situation happens if users set incorrect values to the macro symbols.

>  I think CPPHTTPLIB_KEEPALIVE_MAX_COUNT should be less than CPPHTTPLIB_THREAD_POOL_COUNT.

This is actually not enough. Even if you set 2 to CPPHTTPLIB_KEEPALIVE_MAX_COUNT, this problem stays. The real solution is to increase CPPHTTPLIB_THREAD_POOL_COUNT to at least 8 according to [this stackoverflow post](https://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser). Or set 1 to CPPHTTPLIB_KEEPALIVE_MAX_COUNT.

> maybe adding some check and give compile warning on such miss-configured macro values is a good choice.
Unfortunately, I can't take your suggestion, since the thread pool implementation is just a **default** thread pool implementation. Users are very much encouraged to provide a more efficient thread pool implementation if exists on the target system. So I don't want to make such a tied dependency between CPPHTTPLIB_KEEPALIVE_MAX_COUNT and CPPHTTPLIB_THREAD_POOL_COUNT.

But anyway, I really appreciate your report that someone else could also fall into easily. In the future, I'll refer to this issue when I receive the same issue again. Thanks a lot!
